project:
  type: book
  output-dir: docs
  resources: 
     - favicon.ico
     - data/Credit.csv
     - data/College.csv
     - data/Auto.csv
     - data/Carseats.csv
     - data/Boston.csv
     
include-in-header: custom-head.html
book:
  title: "Probability And Business Statistics"
  author: "Pamela Schlosser"
  date: "4/15/2026"
  chapters:
    - index.qmd
    - introR.qmd
    - descriptives.qmd
    - dataprep.qmd
    - probability.qmd
    - ttests.qmd
    - anova.qmd
    - regression.qmd
    - ai_viz.qmd
    - summary.qmd
    - references.qmd
  navbar:
    right:
      - text: "Course Assistant"
        href: chat.html

format:
  html:
    css: styles.css
    number-sections: false
    include-in-header: custom-head.html
    favicon: favicon.ico

filters:
  - webr

editor: source