<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2024-08-09">

<title>Analysis of Variance (ANOVA) – Probability And Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./regression.html" rel="next">
<link href="./ttests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-64b801fe9b6685c0a799f7172ecad621.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-CNGRHWZ7C6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-CNGRHWZ7C6');
</script>

<!-- ============================================================
     Statistics Course Assistant — Floating Chat Bubble
     Appears on every page of the book.
     Set WORKER_URL below to your Cloudflare Worker URL.
     ============================================================ -->
<style>
  /* ── Floating button ── */
  #chat-fab {
    position: fixed;
    bottom: 28px;
    right: 28px;
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 4px 20px rgba(79, 142, 247, 0.45);
    z-index: 9999;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  #chat-fab:hover {
    transform: scale(1.08);
    box-shadow: 0 6px 28px rgba(79, 142, 247, 0.6);
  }

  #chat-fab svg { width: 24px; height: 24px; color: #fff; }

  /* unread dot */
  #chat-fab-dot {
    position: absolute;
    top: 4px;
    right: 4px;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: #ff5a5a;
    border: 2px solid #fff;
    display: none;
  }

  /* ── Chat panel ── */
  #chat-panel {
    position: fixed;
    bottom: 96px;
    right: 28px;
    width: 380px;
    max-width: calc(100vw - 40px);
    height: 520px;
    max-height: calc(100vh - 120px);
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 16px;
    display: none;
    flex-direction: column;
    z-index: 9998;
    box-shadow: 0 12px 48px rgba(0,0,0,0.5);
    overflow: hidden;
    animation: panelIn 0.25s ease;
    font-family: 'IBM Plex Sans', -apple-system, sans-serif;
  }

  #chat-panel.open { display: flex; }

  @keyframes panelIn {
    from { opacity: 0; transform: translateY(12px) scale(0.97); }
    to   { opacity: 1; transform: translateY(0) scale(1); }
  }

  /* panel header */
  #chat-panel-header {
    padding: 14px 16px;
    background: #181c27;
    border-bottom: 1px solid #2a2f3e;
    display: flex;
    align-items: center;
    gap: 10px;
    flex-shrink: 0;
  }

  #chat-panel-header .logo {
    width: 30px;
    height: 30px;
    border-radius: 7px;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 600;
    color: #fff;
    font-family: 'IBM Plex Mono', monospace;
    flex-shrink: 0;
  }

  #chat-panel-header .title { flex: 1; }

  #chat-panel-header .title h3 {
    font-size: 13px;
    font-weight: 600;
    color: #e8eaf0;
    margin: 0;
    line-height: 1.2;
  }

  #chat-panel-header .title p {
    font-size: 11px;
    color: #7a8099;
    margin: 0;
    font-family: 'IBM Plex Mono', monospace;
  }

  #chat-close-btn {
    background: none;
    border: none;
    color: #7a8099;
    cursor: pointer;
    padding: 4px;
    border-radius: 4px;
    display: flex;
    align-items: center;
    transition: color 0.15s;
  }

  #chat-close-btn:hover { color: #e8eaf0; }
  #chat-close-btn svg { width: 16px; height: 16px; }

  /* messages */
  #chat-messages {
    flex: 1;
    overflow-y: auto;
    padding: 14px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    scroll-behavior: smooth;
  }

  #chat-messages::-webkit-scrollbar { width: 3px; }
  #chat-messages::-webkit-scrollbar-thumb { background: #2a2f3e; border-radius: 3px; }

  .cm {
    display: flex;
    gap: 8px;
    animation: msgIn 0.2s ease;
  }

  @keyframes msgIn {
    from { opacity: 0; transform: translateY(4px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  .cm-av {
    width: 22px;
    height: 22px;
    border-radius: 5px;
    flex-shrink: 0;
    margin-top: 1px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 9px;
    font-weight: 700;
    font-family: 'IBM Plex Mono', monospace;
  }

  .cm.user .cm-av  { background: #1e2640; border: 1px solid #2e3a5a; color: #4f8ef7; }
  .cm.bot .cm-av   { background: linear-gradient(135deg, #4f8ef7, #7c5cfc); color: #fff; }
  .cm.error .cm-av { background: #3a1010; color: #ff8a8a; }

  .cm-text {
    flex: 1;
    background: #141720;
    border: 1px solid #2a2f3e;
    border-radius: 10px;
    padding: 8px 11px;
    font-size: 13px;
    line-height: 1.55;
    color: #e8eaf0;
    min-width: 0;
    word-break: break-word;
  }

  .cm.user .cm-text  { background: #1e2640; border-color: #2e3a5a; }
  .cm.error .cm-text { background: #1c1010; border-color: #5a2e2e; color: #ff8a8a; }

  .cm-text p { margin: 0 0 6px; }
  .cm-text p:last-child { margin-bottom: 0; }

  .cm-text code {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 3px;
    padding: 1px 5px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 11.5px;
    color: #a5c3ff;
  }

  .cm-text pre {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 6px;
    padding: 10px 12px;
    overflow-x: auto;
    margin: 6px 0;
  }

  .cm-text pre code {
    background: none;
    border: none;
    padding: 0;
    font-size: 12px;
    color: #c8d8ff;
  }

  .cm-text ul, .cm-text ol { padding-left: 16px; margin: 4px 0; }
  .cm-text li { margin-bottom: 3px; }
  .cm-text strong { color: #fff; font-weight: 600; }

  /* typing dots */
  .typing-dots { display: flex; gap: 3px; align-items: center; padding: 2px 0; }
  .typing-dots span {
    width: 5px; height: 5px; border-radius: 50%;
    background: #7a8099;
    animation: td 1.2s infinite;
  }
  .typing-dots span:nth-child(2) { animation-delay: 0.2s; }
  .typing-dots span:nth-child(3) { animation-delay: 0.4s; }

  @keyframes td {
    0%,60%,100% { transform: translateY(0); opacity:0.4; }
    30% { transform: translateY(-4px); opacity:1; }
  }

  /* welcome inside panel */
  .panel-welcome {
    text-align: center;
    padding: 20px 10px;
    color: #7a8099;
  }

  .panel-welcome p {
    font-size: 12.5px;
    margin: 0 0 14px;
    line-height: 1.5;
    color: #7a8099;
  }

  .panel-chips {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    justify-content: center;
  }

  .panel-chip {
    background: #181c27;
    border: 1px solid #2a2f3e;
    border-radius: 14px;
    padding: 5px 10px;
    font-size: 11.5px;
    color: #7a8099;
    cursor: pointer;
    transition: all 0.15s;
    font-family: 'IBM Plex Mono', monospace;
    text-align: left;
  }

  .panel-chip:hover {
    border-color: #4f8ef7;
    color: #4f8ef7;
    background: rgba(79,142,247,0.07);
  }

  /* input row */
  #chat-input-row {
    padding: 10px 12px;
    border-top: 1px solid #2a2f3e;
    background: #181c27;
    display: flex;
    gap: 8px;
    align-items: flex-end;
    flex-shrink: 0;
  }

  #chat-input {
    flex: 1;
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 8px;
    padding: 8px 11px;
    font-family: -apple-system, sans-serif;
    font-size: 13px;
    color: #e8eaf0;
    resize: none;
    min-height: 36px;
    max-height: 100px;
    outline: none;
    line-height: 1.4;
    transition: border-color 0.2s;
    overflow-y: auto;
  }

  #chat-input:focus { border-color: #4f8ef7; }
  #chat-input::placeholder { color: #7a8099; }

  #chat-send {
    width: 36px;
    height: 36px;
    border-radius: 8px;
    border: none;
    background: #4f8ef7;
    color: #fff;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    transition: opacity 0.15s;
  }

  #chat-send:hover { opacity: 0.85; }
  #chat-send:disabled { opacity: 0.3; cursor: not-allowed; }
  #chat-send svg { width: 15px; height: 15px; }

  /* mobile adjustments */
  @media (max-width: 480px) {
    #chat-panel { right: 12px; bottom: 80px; width: calc(100vw - 24px); }
    #chat-fab   { right: 16px; bottom: 16px; }
  }
</style>

<!-- Floating Action Button -->
</head><body class="nav-sidebar floating nav-fixed"><button id="chat-fab" onclick="toggleChat()" title="Course Assistant" aria-label="Open course assistant">
  <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
  </svg>
  <div id="chat-fab-dot"></div>
</button>

<!-- Chat Panel -->
<div id="chat-panel">
  <div id="chat-panel-header">
    <div class="logo">R∑</div>
    <div class="title">
      <h3>Course Assistant</h3>
      <p>R &amp; Statistics</p>
    </div>
    <button id="chat-close-btn" onclick="toggleChat()" aria-label="Close">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>

  <div id="chat-messages">
    <div class="panel-welcome" id="panel-welcome">
      <p>Ask me anything about R, statistics concepts, or your code.</p>
      <div class="panel-chips">
        <div class="panel-chip" onclick="chipSend(this)">mean vs median?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is skewness?</div>
        <div class="panel-chip" onclick="chipSend(this)">How do I use filter()?</div>
        <div class="panel-chip" onclick="chipSend(this)">Explain na.rm=TRUE</div>
        <div class="panel-chip" onclick="chipSend(this)">How to read a CSV?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is kurtosis?</div>
      </div>
    </div>
  </div>

  <div id="chat-input-row">
    <textarea id="chat-input" rows="1" placeholder="Ask a question…" onkeydown="chatKey(event)" oninput="chatResize(this)"></textarea>
    <button id="chat-send" onclick="chatSend()" aria-label="Send">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="22" y1="2" x2="11" y2="13"></line>
        <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
      </svg>
    </button>
  </div>
</div>

<script>
  // ============================================================
  // Set this to your Cloudflare Worker URL after deploying

  // ============================================================
  var CHAT_WORKER_URL = 'https://statchat.pamela-schlosser.workers.dev';
  // ============================================================

  var chatHistory = [];
  var chatLoading = false;
  var chatIsOpen  = false;

  function toggleChat() {
    chatIsOpen = !chatIsOpen;
    var panel = document.getElementById('chat-panel');
    var dot   = document.getElementById('chat-fab-dot');
    if (chatIsOpen) {
      panel.classList.add('open');
      dot.style.display = 'none';
      setTimeout(function() {
        var inp = document.getElementById('chat-input');
        if (inp) inp.focus();
      }, 100);
    } else {
      panel.classList.remove('open');
    }
  }

  function chipSend(el) {
    var inp = document.getElementById('chat-input');
    inp.value = el.textContent.trim();
    chatSend();
  }

  function chatKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      chatSend();
    }
  }

  function chatResize(el) {
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 100) + 'px';
  }

  function escHtml(s) {
    return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  function mdToHtml(text) {
    text = text.replace(/```(\w*)\n?([\s\S]*?)```/g, function(_,l,c) {
      return '<pre><code>' + escHtml(c.trim()) + '</code></pre>';
    });
    text = text.replace(/`([^`]+)`/g, '<code>$1</code>');
    text = text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    text = text.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
    text = text.replace(/(<li>.*<\/li>\n?)+/g, function(m) { return '<ul>' + m + '</ul>'; });
    text = text.split(/\n{2,}/).map(function(p) {
      p = p.trim();
      if (!p || p.charAt(0) === '<') return p;
      return '<p>' + p.replace(/\n/g,'<br>') + '</p>';
    }).join('');
    return text;
  }

  function addMsg(role, content, typing) {
    var welcome = document.getElementById('panel-welcome');
    if (welcome) welcome.remove();
    var box = document.getElementById('chat-messages');
    var d   = document.createElement('div');
    d.className = 'cm ' + role;
    var av = role==='user' ? 'you' : role==='bot' ? 'ai' : '!';
    if (typing) {
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text" id="cm-typing">' +
        '<div class="typing-dots"><span></span><span></span><span></span></div>' +
        '</div>';
    } else {
      var html = role==='user'
        ? '<p>' + escHtml(content) + '</p>'
        : mdToHtml(content);
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text">' + html + '</div>';
    }
    box.appendChild(d);
    box.scrollTop = box.scrollHeight;
    if (!chatIsOpen && role === 'bot') {
      document.getElementById('chat-fab-dot').style.display = 'block';
    }
  }

  function removeTyping() {
    var t = document.getElementById('cm-typing');
    if (t) t.closest('.cm').remove();
  }

  async function chatSend() {
    if (chatLoading) return;

    var el   = document.getElementById('chat-input');
    var text = el.value.trim();
    if (!text) return;

    addMsg('user', text);
    chatHistory.push({ role: 'user', content: text });
    el.value = '';
    el.style.height = 'auto';

    chatLoading = true;
    document.getElementById('chat-send').disabled = true;
    addMsg('bot', '', true);

    try {
      var res = await fetch(CHAT_WORKER_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 1024,
          messages: chatHistory
        })
      });

      removeTyping();

      if (!res.ok) {
        var err = await res.json().catch(function() { return {}; });
        var msg = err.error || ('HTTP ' + res.status);
        addMsg('error', res.status === 429
          ? 'Rate limit reached. Please wait a moment and try again.'
          : 'Something went wrong: ' + msg);
        chatHistory.pop();
      } else {
        var data  = await res.json();
        var reply = (data.content && data.content[0] && data.content[0].text) || '(no response)';
        chatHistory.push({ role: 'assistant', content: reply });
        addMsg('bot', reply);
      }

    } catch(err) {
      removeTyping();
      addMsg('error', 'Network error: ' + err.message);
      chatHistory.pop();
    }

    chatLoading = false;
    document.getElementById('chat-send').disabled = false;
  }
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Probability And Business Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./chat.html"> 
<span class="menu-text">Course Assistant</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./anova.html"><span class="chapter-title">Analysis of Variance (ANOVA)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Software Know-How</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introR.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to R and RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Descriptive Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataprep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Preparation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ai.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Using AI</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Analysis of Variance (ANOVA)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Recommended Further Reading Materials</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a Glance</a></li>
  <li><a href="#lesson-objectives" id="toc-lesson-objectives" class="nav-link" data-scroll-target="#lesson-objectives">Lesson Objectives</a></li>
  <li><a href="#consider-while-reading" id="toc-consider-while-reading" class="nav-link" data-scroll-target="#consider-while-reading">Consider While Reading</a></li>
  <li><a href="#analysis-of-variance-anova" id="toc-analysis-of-variance-anova" class="nav-link" data-scroll-target="#analysis-of-variance-anova">Analysis of Variance (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#omnibus-test" id="toc-omnibus-test" class="nav-link" data-scroll-target="#omnibus-test">Omnibus test</a></li>
  <li><a href="#anova-methodology" id="toc-anova-methodology" class="nav-link" data-scroll-target="#anova-methodology">ANOVA Methodology</a></li>
  </ul></li>
  <li><a href="#type-i-and-type-ii-errors" id="toc-type-i-and-type-ii-errors" class="nav-link" data-scroll-target="#type-i-and-type-ii-errors">Type I and Type II Errors</a>
  <ul class="collapse">
  <li><a href="#some-reasons-for-error" id="toc-some-reasons-for-error" class="nav-link" data-scroll-target="#some-reasons-for-error">Some Reasons For Error</a></li>
  </ul></li>
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova">One-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#steps-for-conducting-a-one-way-anova" id="toc-steps-for-conducting-a-one-way-anova" class="nav-link" data-scroll-target="#steps-for-conducting-a-one-way-anova">Steps for Conducting a One-Way Anova</a></li>
  <li><a href="#statistics-in-a-one-way-anova-table" id="toc-statistics-in-a-one-way-anova-table" class="nav-link" data-scroll-target="#statistics-in-a-one-way-anova-table">Statistics in a One-Way ANOVA Table</a>
  <ul class="collapse">
  <li><a href="#explained-variance" id="toc-explained-variance" class="nav-link" data-scroll-target="#explained-variance">Explained Variance</a></li>
  <li><a href="#unexplained-variance" id="toc-unexplained-variance" class="nav-link" data-scroll-target="#unexplained-variance">Unexplained Variance</a></li>
  <li><a href="#calculating-f" id="toc-calculating-f" class="nav-link" data-scroll-target="#calculating-f">Calculating F</a></li>
  </ul></li>
  <li><a href="#subsetting-data-for-anova" id="toc-subsetting-data-for-anova" class="nav-link" data-scroll-target="#subsetting-data-for-anova">Subsetting Data for ANOVA</a></li>
  <li><a href="#example-of-a-one-way-anova" id="toc-example-of-a-one-way-anova" class="nav-link" data-scroll-target="#example-of-a-one-way-anova">Example of a One-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up-null-and-alternative-hypothesis" id="toc-step-1-set-up-null-and-alternative-hypothesis" class="nav-link" data-scroll-target="#step-1-set-up-null-and-alternative-hypothesis">Step 1: Set Up Null and Alternative Hypothesis</a></li>
  <li><a href="#step-2-compute-the-f-test-statistic-and-p-value" id="toc-step-2-compute-the-f-test-statistic-and-p-value" class="nav-link" data-scroll-target="#step-2-compute-the-f-test-statistic-and-p-value">Step 2: Compute the F-test Statistic and p-Value</a></li>
  <li><a href="#step-3-interpret-the-probability-and-write-a-conclusion." id="toc-step-3-interpret-the-probability-and-write-a-conclusion." class="nav-link" data-scroll-target="#step-3-interpret-the-probability-and-write-a-conclusion.">Step 3: Interpret the Probability and Write a conclusion.</a></li>
  <li><a href="#step-4-if-model-is-significant-run-post-hoc-tests" id="toc-step-4-if-model-is-significant-run-post-hoc-tests" class="nav-link" data-scroll-target="#step-4-if-model-is-significant-run-post-hoc-tests">Step 4: If Model is Significant, Run Post-Hoc Tests</a></li>
  <li><a href="#bonferroni-method" id="toc-bonferroni-method" class="nav-link" data-scroll-target="#bonferroni-method">Bonferroni Method</a></li>
  <li><a href="#tukey-hsd-method" id="toc-tukey-hsd-method" class="nav-link" data-scroll-target="#tukey-hsd-method">Tukey HSD Method</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova">Two-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#steps-for-conducting-a-two-way-anova" id="toc-steps-for-conducting-a-two-way-anova" class="nav-link" data-scroll-target="#steps-for-conducting-a-two-way-anova">Steps for Conducting a Two-Way ANOVA</a></li>
  <li><a href="#statistics-in-a-two-way-anova-table" id="toc-statistics-in-a-two-way-anova-table" class="nav-link" data-scroll-target="#statistics-in-a-two-way-anova-table">Statistics in a Two-Way ANOVA Table</a>
  <ul class="collapse">
  <li><a href="#explained-variance-1" id="toc-explained-variance-1" class="nav-link" data-scroll-target="#explained-variance-1">Explained Variance</a></li>
  <li><a href="#unexplained-variance-1" id="toc-unexplained-variance-1" class="nav-link" data-scroll-target="#unexplained-variance-1">Unexplained Variance</a></li>
  <li><a href="#calculating-f-test-statistics" id="toc-calculating-f-test-statistics" class="nav-link" data-scroll-target="#calculating-f-test-statistics">Calculating F-test Statistics</a></li>
  </ul></li>
  <li><a href="#using-factor-inline-in-anova-formulas" id="toc-using-factor-inline-in-anova-formulas" class="nav-link" data-scroll-target="#using-factor-inline-in-anova-formulas">Using factor() Inline in ANOVA Formulas</a></li>
  <li><a href="#example-of-a-two-way-anova" id="toc-example-of-a-two-way-anova" class="nav-link" data-scroll-target="#example-of-a-two-way-anova">Example of a Two-way ANOVA</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up-null-and-alternative-hypothesis-1" id="toc-step-1-set-up-null-and-alternative-hypothesis-1" class="nav-link" data-scroll-target="#step-1-set-up-null-and-alternative-hypothesis-1">Step 1: Set Up Null and Alternative Hypothesis</a></li>
  <li><a href="#step-2-compute-the-f-test-statistics-and-p-values" id="toc-step-2-compute-the-f-test-statistics-and-p-values" class="nav-link" data-scroll-target="#step-2-compute-the-f-test-statistics-and-p-values">Step 2: Compute the F-test Statistics and p-Values</a></li>
  <li><a href="#step-3-interpret-the-probabilities-and-write-a-conclusion" id="toc-step-3-interpret-the-probabilities-and-write-a-conclusion" class="nav-link" data-scroll-target="#step-3-interpret-the-probabilities-and-write-a-conclusion">Step 3: Interpret the Probabilities and Write a Conclusion</a></li>
  <li><a href="#step-4-if-model-is-significant-run-post-hoc-tests-1" id="toc-step-4-if-model-is-significant-run-post-hoc-tests-1" class="nav-link" data-scroll-target="#step-4-if-model-is-significant-run-post-hoc-tests-1">Step 4: If Model is Significant, Run Post-Hoc Tests</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#two-way-anova-with-interaction" id="toc-two-way-anova-with-interaction" class="nav-link" data-scroll-target="#two-way-anova-with-interaction">Two-Way ANOVA with Interaction</a>
  <ul class="collapse">
  <li><a href="#statistics-in-a-two-way-with-interaction-anova" id="toc-statistics-in-a-two-way-with-interaction-anova" class="nav-link" data-scroll-target="#statistics-in-a-two-way-with-interaction-anova">Statistics in a Two-Way with Interaction ANOVA</a></li>
  <li><a href="#steps-for-conducting-a-two-way-anova-with-interaction" id="toc-steps-for-conducting-a-two-way-anova-with-interaction" class="nav-link" data-scroll-target="#steps-for-conducting-a-two-way-anova-with-interaction">Steps for Conducting a Two-Way ANOVA with Interaction</a>
  <ul class="collapse">
  <li><a href="#explained-variance-2" id="toc-explained-variance-2" class="nav-link" data-scroll-target="#explained-variance-2">Explained Variance</a></li>
  <li><a href="#unexplained-variance-2" id="toc-unexplained-variance-2" class="nav-link" data-scroll-target="#unexplained-variance-2">Unexplained Variance</a></li>
  <li><a href="#calculating-f-test-statistics-1" id="toc-calculating-f-test-statistics-1" class="nav-link" data-scroll-target="#calculating-f-test-statistics-1">Calculating F-test Statistics</a></li>
  </ul></li>
  <li><a href="#example-of-a-two-way-anova-with-interaction" id="toc-example-of-a-two-way-anova-with-interaction" class="nav-link" data-scroll-target="#example-of-a-two-way-anova-with-interaction">Example of a Two-way ANOVA with Interaction</a>
  <ul class="collapse">
  <li><a href="#step-1-write-the-null-and-alternate-hypotheses" id="toc-step-1-write-the-null-and-alternate-hypotheses" class="nav-link" data-scroll-target="#step-1-write-the-null-and-alternate-hypotheses">Step 1: Write the null and alternate hypotheses</a></li>
  <li><a href="#step-2-compute-the-f-test-statistic-for-the-interaction-and-its-p-value." id="toc-step-2-compute-the-f-test-statistic-for-the-interaction-and-its-p-value." class="nav-link" data-scroll-target="#step-2-compute-the-f-test-statistic-for-the-interaction-and-its-p-value.">Step 2: Compute the F-test statistic for the interaction and its p-value.</a></li>
  <li><a href="#step-3-interpret-the-probability-and-write-a-conclusion.-1" id="toc-step-3-interpret-the-probability-and-write-a-conclusion.-1" class="nav-link" data-scroll-target="#step-3-interpret-the-probability-and-write-a-conclusion.-1">Step 3: Interpret the probability and write a conclusion.</a></li>
  <li><a href="#step-4-if-the-interaction-is-significant-examine-simple-effects-or-conduct-post-hoc-tests." id="toc-step-4-if-the-interaction-is-significant-examine-simple-effects-or-conduct-post-hoc-tests." class="nav-link" data-scroll-target="#step-4-if-the-interaction-is-significant-examine-simple-effects-or-conduct-post-hoc-tests.">Step 4: If the interaction is significant, examine simple effects or conduct post-hoc tests.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#choose-command" id="toc-choose-command" class="nav-link" data-scroll-target="#choose-command">choose() command</a></li>
  <li><a href="#using-ai" id="toc-using-ai" class="nav-link" data-scroll-target="#using-ai">Using AI</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Analysis of Variance (ANOVA)</span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<ul>
<li>The main goal of this lesson is to understand and conduct one- and two-way ANOVAs and interpret their results. We will learn about Type I and Type II errors, which are applicable forms of error in any hypothesis test. We will also learn how to conduct post-hoc tests when an ANOVA yields significant results.</li>
</ul>
<section id="at-a-glance" class="level3">
<h3 class="anchored" data-anchor-id="at-a-glance">At a Glance</h3>
<ul>
<li>In order to succeed in this section, you will need to apply what you learned about variable types (quantitative versus categorical) and hypothesis testing in earlier lessons We will learn how to conduct and interpret an ANOVA, which allows us to compare groups (from a categorical/factor variable) with respect to a continuous variable. Unlike the independent samples t-test covered in Module 5, which is limited to comparing two groups, the ANOVA is meant for three or more groups. We can also follow up a significant ANOVA with post-hoc tests to see which groups are different from each other in regards to the continuous variable.</li>
</ul>
</section>
<section id="lesson-objectives" class="level3">
<h3 class="anchored" data-anchor-id="lesson-objectives">Lesson Objectives</h3>
<ul>
<li>Conduct and interpret a one-way ANOVA.</li>
<li>Choose and use post-hoc tests and contrasts.</li>
<li>Conduct and interpret a two-way ANOVA.</li>
</ul>
</section>
<section id="consider-while-reading" class="level3">
<h3 class="anchored" data-anchor-id="consider-while-reading">Consider While Reading</h3>
<ul>
<li>In this lesson, we continue with our discussion of both hypothesis testing and using inference. However, we are no longer limiting ourselves to one or two populations. ANOVA consists of the calculations that provide information about levels of variability within a regression model and form a basis for calculating tests of significance. This means that ANOVA can be conducted as we will do here, and as part of a regression analysis.</li>
<li>ANOVA is used to determine if there are differences among three or more populations. In cases of only two groups, an independent samples t-test should be used as was discussed in an earlier lesson. When reading, be sure to make connections back to variable data type, and know that with ANOVA, we are testing for group differences where groups are the categorical X variable or variables, and we want to see if there are group differences in regards to a continuous/numerical Y.</li>
</ul>
</section>
<section id="analysis-of-variance-anova" class="level1">
<h1>Analysis of Variance (ANOVA)</h1>
<ul>
<li>An ANOVA is used to determine if there are differences among three or more groups. If there were only two groups, an independent samples t-test should be used.</li>
<li>In conducting an ANOVA, we utilize a completely randomized design, comparing sample means computed for each treatment to test whether the population means differ.</li>
<li>ANOVA has underlying assumptions to be met, and there are alternative methods to use when the assumptions are not met. The assumptions are extensions of those we use when comparing just two populations in a t.test:
<ul>
<li>The populations are normally distributed.</li>
<li>The population standard deviations are unknown but assumed equal.</li>
<li>Samples are selected independently from each population.</li>
</ul></li>
<li>Here we compare a total of <span class="math inline">\(k\)</span> populations, rather than just two. Therefore, the competing hypotheses for the one-way ANOVA:
<ul>
<li><span class="math inline">\(H_0: \mu_1 = \mu_2 = \cdots= \mu_k\)</span></li>
<li><span class="math inline">\(H_A:\)</span> Not all population means are equal</li>
</ul></li>
</ul>
<section id="omnibus-test" class="level2">
<h2 class="anchored" data-anchor-id="omnibus-test">Omnibus test</h2>
<ul>
<li>A significant result indicates the omnibus test is significant and that there is a difference between the means. This only suggests that there is at least one group difference somewhere between groups. This is not useful in determining which means are different from each other. Therefore, for the alternative hypothesis to be supported, at least one group must be different from the rest.</li>
<li>Then, if we find a significant omnibus test, we continue our analysis with planned contrasts and post-hoc tests, which determine which means are statistically significantly different from one another.</li>
</ul>
</section>
<section id="anova-methodology" class="level2">
<h2 class="anchored" data-anchor-id="anova-methodology">ANOVA Methodology</h2>
<ul>
<li>The core idea behind ANOVA is to compare two sources of variability: how much the group means differ from each other (<em>between-group variability</em>) versus how much individual observations differ within their own groups (<em>within-group variability</em>). If the between-group variability is much larger than the within-group variability, it suggests that the group means are not all equal. This ratio forms the F-statistic.</li>
</ul>
<ol type="1">
<li>We first compute the amount of variability between the sample means. This is known as the <em>between-treatments estimate</em>, which compares the sample means to the overall mean, sometimes called the grand mean, or the average of all the values in the data set.</li>
<li>Then, we measure how much variability there is within each sample. This is known as the <em>within-treatments estimate</em>, which is essentially a measure of error.</li>
<li>A ratio of the first quantity to the second forms our test statistic which follows the <span class="math inline">\(F_{df1,df2}\)</span> distribution, where the degrees of freedom are calculated from the number of groups - 1 (<span class="math inline">\(df_1: k-1\)</span>) and the total number of observations minus the number of groups (<span class="math inline">\(df_2: n_t-k\)</span>).</li>
</ol>
<ul>
<li>Note an F distribution behaves differently than a z- or a t- distribution.
<ul>
<li>The z-distribution shows how many sample standard deviations (SD) some value is away from the mean.</li>
<li>The t-distribution shows how many standard errors (SE) away from the mean.</li>
<li>The F-distribution is used to compare 2 populations’ variances. <img src="Pictures/Ch7/FDist.png" title="F Distribution Visualization" class="img-fluid" alt="The F Distribution"></li>
</ul></li>
<li>The F distribution is noted by its:
<ul>
<li>Right-Skewness: The distribution is positively skewed, meaning the right tail is longer than the left tail.</li>
<li>Non-Negative Values: The F-distribution is only defined for positive values.</li>
<li>Shape and Degrees of Freedom: The exact shape of the F-distribution depends on the degrees of freedom. As the degrees of freedom increase, the distribution becomes less skewed and more closely approximates a normal distribution.</li>
</ul></li>
</ul>
</section>
</section>
<section id="type-i-and-type-ii-errors" class="level1">
<h1>Type I and Type II Errors</h1>
<ul>
<li><p>In any hypothesis test, including an ANOVA, it is important to acknowledge that there is error, and that it is possible to come up with the wrong conclusion. An important note is that we are calculating results and making conclusions based on probability calculated given the sample we have, the timing it was collected, and any biases that might have been used in designing and securing the data set. We could also be violating assumptions that make the findings less accurate if still accurate at all.<br>
</p></li>
<li><p>Therefore, it is really important to understand the limitations of what we are doing, and that there is always error! Our main goal as analysts is to minimize error as much as possible in selecting the right parameters, and having a data set that is as unbiased as possible so that the interpretation is as accurate as possible and consistent with the population it is inferring for.</p></li>
<li><p>There are 2 types of error:</p>
<ul>
<li>Type I Error: Committed when we reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_0\)</span> is actually true. False Positive.
<ul>
<li>Occurs with probability <span class="math inline">\(\alpha\)</span>. <span class="math inline">\(\alpha\)</span> is chosen apriori.</li>
</ul></li>
<li>Type II Error: Committed when we do not reject <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_0\)</span> is actually false. False Negative.
<ul>
<li>Occurs with probability <span class="math inline">\(\beta\)</span>. Power of the Test = 1−<span class="math inline">\(\beta\)</span>.”For a given sample size <span class="math inline">\(n\)</span>, a decrease in <span class="math inline">\(\alpha\)</span> will increase <span class="math inline">\(\beta\)</span> and vice versa.”</li>
</ul></li>
</ul></li>
<li><p>Both <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> decrease as <span class="math inline">\(n\)</span> increases. Therefore, an increase in sample size decreases these two types of error.</p></li>
<li><p>The two types of error can be mapped onto a hypothesis decision chart that shows the two decisions, reject <span class="math inline">\(H_0\)</span> or fail to reject <span class="math inline">\(H_0\)</span>, alongside what is actually happening in reality.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch7/Type1_2Error.png" title="Type I and Type II Error" class="img-fluid figure-img"></p>
<figcaption>Type I and Type II Error</figcaption>
</figure>
</div>
<ul>
<li><p>Consider the following example of competing hypotheses that relate to the court of law.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: An accused person is innocent.</li>
<li><span class="math inline">\(H_A\)</span>: An accused person is guilty.</li>
</ul></li>
<li><p>Now, think through the consequences of making either a Type I and Type II error:</p>
<ul>
<li>Type I error (False Positive): Conclude that the accused is guilty when in reality, they are innocent.</li>
<li>Type II error (False Negative): Conclude that the accused is innocent when in reality, they are guilty.</li>
</ul></li>
</ul>
<p><img src="Pictures/Ch7/TypeErrorA.png" title="Type I and Type II Error" class="img-fluid" alt="Type I and Type II Error"> - Both types of error are extremely bad!</p>
<ul>
<li>In taking another example, let’s look at some sample results from a polygraph. A polygraph (lie detector) is an instrument used to determine if an individual is telling the truth. These tests are considered to be 89% reliable. In other words, if an individual lies, there is a 89$ chance that the test will detect a lie. Let there also be a 10% chance that the test erroneously detects a lie even when the individual is actually telling the truth. Consider the null hypothesis, “the individual is telling the truth,” and look at all 4 options.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch7/TypeErrorB.png" title="Type I and Type II Error" class="img-fluid figure-img"></p>
<figcaption>Type I and Type II Error</figcaption>
</figure>
</div>
<ul>
<li><p>With the error conclusions from Type I and Type II error in this example, we either predicted that someone was being honest when they were telling a lie, or we called someone a liar that was telling the truth! Again, both are bad.</p></li>
<li><p>Now for a more recent example. Let’s look at the vaccine designed to prevent the spread of COVID-19. Again, we cannot assume the vaccine works without a significant test, so the alternative hypothesis <span class="math inline">\(H_A\)</span> is framed as against status quo, or that the vaccine does help.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Vaccine does not help prevent spread of COVID-19.</li>
<li><span class="math inline">\(H_A\)</span>: Vaccine does help prevent the spread of COVID-19.<br>
</li>
</ul></li>
<li><p>Now, think through the consequences of making either a Type I and Type II error and come to the fill out the 4 boxes like I did below.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch7/TypeErrorC.png" title="Type I and Type II Error" class="img-fluid figure-img"></p>
<figcaption>Type I and Type II Error</figcaption>
</figure>
</div>
<ul>
<li><p>In this scenario, if we made a Type I error, we would make people get vaccines that were not helpful. If we made a Type II error, we would end up not administering the vaccine when in fact it actually could help prevent the spread of COVID-19. In making the decision to give the vaccine, these types of errors were weighed (along with others) and the vaccine ended up being administered because the Type II error was considered more problematic than the Type I.</p></li>
<li><p>Some tests are designed to minimize Type I error, while others are designed to minimize Type II error. Selecting alpha levels that are smaller will help reduce Type I error, but at the cost of Type II error. And again, increasing sample size reduces both error.</p></li>
</ul>
<section id="some-reasons-for-error" class="level2">
<h2 class="anchored" data-anchor-id="some-reasons-for-error">Some Reasons For Error</h2>
<ul>
<li>Measurement error refers to the difference between a measured quantity and its true value which could be due to random error or systematic error.
<ul>
<li>Random error refers to naturally occurring errors that are to be expected.</li>
<li>Systematic error refers to miss-calibrated instruments causing error in measurement.</li>
</ul></li>
<li>Bias — the tendency of a sample statistic to systematically over- or underestimate a population parameter.
<ul>
<li>Selection bias refers to a systematic exclusion of certain groups from consideration for the sample.</li>
<li>Non-response bias refers to a systematic difference in preferences between respondents and non-respondents to a survey or a poll.</li>
<li>Social Desirability bias refers to a bias that refers to the systematic difference between a group’s “socially acceptable” responses to a survey or poll.</li>
</ul></li>
</ul>
</section>
</section>
<section id="one-way-anova" class="level1">
<h1>One-Way ANOVA</h1>
<ul>
<li>One-way ANOVA compares population means based on one categorical variable.</li>
</ul>
<section id="steps-for-conducting-a-one-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="steps-for-conducting-a-one-way-anova">Steps for Conducting a One-Way Anova</h2>
<ol type="1">
<li>Write the null and alternate hypotheses.</li>
<li>Compute the F-test statistic and the probability for the test statistic (p-value).</li>
<li>Interpret the probability and write a conclusion.</li>
<li>If model is significant, run post-hoc tests.</li>
</ol>
</section>
<section id="statistics-in-a-one-way-anova-table" class="level2">
<h2 class="anchored" data-anchor-id="statistics-in-a-one-way-anova-table">Statistics in a One-Way ANOVA Table</h2>
<ul>
<li>There are a number of statistics being calculated with an aov() command, with the goal of producing the F-test statistic, which corresponds to a p-value that we can interpret the same way as we did in the earlier lessons (p-value &lt; alpha = significant result - reject the <span class="math inline">\(H_0\)</span>).</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch7/1WayANOVA.PNG" title="Formulas for One Way ANOVA" class="img-fluid figure-img"></p>
<figcaption>One Way ANOVA Formulas</figcaption>
</figure>
</div>
<section id="explained-variance" class="level3">
<h3 class="anchored" data-anchor-id="explained-variance">Explained Variance</h3>
<ul>
<li><p>In a one-way ANOVA, first, we compute the <em>explained variance</em>, which in a one-way ANOVA is the sum of squares due to treatments (SSTR), where the treatment is our grouping variable. The explained variance suggests that the variation in outcome can be explained by a model, or in our case, a grouping variable. In computing the SSTR, we square the deviation between each group mean (<span class="math inline">\(\bar{y}_j\)</span>) and the grand mean <span class="math inline">\(\bar{y}\)</span> and multiply it by the sample size (<span class="math inline">\(n_j\)</span>) and sum up all the values <span class="math inline">\(\sum\)</span>. This leads to the following formula:</p>
<ul>
<li><span class="math inline">\(SSTR = \sum{n_j*(\bar{y}_j-\bar{y}) ^2}\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSTR are computed by the number of groups <span class="math inline">\((k-1)\)</span>.</p>
<ul>
<li><span class="math inline">\(df_{sstr} = k-1\)</span></li>
</ul></li>
<li><p>The mean square due to treatment (MSTR) takes the value for the SSTR and divides by the treatment’s degrees of freedom <span class="math inline">\((k-1)\)</span>.</p>
<ul>
<li><span class="math inline">\(MSTR = SSTR/(k-1)\)</span></li>
</ul></li>
<li><p>Above in the overall methodology, the MSTR corresponds to the <em>between-treatments estimate</em>.</p></li>
</ul>
</section>
<section id="unexplained-variance" class="level3">
<h3 class="anchored" data-anchor-id="unexplained-variance">Unexplained Variance</h3>
<ul>
<li><p>There is also a measure of <em>unexplained variance</em>, which we term error. In a one-way ANOVA, this unexplained variance refers to variability in the outcome that is not explained by the grouping variable. In the table, this error is called the sum of squares error (SSE). SSE is calculated by first multiplying the sample size of group and subtracting one (<span class="math inline">\(n_j-1\)</span>), and then multiplying that number by its group variance (<span class="math inline">\(\sigma^2_i\)</span>). Once all groups are calculated, we add it up (<span class="math inline">\(\sum\)</span>). This leads to the following formula:</p>
<ul>
<li><span class="math inline">\(SSE = \sum^k_{j=1}{(n_j-1)*\sigma^2_j}\)</span></li>
</ul></li>
<li><p>This formula above considers the formula and definition of variance (<span class="math inline">\(\sigma^2\)</span>) and simplifies the formula, which you can also use:</p>
<ul>
<li><span class="math inline">\(SSE = \sum^k_{j=1}\sum^n_{i=1}(y_{ij}-\bar{y_j})^2/(n-k)\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSE are computed by taking the total number of observations (<span class="math inline">\(n_t\)</span>) and subtracting the number of groups <span class="math inline">\((k)\)</span>.</p>
<ul>
<li><span class="math inline">\(df_{sse} = n_t-k\)</span></li>
</ul></li>
<li><p>The mean square due to error (MSE) takes the SSE and divides by the appropriate degrees of freedom (<span class="math inline">\(n_t-k\)</span>).</p>
<ul>
<li><span class="math inline">\(MSE = SSE/(n_t-k)\)</span></li>
</ul></li>
<li><p>Above in the overall methodology, the MSE corresponds to the <em>within-treatments estimate</em>.</p></li>
<li><p>There is a total sum of squares (SST) being calculated in an ANOVA, which refers to the total variance (explained and unexplained). This value is calculated as the total number of observations minus 1 (<span class="math inline">\(n_t-1\)</span>). We don’t see it explicitly in our R output, but it is needed to help understand the full model.</p></li>
</ul>
</section>
<section id="calculating-f" class="level3">
<h3 class="anchored" data-anchor-id="calculating-f">Calculating F</h3>
<ul>
<li>Finally, to calculate the F-test statistic, we take the MSTR (explained variability) and divide by the MSE (unexplained variability) considering the appropriate degrees of freedom (<span class="math inline">\(k-1\)</span> and <span class="math inline">\(n_t-k\)</span>).</li>
<li>A p-value is computed from that statistic mathematically by using the correct command in R.
<ul>
<li><span class="math inline">\(F_{k-1,n_t-k} = MSTR/MSE\)</span></li>
</ul></li>
</ul>
</section>
</section>
<section id="subsetting-data-for-anova" class="level2">
<h2 class="anchored" data-anchor-id="subsetting-data-for-anova">Subsetting Data for ANOVA</h2>
<ul>
<li><p>When running an ANOVA on a subset of your data (e.g., only certain regions or categories), it is important to use <code>droplevels()</code> after subsetting to remove any unused factor levels. If you do not, the ANOVA output — and post-hoc tests like TukeyHSD — may attempt to test groups that no longer have any observations, which causes errors or misleading results.</p></li>
<li><p>You can use <code>droplevels()</code> directly on the subsetted data frame, or use it inside a <code>mutate()</code> call on a specific column. For example:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After filtering to a subset of groups:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, Region <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"West"</span>, <span class="st">"East"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Region =</span> <span class="fu">droplevels</span>(Region))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>This was introduced in Module 2 in the context of cleaning factor variables, and the same logic applies here before running an ANOVA on a subsetted dataset.</li>
</ul>
</section>
<section id="example-of-a-one-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="example-of-a-one-way-anova">Example of a One-Way ANOVA</h2>
<ul>
<li>Like the t-test, a one-way ANOVA follows 3 steps, and then includes an optional 4th step after significance is found and confirmed in step 3.</li>
</ul>
<section id="step-1-set-up-null-and-alternative-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="step-1-set-up-null-and-alternative-hypothesis">Step 1: Set Up Null and Alternative Hypothesis</h3>
<ul>
<li>The competing hypotheses for the one-way ANOVA:
<ul>
<li><span class="math inline">\(H_0: \mu_{Atlanta} = \mu_{Houston}= \mu_{LosAngeles} = \mu_{SanFran} = \mu_{DC}\)</span></li>
<li><span class="math inline">\(H_A:\)</span> Not all population means of congestion levels are equal among the cities</li>
</ul></li>
</ul>
</section>
<section id="step-2-compute-the-f-test-statistic-and-p-value" class="level3">
<h3 class="anchored" data-anchor-id="step-2-compute-the-f-test-statistic-and-p-value">Step 2: Compute the F-test Statistic and p-Value</h3>
<ul>
<li><p>First, we read in the data set and give a look at what is included.</p>
<ul>
<li>Because we are using read.csv() command, we can set stringsAsFactors argument to TRUE so that the categorical variable will be coded appropriately upon download.</li>
<li>The summary() command suggests that there is one categorical variable, “City” and one continuous variable, “CongestionRating.”</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>congestionData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/congestion.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(congestionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             City    CongestionRating
 Atlanta       :25   Min.   :44.00   
 Houston       :25   1st Qu.:56.00   
 Los Angeles   :25   Median :59.00   
 San Francisco :25   Mean   :60.06   
 Washington, DC:25   3rd Qu.:64.00   
                     Max.   :77.00   </code></pre>
</div>
</div></li>
<li><p>The aov() function in R is used to fit an analysis of variance (ANOVA) model. The aov function allows you to specify a response variable and one or more explanatory variables (factors), producing a linear model to compare group means. The aov() function assumes that the variances of the groups are equal (homoscedasticity). Therefore, this function is suitable when the assumption of equal variances is met.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A common set of commands that work for both a one-way and two-way</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA: aov() command with output in a followup command: either</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># anova() or summary() command.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>Anova1way <span class="ot">&lt;-</span> <span class="fu">aov</span>(CongestionRating <span class="sc">~</span> City, <span class="at">data =</span> congestionData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>In either command, our formula is ContinuousVariable ~ CategoricalVariable - this will allow us to see if there are group differences in CongestionRating (continuous) based on city (categorical).</p>
<ul>
<li>Take a good look at the output from these commands to compare the results.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># anova() command works exactly the same as summary here.  This</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># command is very prevalent in various textbooks and online</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># tutorials.</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Anova1way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
City          4   3251   812.7   37.25 &lt;2e-16 ***
Residuals   120   2618    21.8                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(Anova1way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: CongestionRating
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
City        4 3250.7  812.67  37.251 &lt; 2.2e-16 ***
Residuals 120 2617.9   21.82                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Using the anova() or summary() commands, we can see the results from the ANOVA table, including the degrees of freedom (Df), sum of squares (Sum Sq), mean square (Mean Sq), F-test statistic (F value) and p-value (Pr(&gt;F)). It also includes asterisks (*) symbols if there are group differences due to our categorical variable. The more asterisks you see, the smaller the significant code. There is a table for these codes within the output marked <em>Signif. codes</em>.</li>
<li>Reading the codes:
<ul>
<li>If there are three asterisks, you would say that that your p-value is less than .001. If there are 2, your p-value is less than .01. 1 asterisk indicates a p-value &lt; .05.</li>
<li>We never say our p-value is 0, but instead say it is less than ___.</li>
<li>We <em>do not</em> use .1 as a significance level, although some statisticians mark a p-value less than .1 as “marginally significant”. There is a big debate about this, but I agree with the general consensus, so our threshold for this class is less than .05. Anything greater than or equal to .05 is not significant.</li>
</ul></li>
</ul>
</section>
<section id="step-3-interpret-the-probability-and-write-a-conclusion." class="level3">
<h3 class="anchored" data-anchor-id="step-3-interpret-the-probability-and-write-a-conclusion.">Step 3: Interpret the Probability and Write a conclusion.</h3>
<ul>
<li>The F-test statistic is 37.251 and the p-value is &lt; 2.2e-16 ***. This p-value is &lt; all typical alpha values like .05 or .001. This value is very close to 0. We would state that our p-value is less than .001 by looking at the table and noting the three asterisks.<br>
</li>
<li>The p-value result suggests that we support the alternative <span class="math inline">\(H_A\)</span>: Not all population means are equal.</li>
<li>More specifically we reject the null hypothesis <span class="math inline">\(H_0\)</span> in support of <span class="math inline">\(H_A\)</span> and conclude that not all congestion levels are equal among the cities.</li>
</ul>
</section>
<section id="step-4-if-model-is-significant-run-post-hoc-tests" class="level3">
<h3 class="anchored" data-anchor-id="step-4-if-model-is-significant-run-post-hoc-tests">Step 4: If Model is Significant, Run Post-Hoc Tests</h3>
<ul>
<li><p>Pairwise comparisons: A statistical strategy for comparing different groups, often used after a statistically significant ANOVA to test hypotheses about which group means are statistically significantly different from one another.</p>
<ol type="1">
<li>Bonferroni Method;</li>
<li>TukeyHSD Method</li>
</ol></li>
<li><p>There are many tests to compute pairwise comparisons. The tests tend to vary in whether they minimize Type I or Type II error, and by how much. Many of the tests change the distribution in the calculation to alter the final results.</p></li>
<li><p>Planned Comparisons: also known as a priori comparisons or planned comparisons, are a statistical technique used in the analysis of variance (ANOVA) to compare specific means based on hypotheses formulated before examining the data. Unlike post hoc tests, which compare all possible pairs of means and are conducted after data collection, planned contrasts are designed to test specific hypotheses derived from theoretical considerations or previous research.</p></li>
</ul>
</section>
<section id="bonferroni-method" class="level3">
<h3 class="anchored" data-anchor-id="bonferroni-method">Bonferroni Method</h3>
<ul>
<li>The Bonferroni method is a pairwise post-hoc test that is used after finding a statistically significant ANOVA. This method conducts a t-test for each pair of means and adjusts the threshold for statistical significance to ensure that there is a small enough risk of Type I error; it is generally considered a very conservative post hoc test that only identifies the largest differences between means as statistically significant.</li>
<li>The function has several arguments, such as <span class="math inline">\(x =\)</span> for the continuous variable (listed first); <span class="math inline">\(g =\)</span> for the grouping or categorical variable (listed 2nd); and the p-value adjustment, <span class="math inline">\(p.adj =\)</span>, which can be set as __bonf_ for Bonferroni (listed 3rd).</li>
<li>The output is a matrix of p-values, testing each pair for group differences. A value &lt; alpha signifies significant group differences.
<ul>
<li>Based on the output, there are no differences in congestion levels between Houston and Atlanta, San Francisco and Atlanta, and Houston and San Francisco.</li>
<li>There are group differences in congestion levels between all other remaining groups (p-value &lt; alpha).</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(congestionData<span class="sc">$</span>CongestionRating, congestionData<span class="sc">$</span>City, <span class="at">p.adj =</span> <span class="st">"bonf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  congestionData$CongestionRating and congestionData$City 

               Atlanta Houston Los Angeles San Francisco
Houston        1.00000 -       -           -            
Los Angeles    9.7e-15 1.3e-15 -           -            
San Francisco  1.00000 1.00000 &lt; 2e-16     -            
Washington, DC 0.00269 0.00071 2.1e-06     3.8e-05      

P value adjustment method: bonferroni </code></pre>
</div>
</div>
</section>
<section id="tukey-hsd-method" class="level3">
<h3 class="anchored" data-anchor-id="tukey-hsd-method">Tukey HSD Method</h3>
<ul>
<li>The Tukey HSD method is another pairwise post-hoc test that is used after finding a statistically significant ANOVA.</li>
<li>This method is used to determine which means are statistically significantly different from each other by comparing each pair of means.</li>
<li>This method is less conservative than the Bonferroni post hoc test, which means generally less Type II error (False Negative).</li>
<li>This test is modified from the Bonferroni test using a q-distribution instead of a t-distribution to calculate the answers.</li>
<li>Using the TukeyHSD() command, we insert the Anova1way object as a parameter that we made with the aov() command above. This aov() command is required before or while running the TukeyHSD() command.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(Anova1way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = CongestionRating ~ City, data = congestionData)

$City
                               diff        lwr        upr     p adj
Houston-Atlanta               -0.48  -4.139015   3.179015 0.9962320
Los Angeles-Atlanta           12.24   8.580985  15.899015 0.0000000
San Francisco-Atlanta         -1.44  -5.099015   2.219015 0.8113836
Washington, DC-Atlanta         4.96   1.300985   8.619015 0.0024588
Los Angeles-Houston           12.72   9.060985  16.379015 0.0000000
San Francisco-Houston         -0.96  -4.619015   2.699015 0.9499289
Washington, DC-Houston         5.44   1.780985   9.099015 0.0006646
San Francisco-Los Angeles    -13.68 -17.339015 -10.020985 0.0000000
Washington, DC-Los Angeles    -7.28 -10.939015  -3.620985 0.0000021
Washington, DC-San Francisco   6.40   2.740985  10.059015 0.0000373</code></pre>
</div>
</div>
<ul>
<li><p>Based on the output, we find similar results to the Bonferroni test. There are no differences in congestion levels between Houston and Atlanta, San Francisco and Atlanta, and Houston and San Francisco. There are group differences in congestion levels between all other remaining groups (p-value &lt; alpha).</p></li>
<li><p>With the TukeyHSD() command, we can also determine which group mean is higher than the other by looking at the “diff” score. If you see a negative score than the second group listed in the output is higher than the first group listed. Ignoring the insignificant p-values &gt; .05, we find that both San Francisco and Washington has significantly less congestion than Los Angeles. We find that Los Angeles and Washington have a significantly higher group mean than Atlanta. Los Angeles and Washington DC also have a significantly higher group mean than Houston. Finally, Washington DC has a significantly higher group mean than San Francisco.</p></li>
</ul>
</section>
</section>
</section>
<section id="two-way-anova" class="level1">
<h1>Two-Way ANOVA</h1>
<ul>
<li>A two-way ANOVA is called a randomized block design.</li>
<li>The term “block” refers to a matched set of observations across the treatments.</li>
<li>In a two-way ANOVA, there are now three sources of variation:
<ul>
<li>Row variability (due to blocks or Factor B or a first grouping variable),</li>
<li>Column variability (due to treatments or Factor A or a second grouping variable), and,</li>
<li>Variability due to chance or SSE.</li>
</ul></li>
<li>In altering the methodology above, the row and column variability take place of the <em>between-treatment estimate</em> listed above, which still corresponds to <em>explained variance</em>. We still have one <em>within-treatment estimate</em> as before, or a measure of <em>unexplained variance</em>.</li>
</ul>
<section id="steps-for-conducting-a-two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="steps-for-conducting-a-two-way-anova">Steps for Conducting a Two-Way ANOVA</h2>
<ol type="1">
<li>Write the null and alternate hypotheses for each grouping variable.</li>
<li>Compute the F-test statistics for each grouping variable and the probability for the test statistics (2 p-values for a 2-way ANOVA).</li>
<li>Interpret the probabilities and write a conclusion.</li>
<li>If model is significant, run post-hoc tests.</li>
</ol>
<ul>
<li>The steps are the same as a one-way ANOVA listed above, with the exception that now we have 2 grouping variables, so we need 2 F-stats and 2 p-values.</li>
</ul>
</section>
<section id="statistics-in-a-two-way-anova-table" class="level2">
<h2 class="anchored" data-anchor-id="statistics-in-a-two-way-anova-table">Statistics in a Two-Way ANOVA Table</h2>
<ul>
<li>We add another row to our ANOVA table when we move from a one-way ANOVA to a two-way ANOVA. The goal is the same, which is to produce a F-test statistic. In a two-way ANOVA, we will have two F-test statistics (one for each grouping variable). Each F-test statistic corresponds to a separate p-value that we can interpret the same way as we did in the last lessons (p-value &lt; alpha = significant result - reject the <span class="math inline">\(H_0\)</span>). So we can find one group significant and not the other, neither significant, or both significant with one test.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch7/2WayANOVA.PNG" title="Formulas for Two Way ANOVA" class="img-fluid figure-img"></p>
<figcaption>Two Way ANOVA Formulas</figcaption>
</figure>
</div>
<section id="explained-variance-1" class="level3">
<h3 class="anchored" data-anchor-id="explained-variance-1">Explained Variance</h3>
<ul>
<li><p>In a two-way ANOVA, we still start by computing the <em>explained variance</em>. Since we have an additional grouping variable, or factor, we will have two sum of squares measures, a sum of squares for factor A (SSA) and a sum of squares for factor B (SSB). Factor B is typically called a row (r) factor, while Factor A is typically called a column (c) factor. However, the order of the output will depend on the order of your formula in R.</p></li>
<li><p>The explained variance still suggests that the variation in outcome can be explained by a model, but now it will be due to the two grouping variables. In computing the SSB, we take the number of columns (<span class="math inline">\(c\)</span>) and we multiply by the sum of the squared deviation between each group B mean (<span class="math inline">\(\bar{y_j}\)</span>) and the grand mean <span class="math inline">\(\bar{y}\)</span>.</p>
<ul>
<li><span class="math inline">\(SSB = c*\sum^r_{j=1}{(\bar{y_j}-\bar{y}) ^2}\)</span></li>
</ul></li>
<li><p>In computing SSA, we take the number of rows and we multiply that number by the sum of the squared deviation between each group A mean and the grand mean</p>
<ul>
<li><span class="math inline">\(SSA =r*\sum^c_{i=1}{(\bar{y_i}-\bar{y}) ^2}\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSB are computed by the number of rows - 1 <span class="math inline">\((r-1)\)</span>, and the degrees of freedom for SSA are computed as the number of columns - 1 <span class="math inline">\((c-1)\)</span>.</p>
<ul>
<li><span class="math inline">\(df_{ssb} = r-1\)</span></li>
<li><span class="math inline">\(df_{ssa} = c-1\)</span></li>
</ul></li>
<li><p>The mean square due to Factor B (MSB) and Factor A (MSA) both take the value from the appropriate sum of squares (SSB and SSA) and divides that factors degrees of freedom <span class="math inline">\((r-1)\)</span> or <span class="math inline">\((c-1)\)</span>.</p>
<ul>
<li><span class="math inline">\(MSB = SSB/(r-1)\)</span></li>
<li><span class="math inline">\(MSA = SSA/(c-1)\)</span></li>
</ul></li>
</ul>
</section>
<section id="unexplained-variance-1" class="level3">
<h3 class="anchored" data-anchor-id="unexplained-variance-1">Unexplained Variance</h3>
<ul>
<li><p>In a two-way ANOVA, there is still only one measure of <em>unexplained variance</em>, which we term residual error.</p></li>
<li><p>The SSE is calculated after deriving the total variance (SST = both explained and unexplained), and subtracting the explained variance (SSB and SSA).</p>
<ul>
<li><span class="math inline">\(SSE = SST - (SSA + SSB)\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSE are computed by taking the total number of observations (<span class="math inline">\(n_t\)</span>) and subtracting the number of rows (r) and the number of columns (c) and adding 1 <span class="math inline">\((n_t-c-r+1)\)</span>.</p>
<ul>
<li><span class="math inline">\(df_{sse} = n_t-c-r+1\)</span></li>
</ul></li>
<li><p>The mean square due to error (MSE) takes the SSE and divides by the appropriate degrees of freedom <span class="math inline">\((n_t-c-r+1)\)</span>.</p>
<ul>
<li><span class="math inline">\(MSE = SSE/(n_t-c-r+1)\)</span></li>
</ul></li>
<li><p>There is a total sum of squares (SST) being calculated mentioned above, which again refers to the total variance (explained and unexplained). To get this calculation, we take the squared deviation between each observation and the grand mean and we sum up all of our values.</p></li>
<li><p>There is also a total degrees of freedom in a two-way ANOVA, which is the total number of observations minus 1 (<span class="math inline">\(n_t-1\)</span>). We don’t see it explicitly in our R output, but it is needed to help understand the full model.</p></li>
</ul>
</section>
<section id="calculating-f-test-statistics" class="level3">
<h3 class="anchored" data-anchor-id="calculating-f-test-statistics">Calculating F-test Statistics</h3>
<ul>
<li>Finally, to calculate the 2 F-test statistics, given a two-way ANOVA, we take both the MSB (explained variability for factor B) and the MSA (explained variability for factor A) and divide both by the MSE (unexplained variability) considering the appropriate degrees of freedom (<span class="math inline">\(c-1\)</span> and <span class="math inline">\(r-1\)</span> and <span class="math inline">\(n_t-c-r+1\)</span>).</li>
<li>This gives us two scores to evaluate. A p-value is computed from each F-test statistic mathematically by using the correct command in R.
<ul>
<li><span class="math inline">\(F1_{c-1,n_t-c-r+1 }= MSB/MSE\)</span></li>
<li><span class="math inline">\(F2_{r-1,n_t-c-r+1 }= MSA/MSE\)</span></li>
</ul></li>
</ul>
</section>
</section>
<section id="using-factor-inline-in-anova-formulas" class="level2">
<h2 class="anchored" data-anchor-id="using-factor-inline-in-anova-formulas">Using factor() Inline in ANOVA Formulas</h2>
<ul>
<li>In a two-way ANOVA, you can convert a variable to a factor directly inside the <code>aov()</code> formula using <code>factor()</code>. For example, if <code>year</code> is stored as a numeric variable but you want to treat it as a categorical grouping variable, you can write:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(Outcome <span class="sc">~</span> GroupA <span class="sc">*</span> <span class="fu">factor</span>(year), <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>This is equivalent to converting <code>year</code> to a factor first using <code>as.factor()</code> and then passing it to <code>aov()</code>. The inline approach is convenient when you want to test a numeric variable as a categorical factor without permanently changing the variable in your dataset.</li>
</ul>
</section>
<section id="example-of-a-two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="example-of-a-two-way-anova">Example of a Two-way ANOVA</h2>
<ul>
<li>Let’s run an example to compare SAT scores to see if they are comparable from different instructors {Instructor 1, 2, and 3} and across 4 races {Asian.American, Black, Mexican.American, and White}.</li>
</ul>
<section id="step-1-set-up-null-and-alternative-hypothesis-1" class="level3">
<h3 class="anchored" data-anchor-id="step-1-set-up-null-and-alternative-hypothesis-1">Step 1: Set Up Null and Alternative Hypothesis</h3>
<ul>
<li><p>The competing hypotheses for the two-way ANOVA are two-fold:</p></li>
<li><p>Hypothesis 1:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_{Instructor1} = \mu_{Instructor2}= \mu_{Instructor3}\)</span></li>
<li><span class="math inline">\(H_A:\)</span> Not all population means of SAT scores are equal among the instructors</li>
</ul></li>
<li><p>Hypothesis 2:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_{Asian.American} = \mu_{Black} = \mu_{Mexical.American} =  \mu_{White}\)</span></li>
<li><span class="math inline">\(H_A:\)</span> Not all population means of SAT scores are equal among races</li>
</ul></li>
</ul>
</section>
<section id="step-2-compute-the-f-test-statistics-and-p-values" class="level3">
<h3 class="anchored" data-anchor-id="step-2-compute-the-f-test-statistics-and-p-values">Step 2: Compute the F-test Statistics and p-Values</h3>
<ul>
<li><p>Like a one-way ANOVA, in a two-way ANOVA, we start with an appropriate data set.</p>
<ul>
<li>Again, because we are using read.csv() command, we can set stringsAsFactors argument to TRUE so that the categorical variable will be coded appropriately upon download.</li>
<li>The summary() command suggests that there are two categorical variables, “Instructor” and “Race”, and one continuous variable, “SAT.”</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>SATdata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/SAT.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(SATdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Instructor               Race         SAT      
 Instructor A:40   Asian.American  :30   Min.   :1190  
 Instructor B:40   Black           :30   1st Qu.:1328  
 Instructor C:40   Mexican.American:30   Median :1492  
                   White           :30   Mean   :1468  
                                         3rd Qu.:1592  
                                         Max.   :1772  </code></pre>
</div>
</div></li>
</ul>
</section>
<section id="step-3-interpret-the-probabilities-and-write-a-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="step-3-interpret-the-probabilities-and-write-a-conclusion">Step 3: Interpret the Probabilities and Write a Conclusion</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Anova2way <span class="ot">&lt;-</span> <span class="fu">aov</span>(SAT <span class="sc">~</span> Instructor <span class="sc">+</span> Race, <span class="at">data =</span> SATdata)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Anova2way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df  Sum Sq Mean Sq F value Pr(&gt;F)    
Instructor    2    5932    2966   1.084  0.342    
Race          3 2353300  784433 286.624 &lt;2e-16 ***
Residuals   114  311995    2737                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p>In the ANOVA results, we find that there was no difference in SAT score based on the Instructor of record. Specifically, we find a F-test statistic of 1.084 and an associated p-value at .342. That p-value is &gt; alpha (.05), and therefore, we fail to reject the null hypothesis <span class="math inline">\((H_0:  \mu_{Instructor1} = \mu_{Instructor2}= \mu_{Instructor3})\)</span>.</p></li>
<li><p>We also find that Race is significant, with a F-test statistic of 286.624 and an associated p-value of &lt;2e-16 ***. This means that we can reject the null hypothesis and support the alternative hypothesis (<span class="math inline">\(H_A:\)</span> Not all population means of SAT scores are equal among races).</p></li>
<li><p>This means that we can conduct post-hoc tests on our Race variable. If we conduct any post-hoc tests on Instructor, we should find no differences in groups (which we already found in the ANOVA results above). This means additional testing the Instructor variable is an unnecessary step.</p></li>
</ul>
</section>
<section id="step-4-if-model-is-significant-run-post-hoc-tests-1" class="level3">
<h3 class="anchored" data-anchor-id="step-4-if-model-is-significant-run-post-hoc-tests-1">Step 4: If Model is Significant, Run Post-Hoc Tests</h3>
<ul>
<li>Using the pairwise.t.test() command, we can run a Bonferroni test on just race by using the command below. This result suggest that there are group differences between all groups. We can tell that because all p-values are less than alpha at .05.<br>
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(SATdata<span class="sc">$</span>SAT, SATdata<span class="sc">$</span>Race, <span class="at">p.adj =</span> <span class="st">"bonf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  SATdata$SAT and SATdata$Race 

                 Asian.American Black   Mexican.American
Black            &lt; 2e-16        -       -               
Mexican.American &lt; 2e-16        4.9e-09 -               
White            0.0044         &lt; 2e-16 &lt; 2e-16         

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<ul>
<li>Using the TukeyHSD() Method, we do receive output for both Race and Instructor. As expected, all p-values under the instructor grouping are well above an alpha of .05, meaning not significant (Fail to reject <span class="math inline">\(H_0\)</span>).</li>
<li>Receiving similar results to the Bonferroni test with regards to Race, we find all group differences significant. Specifically, Black Americans, Mexican Americans, and White Americans scored lower on their SAT than Asian Americans. Mexican Americans and White Americans scored higher on their SAT than Black Americans. White Americans scored higher than Mexican Americans. Using this command, we can tell which group scored lower than the other by looking at the difference score “diff”.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(Anova2way)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = SAT ~ Instructor + Race, data = SATdata)

$Instructor
                             diff       lwr      upr     p adj
Instructor B-Instructor A  -0.275 -28.05409 27.50409 0.9996954
Instructor C-Instructor A -15.050 -42.82909 12.72909 0.4056475
Instructor C-Instructor B -14.775 -42.55409 13.00409 0.4189723

$Race
                                      diff        lwr        upr     p adj
Black-Asian.American            -339.33333 -374.55195 -304.11472 0.0000000
Mexican.American-Asian.American -248.86667 -284.08528 -213.64805 0.0000000
White-Asian.American             -46.90000  -82.11862  -11.68138 0.0040188
Mexican.American-Black            90.46667   55.24805  125.68528 0.0000000
White-Black                      292.43333  257.21472  327.65195 0.0000000
White-Mexican.American           201.96667  166.74805  237.18528 0.0000000</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="two-way-anova-with-interaction" class="level1">
<h1>Two-Way ANOVA with Interaction</h1>
<ul>
<li>A two-way ANOVA with interaction is a statistical test used to examine the effects of two independent categorical variables (factors) on a continuous dependent variable, while also assessing whether the effects of one factor depend on the levels of the other. This test includes three key components: main effects of each factor (how each variable influences the dependent variable independently) and the interaction effect (whether the effect of one factor changes depending on the level of the other factor). If a significant interaction is found, it suggests that the impact of one factor differs across levels of the second factor, meaning the combined influence of both factors is not simply additive. This interaction is visualized using interaction plots, where non-parallel lines indicate interaction. A two-way ANOVA with interaction assumes the same assumptions as a two-way ANOVA: normality, homogeneity of variances, and independence of observations.</li>
</ul>
<section id="statistics-in-a-two-way-with-interaction-anova" class="level2">
<h2 class="anchored" data-anchor-id="statistics-in-a-two-way-with-interaction-anova">Statistics in a Two-Way with Interaction ANOVA</h2>
<ul>
<li><p>When performing a two-way ANOVA with interaction, we introduce an additional row to the ANOVA table to account for the interaction effect between the two grouping variables. The goal remains to compute F-test statistics, but now we have three F-statistics: one for each main effect and one for the interaction effect. Each F-statistic corresponds to a p-value, which we interpret as before (p-value &lt; alpha means a significant result, leading to rejection of <span class="math inline">\(H_o\)</span>).</p></li>
<li><p>Depending on the results, we may find that only one main effect is significant, both are significant, neither is significant, or the interaction itself is significant.</p></li>
<li><p>In a two-way ANOVA with interaction, we compute the explained variance by adding a new term for the interaction sum of squares (SSAB). This measures the variance explained by the interaction of factors A and B.</p></li>
</ul>
</section>
<section id="steps-for-conducting-a-two-way-anova-with-interaction" class="level2">
<h2 class="anchored" data-anchor-id="steps-for-conducting-a-two-way-anova-with-interaction">Steps for Conducting a Two-Way ANOVA with Interaction</h2>
<ol type="1">
<li>Write the null and alternate hypotheses for each grouping variable and the interaction effect.</li>
<li>Compute the F-test statistics for each grouping variable and the probability for the test statistics (3 p-values for a 2-way ANOVA).</li>
<li>Interpret the probabilities and write a conclusion.</li>
<li>If model is significant, run post-hoc tests.</li>
</ol>
<section id="explained-variance-2" class="level3">
<h3 class="anchored" data-anchor-id="explained-variance-2">Explained Variance</h3>
<ul>
<li><p>In a two-way ANOVA with interaction, we compute the explained variance by adding a new term for the . This measures the variance explained by the interaction of factors A and B.</p></li>
<li><p>The sum of squares for and are computed similarly to before:</p>
<ul>
<li><span class="math inline">\(SSB = c \sum^r_{j=1}{(\bar{y_j}-\bar{y}) ^2}\)</span></li>
<li><span class="math inline">\(SSA = r \sum^c_{i=1}{(\bar{y_i}-\bar{y}) ^2}\)</span></li>
</ul></li>
<li><p>The sum of squares for the measures how much variability is explained by the combination of the two factors, beyond their individual effects:</p>
<ul>
<li><span class="math inline">\(SSAB = \sum^c_{i=1} \sum^r_{j=1} n_{ij} (\bar{y_{ij}} - \bar{y_i} - \bar{y_j} + \bar{y})^2\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSB are computed by the number of rows - 1 <span class="math inline">\((r-1)\)</span>, and the degrees of freedom for SSA are computed as the number of columns - 1 <span class="math inline">\((c-1)\)</span>.</p>
<ul>
<li><span class="math inline">\(df_{ssb} = r-1\)</span></li>
<li><span class="math inline">\(df_{ssa} = c-1\)</span></li>
<li><span class="math inline">\(df_{ssab} = (c-1)(r-1)\)</span></li>
</ul></li>
<li><p>The for each term is calculated by dividing the sum of squares by its respective degrees of freedom:.</p>
<ul>
<li><span class="math inline">\(MSB = SSB/(r-1)\)</span></li>
<li><span class="math inline">\(MSA = SSA/(c-1)\)</span></li>
<li><span class="math inline">\(MSAB = \frac{SSAB}{(c-1)(r-1)}\)</span></li>
</ul></li>
</ul>
</section>
<section id="unexplained-variance-2" class="level3">
<h3 class="anchored" data-anchor-id="unexplained-variance-2">Unexplained Variance</h3>
<ul>
<li><p>The residual variance (unexplained variance) is computed as before, but now it accounts for the additional interaction term:</p>
<ul>
<li><span class="math inline">\(SSE = SST - (SSA + SSB + SSAB)\)</span></li>
</ul></li>
<li><p>Degrees of freedom for the SSE are updated as well to account for the interaction term.</p>
<ul>
<li><span class="math inline">\(df_{sse} = n_t - c - r + 1 - (c-1)(r-1)\)</span></li>
</ul></li>
<li><p>The mean square due to error (MSE) also considers an update.</p>
<ul>
<li><span class="math inline">\(MSE = \frac{SSE}{n_t - c - r + 1 - (c-1)(r-1)}\)</span></li>
</ul></li>
<li><p>There is a total sum of squares (SST) being calculated mentioned above, which again refers to the total variance (explained and unexplained). To get this calculation, we take the squared deviation between each observation and the grand mean and we sum up all of our values.</p></li>
</ul>
</section>
<section id="calculating-f-test-statistics-1" class="level3">
<h3 class="anchored" data-anchor-id="calculating-f-test-statistics-1">Calculating F-test Statistics</h3>
<ul>
<li><p>To determine the significance of each effect, we compute F-test statistics:</p>
<ul>
<li><span class="math inline">\(F_1 = \frac{MSB}{MSE} \quad \text{(for factor B)}\)</span></li>
<li><span class="math inline">\(F_2 = \frac{MSA}{MSE} \quad \text{(for factor A)}\)</span><br>
</li>
<li><span class="math inline">\(F_3 = \frac{MSAB}{MSE} \quad \text{(for interaction effect)}\)</span></li>
</ul></li>
<li><p>Each F-statistic follows an ( F )-distribution with its respective degrees of freedom:</p>
<ul>
<li><span class="math inline">\(F1_{c-1,n_t-c-r+1-(c-1)(r-1)} = \frac{MSA}{MSE}\)</span></li>
<li><span class="math inline">\(F2_{r-1,n_t-c-r+1-(c-1)(r-1)} = \frac{MSB}{MSE}\)</span></li>
<li><span class="math inline">\(F3_{(c-1)(r-1),n_t-c-r+1-(c-1)(r-1)} = \frac{MSAB}{MSE}\)</span></li>
</ul></li>
<li><p>Each F-statistic is associated with a p-value, which determines significance.</p>
<ul>
<li>If the interaction effect is significant, it suggests that the effect of one factor depends on the levels of the other factor.<br>
</li>
<li>If the interaction is , we interpret the main effects independently.<br>
</li>
<li>If the interaction is significant, (e.g., pairwise comparisons) or are needed to examine differences at different levels of the factors.<br>
</li>
<li>Visualization using helps in understanding the nature of the interaction.</li>
</ul></li>
</ul>
</section>
</section>
<section id="example-of-a-two-way-anova-with-interaction" class="level2">
<h2 class="anchored" data-anchor-id="example-of-a-two-way-anova-with-interaction">Example of a Two-way ANOVA with Interaction</h2>
<ul>
<li>Let’s use the corolla car dataset to make an example of a 2 way interaction.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>corolla <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/corolla.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="step-1-write-the-null-and-alternate-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="step-1-write-the-null-and-alternate-hypotheses">Step 1: Write the null and alternate hypotheses</h3>
<ul>
<li>For Factor B:
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_o\)</span>): Factor B has no effect on the dependent variable.</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_a\)</span>): Factor B has a significant effect on the dependent variable.</li>
</ul></li>
<li>For Factor A:
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_o\)</span>): Factor A has no effect on the dependent variable.</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_a\)</span>): Factor A has a significant effect on the dependent variable.</li>
</ul></li>
<li>For Interaction:
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_o\)</span>): There is no interaction between the two factors (i.e., the effect of one factor does not depend on the level of the other factor).</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_a\)</span>): There is an interaction between the two factors (i.e., the effect of one factor depends on the level of the other factor).</li>
</ul></li>
<li>In the dataset, let’s make a hypothesis between Fuel_Type and Metallic paint on Price. We would make two individual hypotheses and one interaction hypothesis between Fuel_Type and Metallic.</li>
</ul>
</section>
<section id="step-2-compute-the-f-test-statistic-for-the-interaction-and-its-p-value." class="level3">
<h3 class="anchored" data-anchor-id="step-2-compute-the-f-test-statistic-for-the-interaction-and-its-p-value.">Step 2: Compute the F-test statistic for the interaction and its p-value.</h3>
<ul>
<li>Use an ANOVA table to obtain the F-statistic for the interaction term.</li>
<li>Compute the associated p-value to determine the significance of the interaction effect.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ANOVAInteraction <span class="ot">&lt;-</span> <span class="fu">aov</span>(Price <span class="sc">~</span> Fuel_Type <span class="sc">*</span> Metallic, <span class="at">data =</span> corolla)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ANOVAInteraction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Price
                     Df     Sum Sq   Mean Sq F value    Pr(&gt;F)    
Fuel_Type             2 8.1770e+07  40885042  3.1689   0.04235 *  
Metallic              1 2.2999e+08 229991578 17.8261 2.573e-05 ***
Fuel_Type:Metallic    2 1.1566e+08  57828498  4.4821   0.01147 *  
Residuals          1430 1.8450e+10  12901974                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="step-3-interpret-the-probability-and-write-a-conclusion.-1" class="level3">
<h3 class="anchored" data-anchor-id="step-3-interpret-the-probability-and-write-a-conclusion.-1">Step 3: Interpret the probability and write a conclusion.</h3>
<ul>
<li><p>If the p-value for an effect is small (typically &lt; 0.05), reject the null hypothesis and conclude that the effect is significant.</p></li>
<li><p>If the interaction effect is significant, this means the relationship between Factor A and the dependent variable depends on the level of Factor B (or vice versa). This interaction may change how the main effects should be interpreted.</p></li>
<li><p>If the interaction is not significant, the main effects can be interpreted independently.</p></li>
<li><p>Fuel Type has a significant main effect on Price (p-value &lt; .05).</p></li>
<li><p>Metallic has a significant main effect on Price (p-value &lt; .001).</p></li>
<li><p>There is a significant interaction between Fuel_Type and Metallic on Price (p-value &lt; .05).</p></li>
</ul>
</section>
<section id="step-4-if-the-interaction-is-significant-examine-simple-effects-or-conduct-post-hoc-tests." class="level3">
<h3 class="anchored" data-anchor-id="step-4-if-the-interaction-is-significant-examine-simple-effects-or-conduct-post-hoc-tests.">Step 4: If the interaction is significant, examine simple effects or conduct post-hoc tests.</h3>
<ul>
<li>If the interaction effect is significant, examine simple effects or run post-hoc tests.
<ul>
<li>Conduct simple effects analysis, examining the effect of one factor at each level of the other factor.</li>
<li>Use post-hoc tests (e.g., Tukey’s HSD) to compare means within the interaction groups if needed.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(ANOVAInteraction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Price ~ Fuel_Type * Metallic, data = corolla)

$Fuel_Type
                   diff        lwr       upr     p adj
Diesel-CNG    1873.3784  -279.6881 4026.4448 0.1028212
Petrol-CNG    1258.1337  -799.4623 3315.7296 0.3233777
Petrol-Diesel -615.2447 -1332.4365  101.9471 0.1095064

$Metallic
           diff      lwr      upr    p adj
Yes-No 854.0585 457.1405 1250.977 2.59e-05

$`Fuel_Type:Metallic`
                            diff         lwr      upr     p adj
Diesel:No-CNG:No       1129.9717 -4184.83891 6444.782 0.9905762
Petrol:No-CNG:No       1772.6707 -3377.20255 6922.544 0.9236558
CNG:Yes-CNG:No         1234.0385 -4626.54810 7094.625 0.9909858
Diesel:Yes-CNG:No      3693.6765 -1530.78039 8918.133 0.3327455
Petrol:Yes-CNG:No      2407.8372 -2729.08521 7544.760 0.7640042
Petrol:No-Diesel:No     642.6990  -853.46403 2138.862 0.8242820
CNG:Yes-Diesel:No       104.0668 -3068.28000 3276.414 0.9999990
Diesel:Yes-Diesel:No   2563.7048   828.11883 4299.291 0.0003807
Petrol:Yes-Diesel:No   1277.8655  -173.09322 2728.824 0.1208642
CNG:Yes-Petrol:No      -538.6323 -3426.15143 2348.887 0.9948689
Diesel:Yes-Petrol:No   1921.0057   786.87985 3055.132 0.0000219
Petrol:Yes-Petrol:No    635.1665    19.32214 1251.011 0.0387028
Diesel:Yes-CNG:Yes     2459.6380  -558.89170 5478.168 0.1845234
Petrol:Yes-CNG:Yes     1173.7988 -1690.55881 4038.156 0.8514287
Petrol:Yes-Diesel:Yes -1285.8392 -2359.62643 -212.052 0.0085182</code></pre>
</div>
</div>
<ul>
<li><p>In the output, it looks like Fuel_Type is a weak variable. There were no group differences detected in the TukeyHSD. There is a group difference between Metallic paint (Yes vs No). There are many interaction groups significantly different as indicated by a significant p-value &lt; .05.</p>
<ul>
<li>Create interaction plots to visualize how the levels of one factor influence the effect of the other factor.</li>
</ul></li>
<li><p>Below is a ggplot confirming the relationship. In the chart, The x-axis represents Fuel Type and the y-axis represents Price. Different lines (or colors) represent whether the car has Metallic Paint (Yes/No). If the lines are not parallel, it suggests an interaction effect. The lines are not parallel below, so there is a confirmed interaction.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(corolla, <span class="fu">aes</span>(<span class="at">x =</span> Fuel_Type, <span class="at">y =</span> Price, <span class="at">color =</span> Metallic, <span class="at">group =</span> Metallic)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">linetype =</span> Metallic)) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Fuel Type and Metallic Paint on Price"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fuel Type"</span>, <span class="at">y =</span> <span class="st">"Price"</span>, <span class="at">color =</span> <span class="st">"Metallic Paint"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="choose-command" class="level1">
<h1>choose() command</h1>
<ul>
<li><p>The choose(n, k) function in R calculates the number of ways to choose k items from a set of n items without regard to order. It answers the question: “How many different groups of k can I make from n items?” For example, choose(5, 2) equals 10, meaning you can make 10 different pairs from a group of 5 items.</p></li>
<li><p>The Combination function counts the number of ways to choose objects from a total of objects. The order in which the objects are listed does not matter.</p></li>
<li><p>Since repetition is not allowed, we use <span class="math inline">\(C(n,x) = (n)!/((n-x!)*x!)\)</span></p></li>
<li><p>When performing Tukey’s Honest Significant Difference (TukeyHSD) test for post-hoc analysis, pairwise comparisons are made between all possible pairs of group means. The total number of comparisons depends on the number of groups and can be calculated using the choose function. The choose function conceptually relates to TukeyHSD because it tells you how many pairwise comparisons will be tested based on the number of groups.</p>
<ul>
<li>In post hoc tests, x is always 2.</li>
<li>If you have 4 groups (A, B, C, D), choose(4, 2) = 6, meaning 6 pairwise comparisons are made: A-B, A-C, A-D, B-C, B-D, and C-D.</li>
</ul></li>
<li><p>You can also calculate the factorial of a number using the factorial function in base R.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># C(4,2) = 4!/2!*(4-2)! manually</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>(<span class="dv">4</span> <span class="sc">*</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">1</span>)<span class="sc">/</span>((<span class="dv">2</span> <span class="sc">*</span> <span class="dv">1</span>) <span class="sc">*</span> (<span class="dv">2</span> <span class="sc">*</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with the factorial function</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">factorial</span>(<span class="dv">4</span>)<span class="sc">/</span>(<span class="fu">factorial</span>(<span class="dv">4</span> <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">factorial</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<ul>
<li>A quick check on how many pairs we can expect in our post-hoc output, we can use the choose() command. We always only check 2 groups at a time, so the 2nd argument should remain a 2.</li>
<li>If we have 4 races, we would use 4,2 inside the command as shown below. This means we should see 6 p-value statistics for 6 pairwise tests.<br>
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with choose function</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">choose</span>(<span class="dv">4</span>, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<ul>
<li>We had 3 instructors, so we would use 3,2 inside the command as shown below. If this variable was significant, we should see 3 p-value statistics for 3 pairwise tests.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">choose</span>(<span class="dv">3</span>, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
</section>
<section id="using-ai" class="level1">
<h1>Using AI</h1>
<ul>
<li><p>Use the following prompts on a generative AI, like chatGPT, to learn more about ANOVA analysis.</p></li>
<li><p>Explain how ANOVA is used to compare group means. What are the assumptions of ANOVA, and how do we interpret the F-statistic and p-value?</p></li>
<li><p>Walk me through the steps of conducting a one-way ANOVA. Explain how to use the aov() function in R and how to interpret the results, including the F-statistic and p-value.</p></li>
<li><p>Describe how to conduct a two-way ANOVA in R. What are the key differences between one-way and two-way ANOVA, and how do we interpret multiple F-statistics?</p></li>
<li><p>What are post-hoc tests, and why are they important after conducting an ANOVA? How do the TukeyHSD and Bonferroni methods differ in terms of reducing Type I and Type II errors?</p></li>
<li><p>Explain Type I and Type II errors in the context of hypothesis testing. How do these errors relate to the significance level (alpha) and the power of a test?</p></li>
<li><p>Given an R output from the aov() or anova() function, explain how to interpret the degrees of freedom, sum of squares, mean square, F-statistic, and p-value.</p></li>
<li><p>Provide a step-by-step guide to performing a one-way ANOVA in R using the aov() function. Include code examples and explain how to interpret the summary output.</p></li>
<li><p>Compare the TukeyHSD and Bonferroni post-hoc tests. Which one is more conservative, and how do they help in reducing error in multiple comparisons?</p></li>
</ul>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<ul>
<li>In this section, we learned about Type I and Type II error and the importance of reducing both. We also learned about a one-way ANOVA and a two-way ANOVA, including how to conduct them, and when to evaluate post-hoc tests.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ttests.html" class="pagination-link" aria-label="Hypothesis Testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./regression.html" class="pagination-link" aria-label="Regression">
        <span class="nav-page-text"><span class="chapter-title">Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>