<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Probability And Business Statistics - 7&nbsp; Contingency Tables and Chi-Squared</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ttests.html" rel="next">
<link href="./probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./contingency.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Contingency Tables and Chi-Squared</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Probability And Business Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Installing R and R Studio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataprep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./contingency.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Contingency Tables and Chi-Squared</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hypothesis Testing with t-Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Correlation Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Recommended Further Reading Materials</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance"><span class="header-section-number">7.0.1</span> At a Glance</a></li>
  <li><a href="#lesson-objectives" id="toc-lesson-objectives" class="nav-link" data-scroll-target="#lesson-objectives"><span class="header-section-number">7.0.2</span> Lesson Objectives</a></li>
  <li><a href="#consider-while-reading" id="toc-consider-while-reading" class="nav-link" data-scroll-target="#consider-while-reading"><span class="header-section-number">7.0.3</span> Consider While Reading</a></li>
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">7.1</span> Contingency Tables</a>
  <ul class="collapse">
  <li><a href="#probability-rules" id="toc-probability-rules" class="nav-link" data-scroll-target="#probability-rules"><span class="header-section-number">7.1.1</span> Probability Rules</a></li>
  <li><a href="#summary-measures-for-a-random-variable" id="toc-summary-measures-for-a-random-variable" class="nav-link" data-scroll-target="#summary-measures-for-a-random-variable"><span class="header-section-number">7.1.2</span> Summary Measures for a Random Variable</a></li>
  <li><a href="#calculating-probability" id="toc-calculating-probability" class="nav-link" data-scroll-target="#calculating-probability"><span class="header-section-number">7.1.3</span> Calculating Probability</a></li>
  <li><a href="#larger-contingency-table" id="toc-larger-contingency-table" class="nav-link" data-scroll-target="#larger-contingency-table"><span class="header-section-number">7.1.4</span> Larger Contingency Table</a></li>
  </ul></li>
  <li><a href="#chi-squared-test-for-independence" id="toc-chi-squared-test-for-independence" class="nav-link" data-scroll-target="#chi-squared-test-for-independence"><span class="header-section-number">7.2</span> Chi-Squared Test for Independence</a>
  <ul class="collapse">
  <li><a href="#steps-to-conduct-chi-squared-test-for-independence" id="toc-steps-to-conduct-chi-squared-test-for-independence" class="nav-link" data-scroll-target="#steps-to-conduct-chi-squared-test-for-independence"><span class="header-section-number">7.2.1</span> Steps to conduct Chi-Squared Test for Independence</a></li>
  <li><a href="#assumptions-of-the-chi-squared-test-of-independence" id="toc-assumptions-of-the-chi-squared-test-of-independence" class="nav-link" data-scroll-target="#assumptions-of-the-chi-squared-test-of-independence"><span class="header-section-number">7.2.2</span> Assumptions of the Chi-Squared Test of Independence</a></li>
  <li><a href="#example-of-a-test-for-independence" id="toc-example-of-a-test-for-independence" class="nav-link" data-scroll-target="#example-of-a-test-for-independence"><span class="header-section-number">7.2.3</span> Example of a Test for Independence</a></li>
  <li><a href="#example-using-an-imported-dataset" id="toc-example-using-an-imported-dataset" class="nav-link" data-scroll-target="#example-using-an-imported-dataset"><span class="header-section-number">7.2.4</span> Example Using an Imported Dataset</a></li>
  </ul></li>
  <li><a href="#chi-squared-goodness-of-fit-test" id="toc-chi-squared-goodness-of-fit-test" class="nav-link" data-scroll-target="#chi-squared-goodness-of-fit-test"><span class="header-section-number">7.3</span> Chi-Squared Goodness of Fit Test</a>
  <ul class="collapse">
  <li><a href="#example-using-raw-numbers" id="toc-example-using-raw-numbers" class="nav-link" data-scroll-target="#example-using-raw-numbers"><span class="header-section-number">7.3.1</span> Example Using Raw Numbers</a></li>
  <li><a href="#example-using-an-imported-dataset-1" id="toc-example-using-an-imported-dataset-1" class="nav-link" data-scroll-target="#example-using-an-imported-dataset-1"><span class="header-section-number">7.3.2</span> Example Using an Imported Dataset</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">7.4</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Contingency Tables and Chi-Squared</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<ul>
<li>The goal of this lesson is to teach you probability calculations via contingency tables. We will also conduct our first hypothesis tests, which is the chi-squared test for independence and the chi-squared test of goodness of fit.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">####################################</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Project name: Computing and Interpreting Chi-Square</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Data used: stem.csv, and stemGOF from Blackboard</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Libraries used: N/A</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="do">####################################</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="at-a-glance" class="level3" data-number="7.0.1">
<h3 data-number="7.0.1" class="anchored" data-anchor-id="at-a-glance"><span class="header-section-number">7.0.1</span> At a Glance</h3>
<ul>
<li>In order to succeed in this section, you will need to learn how to create and calculate probability inside a contingency table, when we have two categorical variables, and conduct our first hypothesis test, the chi-squared test of independence. In your homework assignment for this chapter, you will put these skills into practice.</li>
</ul>
</section>
<section id="lesson-objectives" class="level3" data-number="7.0.2">
<h3 data-number="7.0.2" class="anchored" data-anchor-id="lesson-objectives"><span class="header-section-number">7.0.2</span> Lesson Objectives</h3>
<ul>
<li>Compute probability regarding two categorical variables inside contingencies tables.</li>
<li>Calculate and interpret the chi-squared statistic for the test of independence.</li>
<li>Calculate and interpret the chi-squared statistic for the goodness of fit test.</li>
</ul>
</section>
<section id="consider-while-reading" class="level3" data-number="7.0.3">
<h3 data-number="7.0.3" class="anchored" data-anchor-id="consider-while-reading"><span class="header-section-number">7.0.3</span> Consider While Reading</h3>
<ul>
<li>In this lesson, we move from simply describing data to making inferences. We learn about contingency tables in regards to calculating probability and are able to calculate and interpret the Chi-squared statistic for the test of independence.</li>
<li>As you read and listen to the materials for this lesson, pay attention to the concepts, and pay attention to how those concepts are applied. There are rules for calculating and combining probabilities that are important for you to know to solve the problem sets and to solve real-life problems. Take note of the applicability of the normal distribution, which is a major cornerstone for statistical analysis.</li>
</ul>
</section>
<section id="contingency-tables" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">7.1</span> Contingency Tables</h2>
<ul>
<li>A contingency table generally shows frequencies for two qualitative or categorical variables, x and y.</li>
<li>Each cell represents a mutually exclusive combination of the pair of x and y values.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/ContTableEx.png" title="Contingency Table Example" class="img-fluid figure-img"></p>
<figcaption>Contingency Table Example</figcaption>
</figure>
</div>
<ul>
<li>Note that each cell in the contingency table represents a frequency.
<ul>
<li>In the above table, 174 customers under the age of 35 purchased an Under Armour product.</li>
<li>54 customers at least 35 years old purchased an Under Armour product.</li>
</ul></li>
<li>The contingency table may be used to calculate probabilities using relative frequency.
<ul>
<li>First obtain the row and column totals.</li>
<li>Sample size is equal to the total of the row totals or column totals. In this case, n = 600.</li>
</ul></li>
</ul>
<section id="probability-rules" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="probability-rules"><span class="header-section-number">7.1.1</span> Probability Rules</h3>
<ul>
<li>The addition rule refers to the probability that event A or B occurs, or that at least one of these events occurs, is the following:<br>
<span class="math display">\[P(A \cup B) = (P(A) + P(B) - P(A \cap B)\]</span></li>
<li>The complement rule refers to the probability of the complement of an event, <span class="math inline">\(P(A^c)\)</span> is equal to one minus the probability of the event.<br>
<span class="math display">\[P(A^c) = 1-P(A)\]</span></li>
<li>Conditional probability refers to the probability of an event given that another event has already occurred.
<ul>
<li>Given two events A and B, each with a positive probability of occurring, the probability that A occurs given that B has occurred (A conditioned on B) is equals to <span class="math inline">\(P(A|B) = (P(A \cap B)/P(B)\)</span>. Similarly, the probability that B occurs given that A has occurred (B conditioned on A) is equal to <span class="math inline">\(P(B|A) = (P(B \cap A)/P(A)\)</span>.</li>
</ul></li>
<li>Marginal probability refers to the probability of an event occurring <span class="math inline">\((P(A))\)</span>, it may be thought of as an unconditional probability. It is not conditioned on another event.</li>
<li>The joint probability rule is determined by dividing each cell frequency by the grand total. Joint probability refers to the statistical measure that calculates the likelihood of two events occurring together and at the same point in time.<br>
<span class="math display">\[P(A \cap B)\]</span>
<ul>
<li>For example, the probability that a randomly selected person is under 35 years of age and makes an Under Armour purchase is <span class="math inline">\(P(U35 \cap UA)=174/600= .29\)</span></li>
</ul></li>
<li>For example, this Venn Diagram illustrates the sample space for events A and B.</li>
<li>The union of two events (<span class="math inline">\(A \cup B\)</span>) is the event consisting of all simple events in A or B.</li>
</ul>
<p><img src="Pictures/Ch5/Venn1.png" title="Venn Diagram" class="img-fluid" alt="Venn Diagram"> The intersection of two events (<span class="math inline">\(A \cap B\)</span>) consists of all simple events in both A and B.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/Venn2.png" title="Venn Diagram: Intersection and Union" class="img-fluid figure-img"></p>
<figcaption>Venn Diagram: Intersection and Union</figcaption>
</figure>
</div>
<ul>
<li>The complement of event A (i.e., <span class="math inline">\(A^c\)</span>) is the event consisting of all simple events in the sample space S that are not in A.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/Venn3.png" title="Venn Diagram: Complement Rule" class="img-fluid figure-img"></p>
<figcaption>Venn Diagram: Complement Rule</figcaption>
</figure>
</div>
</section>
<section id="summary-measures-for-a-random-variable" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="summary-measures-for-a-random-variable"><span class="header-section-number">7.1.2</span> Summary Measures for a Random Variable</h3>
<ul>
<li>The Summary Measures of a Random Variable are consistent with our discussion of Probability in the last lesson. They are copied back here for ease of reference.</li>
</ul>
<section id="expected-value" class="level4" data-number="7.1.2.1">
<h4 data-number="7.1.2.1" class="anchored" data-anchor-id="expected-value"><span class="header-section-number">7.1.2.1</span> Expected Value</h4>
<ul>
<li>We can calculate the expected value, or value we think is going to occur based on the type of distribution.
<ul>
<li>Expected value is also known as the population mean <span class="math inline">\(\mu\)</span>, and is the weighted average of all possible values of <span class="math inline">\(X\)</span>.</li>
<li>More specifically, <span class="math inline">\(E(X)\)</span> is the long-run average value of the random variable over infinitely many independent repetitions of an experiment.</li>
<li>For a discrete random variable <span class="math inline">\(X\)</span> with values <span class="math inline">\(x_1, x_2, x_3, ...\)</span> that occur with probabilities <span class="math inline">\(P(X=x_i)\)</span>, the expected value of <span class="math inline">\(X\)</span> is the probability weighted average of the values. In the case of one random variable, that means: <span class="math display">\[E(X) = \mu = \sum{x_iP(X=x_i)} = n*p\]</span></li>
</ul></li>
</ul>
</section>
<section id="variance" class="level4" data-number="7.1.2.2">
<h4 data-number="7.1.2.2" class="anchored" data-anchor-id="variance"><span class="header-section-number">7.1.2.2</span> Variance</h4>
<ul>
<li>Variance of a random variable is the average of the squared differences from the mean.
<ul>
<li>For a discrete random variable <span class="math inline">\(X\)</span> with values <span class="math inline">\(x_1, x_2, x_3, ...\)</span> that occur with probabilities <span class="math inline">\(P(X=x_i)\)</span>, the variance is defined as: <span class="math display">\[Var(X) = \sigma^2 = \sum{(x_i-\mu)^2*P(X=x_i)} = n*p*(1-p)\]</span></li>
</ul></li>
</ul>
</section>
<section id="standard-deviation" class="level4" data-number="7.1.2.3">
<h4 data-number="7.1.2.3" class="anchored" data-anchor-id="standard-deviation"><span class="header-section-number">7.1.2.3</span> Standard Deviation</h4>
<ul>
<li>Standard deviation is consistently the square root of the variance. <span class="math display">\[SD(X) = \sigma = \sqrt{\sigma^2} = \sqrt{\sum{(x_i-\mu)^2*P(X=x_i)}}= \sqrt{np*(1-p)}\]</span></li>
</ul>
</section>
</section>
<section id="calculating-probability" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="calculating-probability"><span class="header-section-number">7.1.3</span> Calculating Probability</h3>
<ul>
<li>We could calculate the statistics in this contingency table a couple of ways. First, we could manually calculate it like below.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate Totals</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>TotalUnder35 <span class="ot">&lt;-</span> <span class="dv">174</span> <span class="sc">+</span> <span class="dv">132</span> <span class="sc">+</span> <span class="dv">90</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>TotalUnder35  <span class="do">##Total under 35 age group</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 396</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Total35up <span class="ot">&lt;-</span> <span class="dv">54</span> <span class="sc">+</span> <span class="dv">72</span> <span class="sc">+</span> <span class="dv">78</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Total35up  <span class="do">## Total 35 and older</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>TotalUA <span class="ot">&lt;-</span> <span class="dv">174</span> <span class="sc">+</span> <span class="dv">54</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>TotalUA  <span class="do">## Total Under Armour</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 228</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>TotalNike <span class="ot">&lt;-</span> <span class="dv">132</span> <span class="sc">+</span> <span class="dv">72</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>TotalNike  <span class="do">## Total Nike</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>TotalAdidas <span class="ot">&lt;-</span> <span class="dv">90</span> <span class="sc">+</span> <span class="dv">78</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>TotalAdidas  <span class="do">## Total Adidas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 168</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Total <span class="ot">&lt;-</span> <span class="dv">174</span> <span class="sc">+</span> <span class="dv">132</span> <span class="sc">+</span> <span class="dv">90</span> <span class="sc">+</span> <span class="dv">54</span> <span class="sc">+</span> <span class="dv">72</span> <span class="sc">+</span> <span class="dv">78</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Total  <span class="do">##Grand Total </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 600</code></pre>
</div>
</div>
<ul>
<li>Alternatively, we could make this a matrix and use the matrix command to help us calculate the answer. This gives us all the statistics with a couple of functions and allows us to interpret from there after selecting the right information from the output.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Put observed values in a vector by row.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">174</span>, <span class="dv">132</span>, <span class="dv">90</span>, <span class="dv">54</span>, <span class="dv">72</span>, <span class="dv">78</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Turn the vector into a matrix. In this case, we had 2 rows, 3</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># columns, and entered the data by row.</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> <span class="fu">matrix</span>(x, <span class="dv">2</span>, <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]  174  132   90
[2,]   54   72   78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Next, we could add the names of the columns and rows values using</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the dimnames() command.</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(o) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Under 35"</span>, <span class="st">"35 and Older"</span>), <span class="fu">c</span>(<span class="st">"Under Armour"</span>, <span class="st">"Nike"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Adidas"</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Under Armour Nike Adidas
Under 35              174  132     90
35 and Older           54   72     78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can easily calculate the total from here.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(o)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 600</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>rowsums <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(o, <span class="dv">1</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>rowsums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Under 35 35 and Older 
         396          204 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>colsums <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(o, <span class="dv">2</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>colsums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Under Armour         Nike       Adidas 
         228          204          168 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(o)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>prob  <span class="co"># each cell represents a joint probability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Under Armour Nike Adidas
Under 35             0.29 0.22   0.15
35 and Older         0.09 0.12   0.13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rowprob <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(prob, <span class="dv">1</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>rowprob  <span class="co">#each value represents marginal probability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Under 35 35 and Older 
        0.66         0.34 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>colprob <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(prob, <span class="dv">2</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>colprob  <span class="co">#each value represents marginal probability</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Under Armour         Nike       Adidas 
        0.38         0.34         0.28 </code></pre>
</div>
</div>
<ul>
<li>Take note that when subsetting from the matrix we created above, the dimnames do not serve as a column or row. so the first number is in row 1, column 1. This is distinct from data.frames, which typically have the 1st column designated for the labels.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>prob[<span class="dv">1</span>, <span class="dv">1</span>]  <span class="co">#corresponds to the joint probability value associated with Row 1 (Under 35), Col 1 (Under Armour)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.29</code></pre>
</div>
</div>
<ul>
<li><p>Once we do our calculations our totals, we can ask probability questions.</p></li>
<li><p>When looking up an answer to the question, it makes it easier to reference the tables to ensure you are subsetting correctly.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Under Armour Nike Adidas
Under 35              174  132     90
35 and Older           54   72     78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Under Armour Nike Adidas
Under 35             0.29 0.22   0.15
35 and Older         0.09 0.12   0.13</code></pre>
</div>
</div>
<ul>
<li>If a person is under 35, what is the probability they will select Under Armour? <span class="math display">\[P(UA|under35) = (P(UA \cap under35)/P(under35))\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is a conditional probability question.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="dv">174</span><span class="sc">/</span><span class="dv">396</span>  <span class="co">#or</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4393939</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>prob[<span class="dv">1</span>, <span class="dv">1</span>]<span class="sc">/</span>rowprob[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Under 35 
0.4393939 </code></pre>
</div>
</div>
<ul>
<li>What is the probability of a person 35 or older randomly selecting Nike? <span class="math display">\[P(N|older35) = (P(N \cap older35)/P(older35))\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is a conditional probability question.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="dv">72</span><span class="sc">/</span><span class="dv">204</span>  <span class="co"># or</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3529412</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>prob[<span class="dv">2</span>, <span class="dv">2</span>]<span class="sc">/</span>rowprob[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>35 and Older 
   0.3529412 </code></pre>
</div>
</div>
<ul>
<li>If the chance the preference was the same regardless of condition, how many people would you expect to select Nike? <span class="math display">\[Ex(Nike)\]</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is a expected value question.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>TotalNike  <span class="co"># or</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>colsums[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nike 
 204 </code></pre>
</div>
</div>
<ul>
<li>We can calculate summary measures based on a variable category.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># E(X) of 35 Years or older (formula n*p)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> total</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>n  <span class="co">#600</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 600</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> rowprob[<span class="dv">2</span>]</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>p  <span class="co">#.34</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>35 and Older 
        0.34 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>n <span class="sc">*</span> p  <span class="co">#Or simply the frequency for the column 35 and older</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>35 and Older 
         204 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Var(X) (formula n*p*(1-p))</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>varx <span class="ot">&lt;-</span> n <span class="sc">*</span> p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>varx  <span class="co">#134.64</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>35 and Older 
      134.64 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SD(X) (formula sqrt of variance)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>sdx <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(varx)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>sdx  <span class="co">#11.60345 </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>35 and Older 
    11.60345 </code></pre>
</div>
</div>
</section>
<section id="larger-contingency-table" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="larger-contingency-table"><span class="header-section-number">7.1.4</span> Larger Contingency Table</h3>
<ul>
<li>The survey question asked participants in multiple groups the following question, “How likely are you to participate in the event in the future?”</li>
<li>In order to answer this question, first, lets bring in some data and calculate totals.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/ConTblNum.png" title="Contingency Table Numbers" class="img-fluid figure-img"></p>
<figcaption>Contingency Table Numbers</figcaption>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">197</span>, <span class="dv">388</span>, <span class="dv">230</span>, <span class="dv">103</span>, <span class="dv">137</span>, <span class="dv">98</span>, <span class="dv">20</span>, <span class="dv">18</span>, <span class="dv">18</span>, <span class="dv">13</span>, <span class="dv">58</span>, <span class="dv">45</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> <span class="fu">matrix</span>(x, <span class="dv">4</span>, <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]  197  388  230
[2,]  103  137   98
[3,]   20   18   18
[4,]   13   58   45</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(o) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Students"</span>, <span class="st">"Faculty/Staff"</span>, <span class="st">"Alumni"</span>, <span class="st">"Town Residents"</span>),</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Unlikely"</span>, <span class="st">"Moderately Likely"</span>, <span class="st">"Very Likely"</span>))</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>o</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Unlikely Moderately Likely Very Likely
Students            197               388         230
Faculty/Staff       103               137          98
Alumni               20                18          18
Town Residents       13                58          45</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">sum</span>(o)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1325</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>rowsums <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(o, <span class="dv">1</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>rowsums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Students  Faculty/Staff         Alumni Town Residents 
           815            338             56            116 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>colsums <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(o, <span class="dv">2</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>colsums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Unlikely Moderately Likely       Very Likely 
              333               601               391 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lets add the grand total to the colsums</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>colsums <span class="ot">&lt;-</span> <span class="fu">c</span>(colsums, total)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>colsums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Unlikely Moderately Likely       Very Likely                   
              333               601               391              1325 </code></pre>
</div>
</div>
<ul>
<li>In this example, we can bind the data together so that it is a little easier to see. Examine the final table and compare that to the figure above.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>totals <span class="ot">&lt;-</span> <span class="fu">cbind</span>(o, rowsums)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>totals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Unlikely Moderately Likely Very Likely rowsums
Students            197               388         230     815
Faculty/Staff       103               137          98     338
Alumni               20                18          18      56
Town Residents       13                58          45     116</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>totals <span class="ot">&lt;-</span> <span class="fu">rbind</span>(totals, colsums)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>totals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Unlikely Moderately Likely Very Likely rowsums
Students            197               388         230     815
Faculty/Staff       103               137          98     338
Alumni               20                18          18      56
Town Residents       13                58          45     116
colsums             333               601         391    1325</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/ConTblProp.png" title="Contingency Table Proportions" class="img-fluid figure-img"></p>
<figcaption>Contingency Table Proportions</figcaption>
</figure>
</div>
<ul>
<li>Next, let’s calculate probabilities.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(o)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Unlikely Moderately Likely Very Likely
Students       0.148679245        0.29283019  0.17358491
Faculty/Staff  0.077735849        0.10339623  0.07396226
Alumni         0.015094340        0.01358491  0.01358491
Town Residents 0.009811321        0.04377358  0.03396226</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>TotalRowProb <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(prob, <span class="dv">1</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>TotalRowProb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Students  Faculty/Staff         Alumni Town Residents 
    0.61509434     0.25509434     0.04226415     0.08754717 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>TotalColProb <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(prob, <span class="dv">2</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>TotalColProb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Unlikely Moderately Likely       Very Likely 
        0.2513208         0.4535849         0.2950943 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>TotalColProb <span class="ot">&lt;-</span> <span class="fu">c</span>(TotalColProb, <span class="fu">sum</span>(TotalColProb))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>TotalColProb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Unlikely Moderately Likely       Very Likely                   
        0.2513208         0.4535849         0.2950943         1.0000000 </code></pre>
</div>
</div>
<ul>
<li>In this example, we can also bind the data together so that it is a little easier to see. Again, we are trying to get our R code in the best shape to be able to select the right information to calculate probability from it.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>proportions <span class="ot">&lt;-</span> <span class="fu">cbind</span>(prob, TotalRowProb)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>proportions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Unlikely Moderately Likely Very Likely TotalRowProb
Students       0.148679245        0.29283019  0.17358491   0.61509434
Faculty/Staff  0.077735849        0.10339623  0.07396226   0.25509434
Alumni         0.015094340        0.01358491  0.01358491   0.04226415
Town Residents 0.009811321        0.04377358  0.03396226   0.08754717</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>proportions <span class="ot">&lt;-</span> <span class="fu">rbind</span>(proportions, TotalColProb)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>proportions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Unlikely Moderately Likely Very Likely TotalRowProb
Students       0.148679245        0.29283019  0.17358491   0.61509434
Faculty/Staff  0.077735849        0.10339623  0.07396226   0.25509434
Alumni         0.015094340        0.01358491  0.01358491   0.04226415
Town Residents 0.009811321        0.04377358  0.03396226   0.08754717
TotalColProb   0.251320755        0.45358491  0.29509434   1.00000000</code></pre>
</div>
</div>
<ul>
<li><p>Now that our tables have been tabulated, we can answer some probability questions.</p></li>
<li><p>What proportion of Students participated in the survey?<br>
<span class="math inline">\(P_S= 815/1325\)</span> or <span class="math inline">\(0.61509434\)</span></p></li>
<li><p>What proportion of Faculty/Staff remarked that they were Unlikely to participate?<br>
<span class="math inline">\(P(U|FS) = P(U \cap FS) / P(FS) = 103/338 = 0.077735849/0.25509434 = 0.3047337\)</span></p></li>
<li><p>If a person is a Town Resident, what is the probability that they will select Very Likely?<br>
<span class="math inline">\(P(VL|TR) = P(VL \cap TR) / P(TR) = 45/116 = 0.03396226/0.08754717 = 0.387931\)</span></p></li>
<li><p>What proportion of people would you expect to select Moderately Likely?<br>
<span class="math inline">\(P_ML = 601/1325\)</span> or <span class="math inline">\(0.4535849\)</span>. What is the expected number? <span class="math inline">\(E(ML) = 601\)</span>.</p></li>
<li><p>What is the probability that a randomly selected person is a Faculty/Staff or selects Very Likely?<br>
<span class="math inline">\(P_FS + P_VL - P_FS \cup P_VL = 0.25509434 + 0.2950943 − 0.07396226 = 0.4762264\)</span></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># E(X) of Moderately Likely (formula n*p)</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> total</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>n  <span class="co">#1325</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1325</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> TotalColProb[<span class="dv">2</span>]</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>p  <span class="co">#.45358</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moderately Likely 
        0.4535849 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>n <span class="sc">*</span> p  <span class="co">#Or simply the frequency for the column Moderately Likely</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moderately Likely 
              601 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Var(X) (formula n*p*(1-p))</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>varx <span class="ot">&lt;-</span> n <span class="sc">*</span> p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>varx  <span class="co">#328.3955</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moderately Likely 
         328.3955 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SD(X) (formula sqrt of variance)</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>sdx <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(varx)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>sdx  <span class="co">#18.12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moderately Likely 
         18.12169 </code></pre>
</div>
</div>
</section>
</section>
<section id="chi-squared-test-for-independence" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="chi-squared-test-for-independence"><span class="header-section-number">7.2</span> Chi-Squared Test for Independence</h2>
<ul>
<li><p>Broadly, the test for independence tests whether or not two variables whose frequencies are represented in a contingency table have statistical independence from one another.</p></li>
<li><p>A test of independence – also called a chi-square test of a contingency table – is used to analyze the relationship between two qualitative variables.</p></li>
<li><p>Broadly, this test involves summing the squared differences between observed and expected values, combining the differences into an overall statistic, and then using that statistic to determine significance of the hypothesis test.<br>
<span class="math inline">\(\chi^2 = \frac{(observed-expected)^2}{expected}\)</span></p></li>
<li><p>Squaring the differences before adding them up will result in a positive value that is larger when there are larger differences and smaller when there are smaller differences. This value captures the magnitude of the difference between observed and expected values.</p></li>
<li><p>In order to account for situations when the observed and expected values are very large, which could result in extremely large differences between observed and expected, the squared differences are divided by the expected value in each cell.</p></li>
<li><p>Visualizing the Chi-squared Distribution Chi-squared distribution has a single parameter, the degrees of freedom or <span class="math inline">\(df\)</span>.<br>
<span class="math inline">\(\sqrt(2*df)\)</span></p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="contingency_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The Chi-squared probability density function shows the probability of a value of chi-squared occurring when there is no relationship between the two variables contributing to the chi-squared, where a large chi-square indicates a relationship between variables.</li>
<li>The competing hypotheses can be expressed as:
<ul>
<li><span class="math inline">\(H_0\)</span>: The two classifications are independent.</li>
<li><span class="math inline">\(H_A\)</span>: The two classifications are dependent.</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="contingency_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="steps-to-conduct-chi-squared-test-for-independence" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="steps-to-conduct-chi-squared-test-for-independence"><span class="header-section-number">7.2.1</span> Steps to conduct Chi-Squared Test for Independence</h3>
<ul>
<li>Step 1: Write the null and alternate hypotheses.</li>
<li>Step 2: Compute the test statistic.</li>
<li>Step 3: Calculate the probability.</li>
<li>Step 4: If the probability that the null is true is very small, usually less than 5%, reject the null hypothesis OR If the probability that the null is true is not small, usually 5% or greater, retain the null hypothesis.</li>
</ul>
</section>
<section id="assumptions-of-the-chi-squared-test-of-independence" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="assumptions-of-the-chi-squared-test-of-independence"><span class="header-section-number">7.2.2</span> Assumptions of the Chi-Squared Test of Independence</h3>
<ul>
<li><p>Assumption 1: The variables must be nominal or ordinal.</p></li>
<li><p>Assumption 2: The expected values should be 5 or higher in at least 80% of groups.</p></li>
<li><p>Assumption 3: The observations must be independent.</p></li>
<li><p>Note that there are a couple of ways observations can be non-independent.</p>
<ul>
<li>One way to violate this assumption would be if the data included the same set of people before and after some intervention or treatment.</li>
<li>Another way to violate this assumption would be for the data to include siblings or parents and children or spouses or other people who are somehow linked to one another.</li>
<li>Since people who are linked to each other often have similar characteristics, statistical tests need to be able to account for this and the chi-squared test does not.</li>
</ul></li>
</ul>
</section>
<section id="example-of-a-test-for-independence" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="example-of-a-test-for-independence"><span class="header-section-number">7.2.3</span> Example of a Test for Independence</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch5/ContTableEx.png" title="Contingency Table Example" class="img-fluid figure-img"></p>
<figcaption>Contingency Table Example</figcaption>
</figure>
</div>
<ul>
<li>Step 1: Set up the Hypothesis
<ul>
<li><span class="math inline">\(H_0\)</span>: Age group and Brand Name are independent.</li>
<li><span class="math inline">\(H_A\)</span>: Age group and Brand Name are dependent.</li>
</ul></li>
<li>First, we bring in the data manually from the table by column. We had 3 columns, so we need to make three vectors as shown below.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>UA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">174</span>, <span class="dv">54</span>)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">132</span>, <span class="dv">72</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">90</span>, <span class="dv">78</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Then we convert these columns to a data frame. If you already have a data frame, you don’t have to do this step.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(UA, N, A)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>M</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   UA   N  A
1 174 132 90
2  54  72 78</code></pre>
</div>
</div>
<ul>
<li><p>Always make sure your data frame looks like the table.</p></li>
<li><p>Steps 2 and 3: Compute the test statistic and calculate the probability.</p></li>
<li><p>Here, we run the chisq.test() command, which only includes the columns of interest.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  M
X-squared = 22.529, df = 2, p-value = 1.282e-05</code></pre>
</div>
</div>
<ul>
<li>Step 4: If the probability that the null is true is very small, usually less than 5%, reject the null hypothesis versus If the probability that the null is true is not small, usually 5% or greater, retain the null hypothesis.</li>
<li>Here, our p-value is 1.282e-05, so we reject the null, <span class="math inline">\(H_0\)</span>, and conclude that Age group and Brand Names are dependent.</li>
</ul>
</section>
<section id="example-using-an-imported-dataset" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="example-using-an-imported-dataset"><span class="header-section-number">7.2.4</span> Example Using an Imported Dataset</h3>
<ul>
<li>Import the STEM data into a data frame (table) into R.</li>
<li>Step 1: Set up the Hypothesis:
<ul>
<li><span class="math inline">\(H_0\)</span>: Stem field and Gender are independent.</li>
<li><span class="math inline">\(H_A\)</span>: Stem field and Gender are dependent.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>STEM <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/stem.csv"</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>STEM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   STEM.field Female Male
1    Sciences    120  100
2  Technology     15   75
3 Engineering     30  125
4        Math     15   20</code></pre>
</div>
</div>
<ul>
<li>Steps 2 and 3: Compute the test statistic and calculate the probability.</li>
<li>Again, we use Rs chisq.test() command to calculate the value of the test statistic, as well as the p-value. Within the chisq.test() function, we indicate that the relevant data are in columns 2 and 3 of the data frame.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(STEM[, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  STEM[, 2:3]
X-squared = 66.795, df = 3, p-value = 2.072e-14</code></pre>
</div>
</div>
<ul>
<li>Step 4: If the probability that the null is true is very small, usually less than 5%, reject the null hypothesis versus If the probability that the null is true is not small, usually 5% or greater, retain the null hypothesis.</li>
<li>Since the p-value is less than 0.05, we can reject the null hypothesis. At the 5% significance level, we can conclude that one’s sex does influence field choice within the STEM major.</li>
</ul>
</section>
</section>
<section id="chi-squared-goodness-of-fit-test" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="chi-squared-goodness-of-fit-test"><span class="header-section-number">7.3</span> Chi-Squared Goodness of Fit Test</h2>
<ul>
<li><p>There are a few other tests regarding a Chi-squared distribution, and one other is the goodness of fit test.</p></li>
<li><p>This test determines whether two or more population proportions equal each other or any predetermined set of values and like the test for independence, still involves the fit between observed and estimated values.</p></li>
<li><p>A multinomial experiment consists of a series of n independent trials such that:</p></li>
<li><p>On each there are k possible outcomes.</p></li>
<li><p>The probability of falling into category <span class="math inline">\(i\)</span> is the same on each trial.</p></li>
<li><p>The <span class="math inline">\(k\)</span> probabilities sum to <span class="math inline">\(1:p_1 + p_2 +⋯+p_k = 1\)</span></p></li>
<li><p>The null hypothesis: the population proportions are equal to one another or they are each equal to a specific value.</p></li>
<li><p>For example, are four candidates in an election equally favored by voters?</p></li>
<li><p>Equal Population proportions:<br>
<span class="math inline">\(H_0: P_1=P_2=P_3=P_4=.25;\)</span><br>
<span class="math inline">\(H_A\)</span>:Not all populations are equal to .25</p></li>
<li><p>Or, do people rate food quality in a restaurant comparably to last year?</p></li>
<li><p>Unequal Population Proportions:<br>
<span class="math inline">\(H_0: P_1= .4, P_2=.3, P_3= .2, P_4=.1;\)</span><br>
<span class="math inline">\(H_A:\)</span> At least one <span class="math inline">\(P_i\)</span> differs from its hypothesized value.</p></li>
</ul>
<section id="example-using-raw-numbers" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="example-using-raw-numbers"><span class="header-section-number">7.3.1</span> Example Using Raw Numbers</h3>
<ul>
<li><p>Last year the management at a restaurant surveyed its patrons to rate the quality of its food. The results were as follows: 15% Excellent; 30% Good; 45% Fair; and 10% Poor.</p></li>
<li><p>Based on this and other survey results, management made changes to the menu.</p></li>
<li><p>This year, the management surveyed 250 patrons, asking the same questions about food quality. Here are the results: 46 Excellent; 83 Good; 105 Fair; and 16 Poor.</p></li>
<li><p>We want to know if the current results agree with those from last year, or if there has been a significant change.</p></li>
<li><p>To do this, we compute an expected frequency for each category and compare it to what we actually observe. Then, we compute the difference between what was observed and expected for each category. If the results this year are consistent with last year, these differences will be relatively small.</p></li>
<li><p>The steps are same as the Chi-Squared Test of Independence.</p></li>
<li><p>Step 1: Set up the Hypothesis:</p>
<ul>
<li><span class="math inline">\(𝐻_0\)</span>: Each proportion equals a hypothesized value.</li>
<li><span class="math inline">\(𝐻_A\)</span>: Not all proportions equal their hypothesized values.</li>
</ul></li>
<li><p>Steps 2 and3: Compute the test statistic and calculate the probability.</p></li>
<li><p>We can use R’s chisq.test() function to calculate the value of the test statistic and corresponding p-value. Within this function, we use the option p to indicate the location of the hypothesized proportions.<br>
</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chi Squared Test Goodness of Fit</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">46</span>, <span class="dv">83</span>, <span class="dv">105</span>, <span class="dv">16</span>)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.15</span>, <span class="fl">0.3</span>, <span class="fl">0.45</span>, <span class="fl">0.1</span>)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(o, <span class="at">p =</span> p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  o
X-squared = 6.52, df = 3, p-value = 0.08888</code></pre>
</div>
</div>
<ul>
<li><p>Note that p= is required here because it is not the second argument in the chisq.test() command.</p></li>
<li><p>Step 4: If the probability that the null is true is very small, usually less than 5%, reject the null hypothesis versus If the probability that the null is true is not small, usually 5% or greater, retain the null hypothesis.</p></li>
<li><p>At alpha = .05, we do not reject <span class="math inline">\(H_0\)</span> and cannot conclude that the proportions differ from the ones a year ago.</p></li>
</ul>
</section>
<section id="example-using-an-imported-dataset-1" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="example-using-an-imported-dataset-1"><span class="header-section-number">7.3.2</span> Example Using an Imported Dataset</h3>
<ul>
<li>The steps are same as the Chi-Squared Test of Independence.</li>
<li>Step 1: Set up the Hypothesis:
<ul>
<li><span class="math inline">\(𝐻_0\)</span>: Each proportion equals a hypothesized value.</li>
<li><span class="math inline">\(𝐻_A\)</span>: Not all proportions equal their hypothesized values.</li>
</ul></li>
<li>Steps 2 and 3: Compute the test statistic and calculate the probability.</li>
<li>First, we import the stemGOF.csv data into a data frame (table) in R.</li>
<li>Then, again, we use Rs chisq.test function to calculate the value of the test statistic and the p-value. Within the chisq.test function, we use the option p to indicate the location of the hypothesized proportions.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>STEMGOF <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/stemGOF.csv"</span>)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>STEMGOF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Major X2010Proportions RecentNumbers
1        Business             0.19            80
2       Education             0.09            35
3      Healthcare             0.12            85
4 Social Sciences             0.22           105
5            STEM             0.08            55
6           Other             0.30           140</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(STEMGOF<span class="sc">$</span>RecentNumbers, <span class="at">p =</span> STEMGOF<span class="sc">$</span>X2010Proportions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  STEMGOF$RecentNumbers
X-squared = 21.526, df = 5, p-value = 0.0006441</code></pre>
</div>
</div>
<ul>
<li>Step 4: If the probability that the null is true is very small, usually less than 5%, reject the null hypothesis versus If the probability that the null is true is not small, usually 5% or greater, retain the null hypothesis.</li>
<li>Since our p-value is 0.0006441, we reject <span class="math inline">\(H_0\)</span> and conclude that the proportions differ at the 5% significance level. In this case, that means that the recent stem numbers differ from the 2010 values.</li>
</ul>
</section>
</section>
<section id="summary" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">7.4</span> Summary</h2>
<ul>
<li>In this lesson, we learned about contingency tables in regards to calculating probability with two categorical variables. We also computed the chi-squared statistics for the test of independence and the goodness of fit.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./probability.html" class="pagination-link" aria-label="Probability and Probability Distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Probability Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ttests.html" class="pagination-link" aria-label="Hypothesis Testing with t-Tests">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hypothesis Testing with t-Tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>