<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Descriptive Statistics – Probability And Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./dataprep.html" rel="next">
<link href="./introR.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-64b801fe9b6685c0a799f7172ecad621.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
     <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4MST1J29YB"></script>
          <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          
          gtag('config', 'G-4MST1J29YB');
          </script>

<!-- ============================================================
     Statistics Course Assistant — Floating Chat Bubble
     Appears on every page of the book.
     Set WORKER_URL below to your Cloudflare Worker URL.
     ============================================================ -->
<style>
  /* ── Floating button ── */
  #chat-fab {
    position: fixed;
    bottom: 28px;
    right: 28px;
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 4px 20px rgba(79, 142, 247, 0.45);
    z-index: 9999;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  #chat-fab:hover {
    transform: scale(1.08);
    box-shadow: 0 6px 28px rgba(79, 142, 247, 0.6);
  }

  #chat-fab svg { width: 24px; height: 24px; color: #fff; }

  /* unread dot */
  #chat-fab-dot {
    position: absolute;
    top: 4px;
    right: 4px;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: #ff5a5a;
    border: 2px solid #fff;
    display: none;
  }

  /* ── Chat panel ── */
  #chat-panel {
    position: fixed;
    bottom: 96px;
    right: 28px;
    width: 380px;
    max-width: calc(100vw - 40px);
    height: 520px;
    max-height: calc(100vh - 120px);
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 16px;
    display: none;
    flex-direction: column;
    z-index: 9998;
    box-shadow: 0 12px 48px rgba(0,0,0,0.5);
    overflow: hidden;
    animation: panelIn 0.25s ease;
    font-family: 'IBM Plex Sans', -apple-system, sans-serif;
  }

  #chat-panel.open { display: flex; }

  @keyframes panelIn {
    from { opacity: 0; transform: translateY(12px) scale(0.97); }
    to   { opacity: 1; transform: translateY(0) scale(1); }
  }

  /* panel header */
  #chat-panel-header {
    padding: 14px 16px;
    background: #181c27;
    border-bottom: 1px solid #2a2f3e;
    display: flex;
    align-items: center;
    gap: 10px;
    flex-shrink: 0;
  }

  #chat-panel-header .logo {
    width: 30px;
    height: 30px;
    border-radius: 7px;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 600;
    color: #fff;
    font-family: 'IBM Plex Mono', monospace;
    flex-shrink: 0;
  }

  #chat-panel-header .title { flex: 1; }

  #chat-panel-header .title h3 {
    font-size: 13px;
    font-weight: 600;
    color: #e8eaf0;
    margin: 0;
    line-height: 1.2;
  }

  #chat-panel-header .title p {
    font-size: 11px;
    color: #7a8099;
    margin: 0;
    font-family: 'IBM Plex Mono', monospace;
  }

  #chat-close-btn {
    background: none;
    border: none;
    color: #7a8099;
    cursor: pointer;
    padding: 4px;
    border-radius: 4px;
    display: flex;
    align-items: center;
    transition: color 0.15s;
  }

  #chat-close-btn:hover { color: #e8eaf0; }
  #chat-close-btn svg { width: 16px; height: 16px; }

  /* messages */
  #chat-messages {
    flex: 1;
    overflow-y: auto;
    padding: 14px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    scroll-behavior: smooth;
  }

  #chat-messages::-webkit-scrollbar { width: 3px; }
  #chat-messages::-webkit-scrollbar-thumb { background: #2a2f3e; border-radius: 3px; }

  .cm {
    display: flex;
    gap: 8px;
    animation: msgIn 0.2s ease;
  }

  @keyframes msgIn {
    from { opacity: 0; transform: translateY(4px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  .cm-av {
    width: 22px;
    height: 22px;
    border-radius: 5px;
    flex-shrink: 0;
    margin-top: 1px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 9px;
    font-weight: 700;
    font-family: 'IBM Plex Mono', monospace;
  }

  .cm.user .cm-av  { background: #1e2640; border: 1px solid #2e3a5a; color: #4f8ef7; }
  .cm.bot .cm-av   { background: linear-gradient(135deg, #4f8ef7, #7c5cfc); color: #fff; }
  .cm.error .cm-av { background: #3a1010; color: #ff8a8a; }

  .cm-text {
    flex: 1;
    background: #141720;
    border: 1px solid #2a2f3e;
    border-radius: 10px;
    padding: 8px 11px;
    font-size: 13px;
    line-height: 1.55;
    color: #e8eaf0;
    min-width: 0;
    word-break: break-word;
  }

  .cm.user .cm-text  { background: #1e2640; border-color: #2e3a5a; }
  .cm.error .cm-text { background: #1c1010; border-color: #5a2e2e; color: #ff8a8a; }

  .cm-text p { margin: 0 0 6px; }
  .cm-text p:last-child { margin-bottom: 0; }

  .cm-text code {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 3px;
    padding: 1px 5px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 11.5px;
    color: #a5c3ff;
  }

  .cm-text pre {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 6px;
    padding: 10px 12px;
    overflow-x: auto;
    margin: 6px 0;
  }

  .cm-text pre code {
    background: none;
    border: none;
    padding: 0;
    font-size: 12px;
    color: #c8d8ff;
  }

  .cm-text ul, .cm-text ol { padding-left: 16px; margin: 4px 0; }
  .cm-text li { margin-bottom: 3px; }
  .cm-text strong { color: #fff; font-weight: 600; }

  /* typing dots */
  .typing-dots { display: flex; gap: 3px; align-items: center; padding: 2px 0; }
  .typing-dots span {
    width: 5px; height: 5px; border-radius: 50%;
    background: #7a8099;
    animation: td 1.2s infinite;
  }
  .typing-dots span:nth-child(2) { animation-delay: 0.2s; }
  .typing-dots span:nth-child(3) { animation-delay: 0.4s; }

  @keyframes td {
    0%,60%,100% { transform: translateY(0); opacity:0.4; }
    30% { transform: translateY(-4px); opacity:1; }
  }

  /* welcome inside panel */
  .panel-welcome {
    text-align: center;
    padding: 20px 10px;
    color: #7a8099;
  }

  .panel-welcome p {
    font-size: 12.5px;
    margin: 0 0 14px;
    line-height: 1.5;
    color: #7a8099;
  }

  .panel-chips {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    justify-content: center;
  }

  .panel-chip {
    background: #181c27;
    border: 1px solid #2a2f3e;
    border-radius: 14px;
    padding: 5px 10px;
    font-size: 11.5px;
    color: #7a8099;
    cursor: pointer;
    transition: all 0.15s;
    font-family: 'IBM Plex Mono', monospace;
    text-align: left;
  }

  .panel-chip:hover {
    border-color: #4f8ef7;
    color: #4f8ef7;
    background: rgba(79,142,247,0.07);
  }

  /* input row */
  #chat-input-row {
    padding: 10px 12px;
    border-top: 1px solid #2a2f3e;
    background: #181c27;
    display: flex;
    gap: 8px;
    align-items: flex-end;
    flex-shrink: 0;
  }

  #chat-input {
    flex: 1;
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 8px;
    padding: 8px 11px;
    font-family: -apple-system, sans-serif;
    font-size: 13px;
    color: #e8eaf0;
    resize: none;
    min-height: 36px;
    max-height: 100px;
    outline: none;
    line-height: 1.4;
    transition: border-color 0.2s;
    overflow-y: auto;
  }

  #chat-input:focus { border-color: #4f8ef7; }
  #chat-input::placeholder { color: #7a8099; }

  #chat-send {
    width: 36px;
    height: 36px;
    border-radius: 8px;
    border: none;
    background: #4f8ef7;
    color: #fff;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    transition: opacity 0.15s;
  }

  #chat-send:hover { opacity: 0.85; }
  #chat-send:disabled { opacity: 0.3; cursor: not-allowed; }
  #chat-send svg { width: 15px; height: 15px; }

  /* mobile adjustments */
  @media (max-width: 480px) {
    #chat-panel { right: 12px; bottom: 80px; width: calc(100vw - 24px); }
    #chat-fab   { right: 16px; bottom: 16px; }
  }
</style>

<!-- Floating Action Button -->
</head><body class="nav-sidebar floating nav-fixed"><button id="chat-fab" onclick="toggleChat()" title="Course Assistant" aria-label="Open course assistant">
  <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
  </svg>
  <div id="chat-fab-dot"></div>
</button>

<!-- Chat Panel -->
<div id="chat-panel">
  <div id="chat-panel-header">
    <div class="logo">R∑</div>
    <div class="title">
      <h3>Course Assistant</h3>
      <p>R &amp; Statistics</p>
    </div>
    <button id="chat-close-btn" onclick="toggleChat()" aria-label="Close">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>

  <div id="chat-messages">
    <div class="panel-welcome" id="panel-welcome">
      <p>Ask me anything about R, statistics concepts, or your code.</p>
      <div class="panel-chips">
        <div class="panel-chip" onclick="chipSend(this)">mean vs median?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is skewness?</div>
        <div class="panel-chip" onclick="chipSend(this)">How do I use filter()?</div>
        <div class="panel-chip" onclick="chipSend(this)">Explain na.rm=TRUE</div>
        <div class="panel-chip" onclick="chipSend(this)">How to read a CSV?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is kurtosis?</div>
      </div>
    </div>
  </div>

  <div id="chat-input-row">
    <textarea id="chat-input" rows="1" placeholder="Ask a question…" onkeydown="chatKey(event)" oninput="chatResize(this)"></textarea>
    <button id="chat-send" onclick="chatSend()" aria-label="Send">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="22" y1="2" x2="11" y2="13"></line>
        <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
      </svg>
    </button>
  </div>
</div>

<script>
  // ============================================================
  // Set this to your Cloudflare Worker URL after deploying

  // ============================================================
  var CHAT_WORKER_URL = 'https://statchat.pamela-schlosser.workers.dev';
  // ============================================================

  var chatHistory = [];
  var chatLoading = false;
  var chatIsOpen  = false;

  function toggleChat() {
    chatIsOpen = !chatIsOpen;
    var panel = document.getElementById('chat-panel');
    var dot   = document.getElementById('chat-fab-dot');
    if (chatIsOpen) {
      panel.classList.add('open');
      dot.style.display = 'none';
      setTimeout(function() {
        var inp = document.getElementById('chat-input');
        if (inp) inp.focus();
      }, 100);
    } else {
      panel.classList.remove('open');
    }
  }

  function chipSend(el) {
    var inp = document.getElementById('chat-input');
    inp.value = el.textContent.trim();
    chatSend();
  }

  function chatKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      chatSend();
    }
  }

  function chatResize(el) {
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 100) + 'px';
  }

  function escHtml(s) {
    return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  function mdToHtml(text) {
    text = text.replace(/```(\w*)\n?([\s\S]*?)```/g, function(_,l,c) {
      return '<pre><code>' + escHtml(c.trim()) + '</code></pre>';
    });
    text = text.replace(/`([^`]+)`/g, '<code>$1</code>');
    text = text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    text = text.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
    text = text.replace(/(<li>.*<\/li>\n?)+/g, function(m) { return '<ul>' + m + '</ul>'; });
    text = text.split(/\n{2,}/).map(function(p) {
      p = p.trim();
      if (!p || p.charAt(0) === '<') return p;
      return '<p>' + p.replace(/\n/g,'<br>') + '</p>';
    }).join('');
    return text;
  }

  function addMsg(role, content, typing) {
    var welcome = document.getElementById('panel-welcome');
    if (welcome) welcome.remove();
    var box = document.getElementById('chat-messages');
    var d   = document.createElement('div');
    d.className = 'cm ' + role;
    var av = role==='user' ? 'you' : role==='bot' ? 'ai' : '!';
    if (typing) {
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text" id="cm-typing">' +
        '<div class="typing-dots"><span></span><span></span><span></span></div>' +
        '</div>';
    } else {
      var html = role==='user'
        ? '<p>' + escHtml(content) + '</p>'
        : mdToHtml(content);
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text">' + html + '</div>';
    }
    box.appendChild(d);
    box.scrollTop = box.scrollHeight;
    if (!chatIsOpen && role === 'bot') {
      document.getElementById('chat-fab-dot').style.display = 'block';
    }
  }

  function removeTyping() {
    var t = document.getElementById('cm-typing');
    if (t) t.closest('.cm').remove();
  }

  async function chatSend() {
    if (chatLoading) return;

    var el   = document.getElementById('chat-input');
    var text = el.value.trim();
    if (!text) return;

    addMsg('user', text);
    chatHistory.push({ role: 'user', content: text });
    el.value = '';
    el.style.height = 'auto';

    chatLoading = true;
    document.getElementById('chat-send').disabled = true;
    addMsg('bot', '', true);

    try {
      var res = await fetch(CHAT_WORKER_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 1024,
          messages: chatHistory
        })
      });

      removeTyping();

      if (!res.ok) {
        var err = await res.json().catch(function() { return {}; });
        var msg = err.error || ('HTTP ' + res.status);
        addMsg('error', res.status === 429
          ? 'Rate limit reached. Please wait a moment and try again.'
          : 'Something went wrong: ' + msg);
        chatHistory.pop();
      } else {
        var data  = await res.json();
        var reply = (data.content && data.content[0] && data.content[0].text) || '(no response)';
        chatHistory.push({ role: 'assistant', content: reply });
        addMsg('bot', reply);
      }

    } catch(err) {
      removeTyping();
      addMsg('error', 'Network error: ' + err.message);
      chatHistory.pop();
    }

    chatLoading = false;
    document.getElementById('chat-send').disabled = false;
  }
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Probability And Business Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./chat.html"> 
<span class="menu-text">Course Assistant</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./descriptives.html"><span class="chapter-title">Descriptive Statistics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Software Know-How</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introR.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to R and RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Descriptive Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataprep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Preparation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">ANOVA and Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ai_viz.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Generative AI and Data Visualization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Recommended Further Reading Materials</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a Glance</a></li>
  <li><a href="#lesson-objectives" id="toc-lesson-objectives" class="nav-link" data-scroll-target="#lesson-objectives">Lesson Objectives</a></li>
  <li><a href="#consider-while-reading" id="toc-consider-while-reading" class="nav-link" data-scroll-target="#consider-while-reading">Consider While Reading</a></li>
  <li><a href="#summarizing-quantitative-data" id="toc-summarizing-quantitative-data" class="nav-link" data-scroll-target="#summarizing-quantitative-data">Summarizing Quantitative Data</a>
  <ul class="collapse">
  <li><a href="#defining-and-calculating-central-tendency" id="toc-defining-and-calculating-central-tendency" class="nav-link" data-scroll-target="#defining-and-calculating-central-tendency">Defining and Calculating Central Tendency</a>
  <ul class="collapse">
  <li><a href="#using-the-mean" id="toc-using-the-mean" class="nav-link" data-scroll-target="#using-the-mean">Using the Mean</a></li>
  <li><a href="#using-the-median" id="toc-using-the-median" class="nav-link" data-scroll-target="#using-the-median">Using the Median</a></li>
  <li><a href="#using-the-mode" id="toc-using-the-mode" class="nav-link" data-scroll-target="#using-the-mode">Using the Mode</a></li>
  <li><a href="#example-of-function-with-salary-variable" id="toc-example-of-function-with-salary-variable" class="nav-link" data-scroll-target="#example-of-function-with-salary-variable">Example of Function with Salary Variable</a></li>
  <li><a href="#finding-no-mode" id="toc-finding-no-mode" class="nav-link" data-scroll-target="#finding-no-mode">Finding No Mode</a></li>
  </ul></li>
  <li><a href="#defining-and-calculating-spread" id="toc-defining-and-calculating-spread" class="nav-link" data-scroll-target="#defining-and-calculating-spread">Defining and Calculating Spread</a>
  <ul class="collapse">
  <li><a href="#spread-to-report-with-the-mean" id="toc-spread-to-report-with-the-mean" class="nav-link" data-scroll-target="#spread-to-report-with-the-mean">Spread to Report with the Mean</a></li>
  </ul></li>
  <li><a href="#examples-from-the-customer-dataset" id="toc-examples-from-the-customer-dataset" class="nav-link" data-scroll-target="#examples-from-the-customer-dataset">Examples from the Customer Dataset</a>
  <ul class="collapse">
  <li><a href="#spread-to-report-with-the-median" id="toc-spread-to-report-with-the-median" class="nav-link" data-scroll-target="#spread-to-report-with-the-median">Spread to Report with the Median</a></li>
  <li><a href="#spread-to-report-with-the-mode" id="toc-spread-to-report-with-the-mode" class="nav-link" data-scroll-target="#spread-to-report-with-the-mode">Spread to Report with the Mode</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#visualizing-quantitative-variables" id="toc-visualizing-quantitative-variables" class="nav-link" data-scroll-target="#visualizing-quantitative-variables">Visualizing Quantitative Variables</a>
  <ul class="collapse">
  <li><a href="#layering-in-ggplot" id="toc-layering-in-ggplot" class="nav-link" data-scroll-target="#layering-in-ggplot">Layering in ggplot</a></li>
  <li><a href="#using-ggplot-command" id="toc-using-ggplot-command" class="nav-link" data-scroll-target="#using-ggplot-command">Using ggplot() command</a></li>
  <li><a href="#histograms" id="toc-histograms" class="nav-link" data-scroll-target="#histograms">Histograms</a></li>
  <li><a href="#density-plot" id="toc-density-plot" class="nav-link" data-scroll-target="#density-plot">Density Plot</a></li>
  <li><a href="#boxplot-and-outliers" id="toc-boxplot-and-outliers" class="nav-link" data-scroll-target="#boxplot-and-outliers">Boxplot and Outliers</a>
  <ul class="collapse">
  <li><a href="#what-is-an-outlier" id="toc-what-is-an-outlier" class="nav-link" data-scroll-target="#what-is-an-outlier">What is an outlier?</a></li>
  </ul></li>
  <li><a href="#boxplot-with-outliers-deliverytime" id="toc-boxplot-with-outliers-deliverytime" class="nav-link" data-scroll-target="#boxplot-with-outliers-deliverytime">Boxplot With Outliers: DeliveryTime</a></li>
  <li><a href="#boxplot-without-outliers-customervalue" id="toc-boxplot-without-outliers-customervalue" class="nav-link" data-scroll-target="#boxplot-without-outliers-customervalue">Boxplot Without Outliers: CustomerValue</a></li>
  <li><a href="#side-by-side-comparison" id="toc-side-by-side-comparison" class="nav-link" data-scroll-target="#side-by-side-comparison">Side-by-Side Comparison</a></li>
  <li><a href="#detecting-outliers-numerically-deliverytime" id="toc-detecting-outliers-numerically-deliverytime" class="nav-link" data-scroll-target="#detecting-outliers-numerically-deliverytime">Detecting Outliers Numerically: DeliveryTime</a></li>
  </ul></li>
  <li><a href="#summarizing-qualitative-data" id="toc-summarizing-qualitative-data" class="nav-link" data-scroll-target="#summarizing-qualitative-data">Summarizing Qualitative Data</a></li>
  <li><a href="#visualizing-qualitative-variables" id="toc-visualizing-qualitative-variables" class="nav-link" data-scroll-target="#visualizing-qualitative-variables">Visualizing Qualitative Variables</a>
  <ul class="collapse">
  <li><a href="#bar-graph" id="toc-bar-graph" class="nav-link" data-scroll-target="#bar-graph">Bar Graph</a>
  <ul class="collapse">
  <li><a href="#geom_bar" id="toc-geom_bar" class="nav-link" data-scroll-target="#geom_bar">geom_bar()</a></li>
  <li><a href="#pertinent-parameters-to-geom_bar" id="toc-pertinent-parameters-to-geom_bar" class="nav-link" data-scroll-target="#pertinent-parameters-to-geom_bar">Pertinent Parameters to geom_bar()</a></li>
  </ul></li>
  <li><a href="#pie-chart" id="toc-pie-chart" class="nav-link" data-scroll-target="#pie-chart">Pie Chart</a></li>
  </ul></li>
  <li><a href="#summary-and-review" id="toc-summary-and-review" class="nav-link" data-scroll-target="#summary-and-review">Summary and Review</a>
  <ul class="collapse">
  <li><a href="#using-ai" id="toc-using-ai" class="nav-link" data-scroll-target="#using-ai">Using AI</a></li>
  <li><a href="#quantitative-data-lab" id="toc-quantitative-data-lab" class="nav-link" data-scroll-target="#quantitative-data-lab">Quantitative Data Lab</a></li>
  <li><a href="#qualitative-data-lab" id="toc-qualitative-data-lab" class="nav-link" data-scroll-target="#qualitative-data-lab">Qualitative Data Lab</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Descriptive Statistics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This lesson covers how to summarize and visualize descriptive statistics for both quantitative and qualitative data in R. Descriptive statistics are the foundation of every analysis — before modeling, testing, or drawing conclusions, you must understand what your data looks like, where it centers, how spread out it is, and whether any unusual patterns or values are present.</p>
<p>We begin with <strong>summarizing quantitative data</strong>: measuring central tendency (mean, median, mode) and spread (standard deviation, variance, skewness, kurtosis, range, IQR). The choice of which measure to use is not arbitrary — skewed distributions and outliers make the mean unreliable, and the same data can tell very different stories depending on which statistics you report. We work through a salary example to make this concrete, then extend to a real customer dataset.</p>
<p>We then move to <strong>visualizing quantitative variables</strong>: histograms reveal distribution shape and connect directly to the skewness and kurtosis statistics; density plots provide a smoothed view of the same shape with a mean reference line; and boxplots summarize the five-number summary while flagging potential outliers as individual points. These three charts complement each other — the histogram shows the overall shape, the boxplot isolates the center and tails, and the density plot is best for comparing groups or overlaying a reference.</p>
<p>The second half of the lesson shifts to <strong>qualitative (categorical) data</strong>: calculating frequencies, proportions, and cumulative distributions using <code>table()</code>, <code>prop.table()</code>, and <code>cumsum()</code>, and visualizing results with bar charts and pie charts using <code>ggplot2</code>. Bar charts are the workhorse for categorical data; pie charts are available but harder to read accurately.</p>
<p>By the end of this lesson, you should be able to choose the appropriate measures of central tendency and spread for any quantitative variable, assess normality using skewness and kurtosis z-scores, identify and investigate outliers visually and numerically, construct frequency tables for categorical variables, and produce publication-quality charts using <code>ggplot2</code>. Work through every code example in your own R script alongside the reading.</p>
<section id="at-a-glance" class="level3">
<h3 class="anchored" data-anchor-id="at-a-glance">At a Glance</h3>
<ul>
<li>In order to succeed in this lesson, you need to understand that descriptive statistics serve one purpose: to summarize data honestly. That means choosing the right measure for the distribution in front of you — not just defaulting to the mean — and using visualizations to confirm what the numbers report. Pay close attention to the relationship between skewness, outliers, and the choice of mean versus median, and to how each chart type (histogram, density, boxplot, bar chart) reveals a different aspect of the data.</li>
</ul>
</section>
<section id="lesson-objectives" class="level3">
<h3 class="anchored" data-anchor-id="lesson-objectives">Lesson Objectives</h3>
<ul>
<li>Calculate and interpret mean, median, and mode for quantitative variables.</li>
<li>Identify when each measure of central tendency is appropriate based on distribution shape.</li>
<li>Calculate and interpret standard deviation, variance, range, and IQR.</li>
<li>Assess skewness and kurtosis using <code>skew()</code> and <code>kurtosis()</code> from <code>semTools</code> and interpret z-scores against sample-size thresholds.</li>
<li>Identify and compute outlier bounds using the 1.5 × IQR rule.</li>
<li>Produce and interpret histograms, density plots, and boxplots using <code>ggplot2</code>.</li>
<li>Calculate frequency tables, relative frequencies, and cumulative distributions for categorical variables.</li>
<li>Produce and interpret bar charts and pie charts using <code>ggplot2</code>.</li>
</ul>
</section>
<section id="consider-while-reading" class="level3">
<h3 class="anchored" data-anchor-id="consider-while-reading">Consider While Reading</h3>
<ul>
<li>As you work through this lesson, keep asking: <em>which summary is honest for this data?</em> The salary example at the start is designed to show how the mean can mislead when outliers are present — that instinct should carry through every variable you analyze.</li>
<li>The workflow throughout is intentionally sequential: compute central tendency first, then assess spread and shape, then visualize to confirm. The histograms and boxplots you build are not decorations — they are the check on whether the numbers you computed accurately describe the data.</li>
<li>When you reach the skewness and kurtosis section, pay attention to the sample-size thresholds for interpreting z-scores. The same z-value that is fine in a large sample may indicate a real problem in a small one.</li>
</ul>
<p>The goal of this lesson is to teach you how to summarize and visualize descriptive statistics for both quantitative and qualitative data in R. To do this well, we need to understand the difference between quantitative and qualitative data and examine data in context — context tells us how the data was collected and what it is meant to represent. In any analysis, it is critically important to understand your data before modeling or drawing conclusions.</p>
<p>For quantitative data, you should understand how to describe a variable’s center (mean, median, mode), visualize its shape with a histogram, density plot, or boxplot, and quantify its spread (variance, standard deviation, skewness, kurtosis, IQR). For qualitative data, you should know how to calculate frequencies, proportions, and cumulative distributions, and display results clearly using bar charts and pie charts.</p>
</section>
<section id="summarizing-quantitative-data" class="level1">
<h1>Summarizing Quantitative Data</h1>
<ul>
<li>Summarizing Quantitative Data is the process of reducing a large set of numbers down to a small set of meaningful values that describe what is typical, how spread out the data is, and what shape the distribution takes.</li>
<li>Rather than reporting every observation, we use statistics to tell the story of the data in a few key numbers.</li>
<li>Three questions every summary should answer:
<ul>
<li>What is typical? Central tendency — mean, median, mode</li>
<li>How spread out is it? Variability — standard deviation, IQR, range</li>
<li>What shape is it? Distribution — skewness, kurtosis, histograms</li>
</ul></li>
<li>Why this matters with AI in the picture: AI computes summaries. You decide which summary is honest, and you explain what it means.</li>
</ul>
<p>AI can generate all of these statistics instantly. What it cannot do is tell you which ones are appropriate for your data, or what the numbers mean in context. A mean wage of $42 means something very different depending on whether the data is symmetric or heavily skewed by a few executives. Choosing the right summary and interpreting it correctly is the analytical judgment this section is building.</p>
<section id="defining-and-calculating-central-tendency" class="level2">
<h2 class="anchored" data-anchor-id="defining-and-calculating-central-tendency">Defining and Calculating Central Tendency</h2>
<ul>
<li>We will cover four measures in this section:
<ul>
<li>Mean: Data is symmetric, no extreme outliers</li>
<li>Median: Data is skewed or outliers are present</li>
<li>Mode: Data is categorical, or you need the most common value</li>
<li>Percentile: You need to describe relative position within the data</li>
</ul></li>
</ul>
<section id="using-the-mean" class="level3">
<h3 class="anchored" data-anchor-id="using-the-mean">Using the Mean</h3>
<ul>
<li><p>The mean() function in R is a versatile tool for calculating the arithmetic average of a numeric vector. The arithmetic mean or simply the mean is a primary measure of central location. It is often referred to as the average.</p></li>
<li><p>The sample mean <span class="math inline">\(\bar{x}\)</span> is the sum of all values divided by the number of observations <span class="math inline">\(n\)</span>.</p></li>
<li><p><span class="math display">\[\bar{x} = \frac{\sum_{i=1}^{n} x_{i}}{n}\]</span></p></li>
<li><p>Consider the salaries of employees at a company: <img src="Pictures/Ch2/Salaries.png" title="Salary Data" class="img-fluid" alt="Salary Data"></p></li>
<li><p>We can use the mean() command to calculate the mean in R.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Vector of Salaries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>salaries <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40000</span>, <span class="dv">40000</span>, <span class="dv">65000</span>, <span class="dv">90000</span>, <span class="dv">145000</span>, <span class="dv">150000</span>, <span class="dv">550000</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean using the mean() command</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154285.7</code></pre>
</div>
</div>
<ul>
<li>Note that due to at least one <em>outlier</em> this mean does not reflect the typical salary - more on that later.</li>
<li>If we edit our vector to include NAs, we have to account for this. This is a common way to handle NAs in functions that do not allow for them.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>salaries2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40000</span>, <span class="dv">40000</span>, <span class="dv">65000</span>, <span class="dv">90000</span>, <span class="dv">145000</span>, <span class="dv">150000</span>, <span class="dv">550000</span>, <span class="cn">NA</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="cn">NA</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice that it does not work without na.rm</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(salaries2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add in na.rm parameter to get it to produce the mean with no NAs.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(salaries2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154285.7</code></pre>
</div>
</div>
<ul>
<li>Note that there are other types of means like the weighted mean or the geometric mean.</li>
<li>The weighted mean uses weights to determine the importance of each data point of a variable. It is calculated by <span class="math inline">\(\bar{x}_w = \frac{\sum_{i=1}^{n} w_i x_i}{\sum_{i=1}^{n} w_i}\)</span>, where <span class="math inline">\(w_i\)</span> are the weights associated to the values.</li>
<li>An example is below.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>weights <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>weighted_mean <span class="ot">&lt;-</span> <span class="fu">weighted.mean</span>(values, weights)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>weighted_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.533333</code></pre>
</div>
</div>
</section>
<section id="using-the-median" class="level3">
<h3 class="anchored" data-anchor-id="using-the-median">Using the Median</h3>
<ul>
<li>The median is another measure of central location that is not affected by outliers.</li>
<li>When the data are arranged in ascending order, the median is:
<ul>
<li>The middle value if the number of observations is odd, or</li>
<li>The average of the two middle values if the number of observations is even.</li>
</ul></li>
<li>Consider the sorted salaries of employees presented earlier which contains an odd number of observations.</li>
<li>On the same salaries vector created above, use median() command to calculate the median in R.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the median using the median() command</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 90000</code></pre>
</div>
</div>
<ul>
<li>Now compare to the mean and note the large difference in numbers signifying that at least one outlier is most likely present.</li>
<li>Specifically, if the mean and median are different, it is likely the variable is skewed and contains outliers.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154285.7</code></pre>
</div>
</div>
<ul>
<li>For another example, consider the sorted data below that contains an even number of values.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>GrowthFund <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">38.32</span>, <span class="fl">1.71</span>, <span class="fl">3.17</span>, <span class="fl">5.99</span>, <span class="fl">12.56</span>, <span class="fl">13.47</span>, <span class="fl">16.89</span>, <span class="fl">16.96</span>, <span class="fl">32.16</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fl">36.29</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>When data contains an even number of values, the median is the average of the 2 sorted middle numbers (12.56 and 13.47).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(GrowthFund)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.015</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">12.56</span> <span class="sc">+</span> <span class="fl">13.47</span>)<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.015</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The mean is still the average</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(GrowthFund)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.088</code></pre>
</div>
</div>
</section>
<section id="using-the-mode" class="level3">
<h3 class="anchored" data-anchor-id="using-the-mode">Using the Mode</h3>
<ul>
<li>The mode is another measure of central location.</li>
<li>The mode is the most frequently occurring value in a data set.</li>
<li>The mode is useful in summarizing categorical data but can also be used to summarize quantitative data.</li>
<li>A data set can have no mode, one mode (unimodal), two modes (bimodal) or many modes (multimodal).</li>
<li>The mode is less useful when there are more than three modes.</li>
</ul>
</section>
<section id="example-of-function-with-salary-variable" class="level3">
<h3 class="anchored" data-anchor-id="example-of-function-with-salary-variable">Example of Function with Salary Variable</h3>
<ul>
<li><p>While this is a small vector, when working with a large dataset and a function like sort(x = table(salaries), decreasing = TRUE), appending [1:5] is a way to focus on the top results after the frequencies have been computed and sorted. Specifically, table(salaries) calculates the frequency of each unique salary, sort(…, decreasing = TRUE) orders these frequencies from highest to lowest, and [1:5] selects the first five entries in the sorted list. This is useful when the dataset contains many unique values, as it allows you to quickly identify and extract the top 5 most frequent salaries, providing a concise summary without being overwhelmed by the full distribution.</p></li>
<li><p>Consider the salary of employees presented earlier. 40,000 appears 2 times and is the mode because that occurs most often.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this command with and without it.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="at">x =</span> <span class="fu">table</span>(salaries), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>salaries
 40000  65000  90000 145000 150000 
     2      1      1      1      1 </code></pre>
</div>
</div>
</section>
<section id="finding-no-mode" class="level3">
<h3 class="anchored" data-anchor-id="finding-no-mode">Finding No Mode</h3>
<ul>
<li>Look at the sort(table()) commands with the GrowthFund Vector we made earlier.</li>
<li>I added a 1:5 in square brackets at the end of the statement to produce the 3 highest frequencies found in the vector.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(GrowthFund), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GrowthFund
-38.32   1.71   3.17   5.99  12.56 
     1      1      1      1      1 </code></pre>
</div>
</div>
<ul>
<li>Even if you use this command, you still need to evaluate the data more systematically to verify the mode. If the highest frequency of the sorted table is 1, then there is no mode.</li>
</ul>
</section>
</section>
<section id="defining-and-calculating-spread" class="level2">
<h2 class="anchored" data-anchor-id="defining-and-calculating-spread">Defining and Calculating Spread</h2>
<ul>
<li>Spread is a measure of distance values are from the central value.</li>
<li>Each measure of central tendency has one or more corresponding measures of spread.</li>
<li>Mean: use variance or standard deviation to measure spread.</li>
<li>skewness and kurtosis help measure spread as well.</li>
<li>Median: use range or interquartile range (IQR) to measure spread.</li>
<li>Mode: use the index of qualitative variation to measure spread.</li>
<li>Not formally testing here with a function.</li>
</ul>
<section id="spread-to-report-with-the-mean" class="level3">
<h3 class="anchored" data-anchor-id="spread-to-report-with-the-mean">Spread to Report with the Mean</h3>
<section id="evaluating-skewness" class="level4">
<h4 class="anchored" data-anchor-id="evaluating-skewness">Evaluating Skewness</h4>
<ul>
<li>Skewness is a measure of the extent to which a distribution is skewed.</li>
<li>Can evaluate skewness visually with histogram.</li>
<li>A histogram is a visual representation of a frequency or a relative frequency distribution.</li>
<li>Bar height represents the respective class frequency (or relative frequency).</li>
<li>Bar width represents the class width.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch2/Skewness.png" title="Evaluating Skewness Visually" class="img-fluid figure-img"></p>
<figcaption>Evaluating Skewness Visually</figcaption>
</figure>
</div>
</section>
<section id="skewed-distributions-median-not-same-as-mean" class="level4">
<h4 class="anchored" data-anchor-id="skewed-distributions-median-not-same-as-mean">Skewed Distributions: Median Not Same as Mean</h4>
<ul>
<li>Sometimes, a histogram is difficult to tell if skewness is present or if the data is relatively normal or symmetric.</li>
<li>If Mean is less than Median and Mode, then the variable is Left-Skewed.</li>
<li>If the Mean is greater than the Median and Mode, then the variable is Right-Skewed.</li>
<li>If the Mean is about equal to the Median and Mode, then the variable has a symmetric distribution.</li>
<li>In R, we can easily look at mean and median with the summary() command.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch2/SkewMeanMedian.png" title="Evaluating Skewness Using Mean and Median" class="img-fluid figure-img"></p>
<figcaption>Evaluating Skewness Using Mean and Median</figcaption>
</figure>
</div>
<ul>
<li>Mean is great when data are normally distributed (data is not skewed).</li>
<li>Mean is not a good representation of skewed data where outliers are present.</li>
<li>Adding together a set of values that includes a few very large or very small values like those on the far left of a left-skewed distribution or the far right of the right-skewed distribution will result in a large or small total value in the numerator of Equation and therefore the mean will be a large or small value relative to the actual middle of the data.</li>
<li>There are a number of ways to check for skewness. The skewness() function from the e1071 package and the skew() function from the semTools package both measure skewness, but they differ slightly in how they scale the result.</li>
<li>By default, e1071::skewness() uses a sample-based formula (dividing by <span class="math inline">\(n\)</span>). In contrast, semTools::skew() uses Mardia’s definition and is more commonly applied in structural equation modeling contexts.</li>
<li>As a result, the values may differ slightly, especially for small samples or skewed distributions. Both are valid but should be used consistently depending on the analytical context.</li>
</ul>
</section>
<section id="using-skewness-command-from-e1071" class="level4">
<h4 class="anchored" data-anchor-id="using-skewness-command-from-e1071">Using skewness command from e1071</h4>
<ul>
<li>A standard calculation of skewness using the mean is based on the third standardized moment of a distribution. The formula is:</li>
</ul>
<p><span class="math display">\[\text{Skewness} = \frac{1}{n} \sum_{i=1}^{n} \left( \frac{x_i - \bar{x}}{s} \right)^3\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> = each observation</li>
<li><span class="math inline">\(\bar{x}\)</span> = sample mean</li>
<li><span class="math inline">\(s\)</span> = sample standard deviation</li>
<li><span class="math inline">\(n\)</span> = sample size</li>
<li>This formula measures the asymmetry of the distribution:
<ul>
<li>Positive skew (right-skewed): longer tail on the right</li>
<li>Negative skew (left-skewed): longer tail on the left</li>
<li>Zero skew: symmetric distribution</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>e1071<span class="sc">::</span><span class="fu">skewness</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.415062</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## a positive number indicates a longer tail to the right.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-skew-command-from-semtools" class="level4">
<h4 class="anchored" data-anchor-id="using-skew-command-from-semtools">Using skew() Command from semTools</h4>
<ul>
<li>We will use the skew() command from the semTools package.</li>
<li>The install.packages() command is commented out below, but install it one time on your R before commenting it out.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('semTools') # run once, then comment out</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(semTools) # already loaded in setup chunk</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>After the package is installed and loaded, run the skew() command on the salaries vector made above.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
    2.311     0.926     2.496     0.013 </code></pre>
</div>
</div>
</section>
<section id="interpreting-the-skew-command-results" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-skew-command-results">Interpreting the skew() Command Results</h4>
<ul>
<li>se = standard error</li>
<li>z = skew/se</li>
<li>If the sample size is small (n &lt; 50), z values outside the –2 to 2 range are a problem.</li>
<li>If the sample size is between 50 and 300, z values outside the –3.29 to 3.29 range are a problem.</li>
<li>For large samples (n &gt; 300), using a visual is recommended over the statistics, but generally z values outside the range of –7 to 7 can be considered problematic.</li>
<li>Salary: Our sample size was small, &lt;50, so the z value of 2.496 in regards to the salary vector indicates there is a problem with skewness.</li>
<li>GrowthFund: We can check the skew of GrowthFund.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(GrowthFund)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
   -1.381     0.775    -1.783     0.075 </code></pre>
</div>
</div>
<ul>
<li>GrowthFund was also considered a small sample size, so the same -2/2 thresholds are used. Here, our z value is -1.78250137, which is in normal range. This indicates there is no problem with skewness.</li>
</ul>
</section>
<section id="kurtosis-in-evaluating-mean-spread" class="level4">
<h4 class="anchored" data-anchor-id="kurtosis-in-evaluating-mean-spread">Kurtosis in Evaluating Mean Spread</h4>
<ul>
<li><p>Kurtosis is the sharpness of the peak of a frequency-distribution curve or more formally a measure of how many observations are in the tails of a distribution.</p></li>
<li><p>The formula for kurtosis is as follows:</p></li>
</ul>
<p><span class="math display">\[\text{Kurtosis} = \frac{n(n+1)}{(n-1)(n-2)(n-3)} \sum \left( \frac{(X_i - \bar{X})^4}{s^4} \right) - \frac{3(n-1)^2}{(n-2)(n-3)}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(n\)</span> is the sample size</li>
<li><span class="math inline">\(X_i\)</span> is each individual value</li>
<li><span class="math inline">\(\bar{X}\)</span> is the mean of the data</li>
<li><span class="math inline">\(s\)</span> is the standard deviation</li>
<li>A normal distribution will have a kurtosis value of three, where distributions with kurtosis around 3 are described as mesokurtic, significantly higher than 3 indicate leptokurtic, and significantly under 3 indicate platykurtic.</li>
<li>The kurtosis() command from the semTools package subtracts 3 from the kurtosis, so we can evaluate values by comparing them to 0. Positive values will be indicative to a leptokurtic distribution and negative will indicate a platykurtic distribution. To see if kurtosis (leptokurtic or platykurtic) is significant, we confirm them by first evaluating the z-score to see if the variable is normal or not. The same cutoff values from skew also apply for the z for small, medium, and large sample sizes in kurtosis.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch2/Kurtosis.png" title="Evaluate Kurtosis" class="img-fluid figure-img"></p>
<figcaption>Evaluate Kurtosis</figcaption>
</figure>
</div>
<ul>
<li>The rules of determining problematic distributions with regards to kurtosis are below.
<ul>
<li>If the sample size is small (n &lt; 50), z values outside the –2 to 2 range are a problem.</li>
<li>If the sample size is between 50 and 300, z values outside the –3.29 to 3.29 range are a problem.</li>
<li>For large samples (n &gt; 300), using a visual is recommended over the statistics, but generally z values outside the range of –7 to 7 can be considered problematic.</li>
<li>If kurtosis is found, then evaluate the excess kur score to see if it is positive or negative to determine whether it is leptokurtic or platykurtic.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># z-value is 3.0398, which is &gt; 2 indicating leptokurtic Small sample</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># size: range is -2 to 2</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(salaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
          5.629           1.852           3.040           0.002 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># z-value is 2.20528007, which is &gt; 2 indicating leptokurtic Small</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sample size: range is -2 to 2</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(GrowthFund)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
          3.416           1.549           2.205           0.027 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="examples-from-the-customer-dataset" class="level2">
<h2 class="anchored" data-anchor-id="examples-from-the-customer-dataset">Examples from the Customer Dataset</h2>
<p>Load the customers.csv dataset as customers. It contains 10 variables: CustID, Sex, Race, BirthDate, College, HHSize, Income, Spending, Orders, and Channel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>customers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/customers.csv"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Noted sample size at 200 observations or a medium sample size.</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Using threshold –3.29 to 3.29 to assess normality.</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># -3.4245446445 is below -3.29 so kurtosis is present Negative</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># kurtosis value indicates platykurtic</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(customers<span class="sc">$</span>Spending)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
         -1.186           0.346          -3.425           0.001 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(customers, <span class="fu">aes</span>(Spending)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">100</span>, <span class="at">fill =</span> <span class="st">"pink"</span>,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>semTools<span class="sc">::</span><span class="fu">skew</span>(customers<span class="sc">$</span>Spending)  <span class="do">## normal indicating no skewness</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
   -0.018     0.173    -0.106     0.916 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normal: 2.977622119 is in between -3.29 and 3.29</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(customers<span class="sc">$</span>Income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
          1.031           0.346           2.978           0.003 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(customers, <span class="fu">aes</span>(Income)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10000</span>, <span class="at">fill =</span> <span class="st">"pink"</span>,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>semTools<span class="sc">::</span><span class="fu">skew</span>(customers<span class="sc">$</span>Income)  <span class="co"># Skewed right</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
    0.874     0.173     5.047     0.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -3.7251961028 is below -3.29 so kurtosis is present Negative</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># kurtosis value indicates platykurtic</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(customers<span class="sc">$</span>HHSize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
         -1.290           0.346          -3.725           0.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(customers, <span class="fu">aes</span>(HHSize)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"pink"</span>,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>semTools<span class="sc">::</span><span class="fu">skew</span>(customers<span class="sc">$</span>HHSize)  <span class="co"># normal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
   -0.089     0.173    -0.513     0.608 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normal: -0.20056607 is in between -3.29 and 3.29</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(customers<span class="sc">$</span>Orders)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Excess Kur (g2)              se               z               p 
         -0.069           0.346          -0.201           0.841 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(customers, <span class="fu">aes</span>(Orders)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"pink"</span>,</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>semTools<span class="sc">::</span><span class="fu">skew</span>(customers<span class="sc">$</span>Orders)  <span class="do">## skewed right</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
    0.789     0.173     4.553     0.000 </code></pre>
</div>
</div>
<section id="spread-to-report-with-the-median" class="level3">
<h3 class="anchored" data-anchor-id="spread-to-report-with-the-median">Spread to Report with the Median</h3>
<ul>
<li>Range = Maximum Value – Minimum Value.
<ul>
<li>Simplest measure.</li>
<li>Focuses on Extreme values.</li>
<li>Use commands diff(range()) or max() – min().</li>
</ul></li>
<li>IQR: Difference between the first and third quartiles.
<ul>
<li>Use IQR() command or quantile() command.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(customers<span class="sc">$</span>Spending, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   50.0   383.8   662.0   659.6   962.2  1250.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(customers<span class="sc">$</span>Spending, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(customers<span class="sc">$</span>Spending, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">min</span>(customers<span class="sc">$</span>Spending, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(customers<span class="sc">$</span>Spending, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 578.5</code></pre>
</div>
</div>
</section>
<section id="spread-to-report-with-the-mode" class="level3">
<h3 class="anchored" data-anchor-id="spread-to-report-with-the-mode">Spread to Report with the Mode</h3>
<ul>
<li>While there is no great function to test for spread, you can look at the data and see if it is concentrated around 1 or 2 frequencies. If it is, then the spread is distorted towards those high frequency values.</li>
</ul>
<hr>
<p>With central tendency and spread established numerically, the next step is to confirm what those numbers are telling you visually. Histograms, density plots, and boxplots each reveal a different aspect of the distribution — and together they should be consistent with the skewness and kurtosis statistics computed above.</p>
</section>
</section>
</section>
<section id="visualizing-quantitative-variables" class="level1">
<h1>Visualizing Quantitative Variables</h1>
<p>The examples in this section use the <code>descriptives.csv</code> dataset. Load it now so it is available for all charts below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>descriptive_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/descriptives.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Graphs for a Single Continuous Variable. A continuous variable refers to a variable that can take any value over a range of values.</p>
<p>A continuous variable needs to be numeric, and could be integer type or numeric type in R. Just like with graphs that include categorical variables, it is beneficial to do any data cleaning and investigation into the variable(s) before you begin.</p>
<p>This may require recoding the variable to coerce it to the appropriate data type and/or renaming it to something meaningful if needed.</p>
<p>It is also beneficial to make sure the numerical variable is indeed supposed to be numerical (as opposed to a factor). For instance, you commonly see numbers listed for categories like the Yes/No coded as a 1/2.</p>
<p>With central tendency, the next step is to visualize the distribution. The three charts below — histogram, density plot, and boxplot — each reveal a different aspect of a numeric variable’s shape, and they connect directly to the skewness and kurtosis statistics above.</p>
<ul>
<li>We will see the following:
<ul>
<li>Histograms</li>
<li>Density Plots</li>
<li>Boxplots</li>
</ul></li>
</ul>
<section id="layering-in-ggplot" class="level2">
<h2 class="anchored" data-anchor-id="layering-in-ggplot">Layering in ggplot</h2>
<ul>
<li>Layering is a fundamental concept in ggplot2 that allows you to build complex visualizations by adding different components (or “layers”) on top of each other. Each layer can represent different types of data, aesthetics, or annotations.</li>
<li>Benefits of Layering:
<ul>
<li>Separation of Plot Components: Each layer can handle a different part of the plot.</li>
<li>Customization and Enhancement: By adding multiple layers, you can customize labels, colors, annotations, and theme elements independently.</li>
<li>Modularity: Layering makes it easier to add, remove, or modify parts of the plot without changing the entire structure.</li>
<li>Combining Data Sources: Different layers can use different datasets or aesthetics, which is useful when you need to overlay one dataset on top of another.</li>
</ul></li>
</ul>
</section>
<section id="using-ggplot-command" class="level2">
<h2 class="anchored" data-anchor-id="using-ggplot-command">Using ggplot() command</h2>
<p>A histogram displays the distribution of a <strong>continuous (numeric) variable</strong> by grouping values into bins and counting how many observations fall in each bin. It is the best first chart to make when you want to understand the shape, center, and spread of a numeric variable.</p>
<p>Layering means building the histogram step by step: <code>ggplot()</code> and <code>aes()</code> set up the canvas and map the variable to the x-axis, <code>geom_histogram()</code> adds the bars, and <code>labs()</code> applies the title and axis labels — each <code>+</code> adds a new layer on top of the last.</p>
<p>Inside aes(), writing x = Spending and Spending are equivalent — ggplot2 assumes the first unnamed argument maps to the x-axis, so both forms produce the same plot. Using x = makes the mapping more explicit and is easier to read, especially once you start adding y =, fill =, and other aesthetics alongside it.</p>
</section>
<section id="histograms" class="level2">
<h2 class="anchored" data-anchor-id="histograms">Histograms</h2>
<ul>
<li>A histogram is a graphical representation of the distribution of numerical data.</li>
<li>It consists of a series of contiguous rectangles, or bars, where the area of each bar corresponds to the frequency of observations within a particular range or bin of values.</li>
<li>The x-axis typically represents the range of values being measured, while the y-axis represents the frequency or count of observations falling within each range.</li>
<li>Histograms are commonly used in statistics and data analysis to visualize the distribution of a dataset and identify patterns or trends.</li>
<li>They are particularly useful for understanding the central tendency, variability, and shape of the data distribution - this includes our observation of skewness.</li>
<li>Works much better with larger datasets.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The simplest way to draw a histogram in base R is hist(). For a</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># quick look at CustomerValue:</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(descriptive_data<span class="sc">$</span>CustomerValue, <span class="at">main =</span> <span class="st">"Customer Value Distribution"</span>,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlab =</span> <span class="st">"Customer Value"</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>geom_histogram()</code> from ggplot2 gives more control. The key parameter is <code>binwidth</code> — experiment to find a width that shows the shape without too much noise:</p>
<ul>
<li><code>binwidth =</code> controls bar width. Too narrow produces noise; too wide hides the shape.</li>
<li>A roughly symmetric histogram suggests normality. A long tail to the right indicates right skew.</li>
<li>These histograms connect directly to the skewness statistics above — the chart lets you <em>see</em> what those numbers measure.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> CustomerValue)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">15</span>,</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Customer Value"</span>,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Customer Value"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A right-skewed example shows what a problematic distribution looks like visually — compare to <code>DeliveryTime</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> DeliveryTime)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">25</span>,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"tomato"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Delivery Time"</span>,</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Delivery Time (days)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(descriptive_data<span class="sc">$</span>DeliveryTime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>skew (g1)        se         z         p 
    2.378     0.173    13.728     0.000 </code></pre>
</div>
</div>
</section>
<section id="density-plot" class="level2">
<h2 class="anchored" data-anchor-id="density-plot">Density Plot</h2>
<p>A density plot is a smoothed version of a histogram. Instead of bins, it draws a continuous curve that represents the estimated distribution of the variable. It is particularly useful for comparing the shape of distributions or overlaying multiple groups.</p>
<p>Layering means <code>ggplot()</code> and <code>aes()</code> set up the canvas and map the variable to the x-axis, <code>geom_density()</code> draws the smoothed curve, <code>geom_vline()</code> overlays a dashed vertical line at the mean, and <code>labs()</code> adds the title and axis labels.</p>
<p>The area under the curve represents the probability of values falling within a given range. Useful parameters include <code>color =</code> for the line color, <code>fill =</code> to color the area under the curve, and <code>alpha =</code> to set transparency (0 = invisible, 1 = solid).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(x)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(x)), <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" alt="Density Chart with Mean Line Generated by R" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Working with a real dataset uses the same approach — pass the variable directly into <code>aes()</code>. Here we use <code>CustomerValue</code> from the <code>descriptives.csv</code> dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> CustomerValue)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"lavender"</span>,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"purple"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(CustomerValue,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Customer Value"</span>,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Customer Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><code>alpha =</code> sets transparency (0 = invisible, 1 = solid). A value around 0.5–0.6 is typical.</li>
<li>The dashed vertical line marks the mean, making it easy to see whether the distribution is symmetric around it or pulled to one side.</li>
<li>If the curve has a longer tail to the right and the mean sits to the right of the peak, the variable is right-skewed.</li>
</ul>
</section>
<section id="boxplot-and-outliers" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-and-outliers">Boxplot and Outliers</h2>
<p>A boxplot summarizes the <strong>distribution</strong> of a continuous variable visually using five key values: the minimum, first quartile (Q1), median, third quartile (Q3), and maximum. It also flags potential outliers as individual points beyond the whiskers.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch3/Boxplot.png" title="A Boxplot Diagram" class="img-fluid figure-img"></p>
<figcaption>A Boxplot with Outliers</figcaption>
</figure>
</div>
<p>The five values displayed in a boxplot are:</p>
<ul>
<li><strong>Median (Q2)</strong>: the line inside the box — the middle value.</li>
<li><strong>Q1</strong>: the left/bottom edge of the box — 25th percentile.</li>
<li><strong>Q3</strong>: the right/top edge of the box — 75th percentile.</li>
<li><strong>IQR</strong>: the width of the box (Q3 − Q1) — the middle 50% of the data.</li>
<li><strong>Whiskers</strong>: extend to 1.5 × IQR beyond Q1 and Q3.</li>
<li><strong>Outliers</strong>: any point beyond the whiskers is plotted individually as a dot.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>GrowthFund <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">38.32</span>, <span class="fl">1.71</span>, <span class="fl">3.17</span>, <span class="fl">5.99</span>, <span class="fl">12.56</span>, <span class="fl">13.47</span>, <span class="fl">16.89</span>, <span class="fl">16.96</span>, <span class="fl">32.16</span>,</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>    <span class="fl">36.29</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>GrowthFund <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(GrowthFund)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The <code>quantile()</code> function returns the five-point summary. The 25th percentile is Q1 and the 75th percentile is Q3.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>QuanData <span class="ot">&lt;-</span> <span class="fu">quantile</span>(GrowthFund<span class="sc">$</span>GrowthFund)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>QuanData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      0%      25%      50%      75%     100% 
-38.3200   3.8750  13.0150  16.9425  36.2900 </code></pre>
</div>
</div>
<section id="what-is-an-outlier" class="level3">
<h3 class="anchored" data-anchor-id="what-is-an-outlier">What is an outlier?</h3>
<p>An outlier is an observation that falls unusually far from the rest of the data. What counts as “unusually far” depends on the method being used — there is no single universal definition. In a boxplot, a value is flagged as an outlier if it falls more than 1.5 × IQR below Q1 or above Q3.</p>
<p>Other methods use different thresholds: Z-scores flag values beyond ±2 or ±3 standard deviations from the mean, and some statistical tests apply their own cutoffs entirely. This means the same data point could be considered an outlier by one method but not another, so the choice of method matters.</p>
<p>Regardless of how they are identified, outliers are not automatically errors — they may be legitimate extreme values, data entry mistakes, or observations from a different population — and they should always be investigated before deciding whether to keep or remove them.</p>
</section>
</section>
<section id="boxplot-with-outliers-deliverytime" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-with-outliers-deliverytime">Boxplot With Outliers: DeliveryTime</h2>
<p><code>DeliveryTime</code> contains several unusually large values — deliveries that took far longer than the typical customer experience. These show up as individual points beyond the right whisker.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> DeliveryTime)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightcoral"</span>,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Delivery Time (Outliers Present)"</span>,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Delivery Time (minutes)"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/boxplot-with-outliers-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(descriptive_data<span class="sc">$</span>DeliveryTime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  41.42   92.12  103.45  106.87  116.16  273.88 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.03</code></pre>
</div>
</div>
<p>Notice that the mean will be pulled to the right by those extreme values — this is exactly when the <strong>median</strong> is the better measure of central tendency. The bulk of deliveries cluster between roughly 75 and 130 minutes, but a handful of extreme delays are distorting the picture.</p>
<hr>
</section>
<section id="boxplot-without-outliers-customervalue" class="level2">
<h2 class="anchored" data-anchor-id="boxplot-without-outliers-customervalue">Boxplot Without Outliers: CustomerValue</h2>
<p><code>CustomerValue</code> tells a different story — values are spread relatively evenly with no individual points plotted beyond the whiskers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> CustomerValue)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"navy"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Customer Value (No Outliers)"</span>,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Customer Value Score"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/boxplot-no-outliers-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(descriptive_data<span class="sc">$</span>CustomerValue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  40.00   79.00   94.00   96.62  114.00  150.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>CustomerValue, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35</code></pre>
</div>
</div>
<p>Here the median line sits near the center of the box, the whiskers are roughly equal in length, and no individual points appear beyond them. This is the signature of a roughly symmetric distribution with no extreme values — a case where the <strong>mean</strong> is a reliable summary.</p>
<hr>
</section>
<section id="side-by-side-comparison" class="level2">
<h2 class="anchored" data-anchor-id="side-by-side-comparison">Side-by-Side Comparison</h2>
<p>Placing both variables together makes the contrast immediate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>descriptive_long <span class="ot">&lt;-</span> descriptive_data <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(DeliveryTime, CustomerValue) <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">fill =</span> Variable)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"gray30"</span>,</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Variable, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">DeliveryTime =</span> <span class="st">"lightcoral"</span>,</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">CustomerValue =</span> <span class="st">"lightblue"</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"With Outliers (DeliveryTime) vs. Without (CustomerValue)"</span>,</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Value"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/side-by-side-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="detecting-outliers-numerically-deliverytime" class="level2">
<h2 class="anchored" data-anchor-id="detecting-outliers-numerically-deliverytime">Detecting Outliers Numerically: DeliveryTime</h2>
<p>We can confirm what the boxplot shows by computing the bounds directly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>Q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="fl">0.25</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>Q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="fl">0.75</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>IQRvalue <span class="ot">&lt;-</span> <span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>OutlierValue <span class="ot">&lt;-</span> IQRvalue <span class="sc">*</span> <span class="fl">1.5</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>LowerBound <span class="ot">&lt;-</span> Q1 <span class="sc">-</span> OutlierValue</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>LowerBound</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  25% 
56.08 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>UpperBound <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> OutlierValue</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>UpperBound</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  75% 
152.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Will learn about filter, select, arrange in data prep.  The key</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="co"># operator here is | meaning OR — a delivery time is flagged if it is</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="co"># either suspiciously short (below the lower bound) or suspiciously</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># long (above the upper bound). Both ends of the distribution are</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="co"># checked in a single filter.</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> descriptive_data <span class="sc">%&gt;%</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(DeliveryTime <span class="sc">&lt;</span> LowerBound <span class="sc">|</span> DeliveryTime <span class="sc">&gt;</span> UpperBound) <span class="sc">%&gt;%</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(DeliveryTime) <span class="sc">%&gt;%</span></span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(DeliveryTime))</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>outliers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   DeliveryTime
1        273.88
2        272.24
3        226.92
4        201.86
5        196.79
6        186.61
7        179.22
8        164.97
9        160.14
10       158.99
11        41.42</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\text{Lower bound} = Q1 - 1.5 \times IQR\)</span></li>
<li><span class="math inline">\(\text{Upper bound} = Q3 + 1.5 \times IQR\)</span></li>
<li>Any value outside these bounds is flagged as an outlier.</li>
</ul>
<p>The outliers identified here are the same points visible as individual dots in the boxplot above — the numeric method and the visual method agree. Remember: being flagged as an outlier does not mean the value is wrong. Each one should be investigated before deciding whether to keep or remove it.</p>
<hr>
<p>Quantitative variables have now been fully described and visualized. We now turn to qualitative (categorical) variables. The tools change — frequencies and proportions replace means and standard deviations — but the goal is the same: describe what is typical and how concentrated or spread out the data is across categories.</p>
</section>
</section>
<section id="summarizing-qualitative-data" class="level1">
<h1>Summarizing Qualitative Data</h1>
<ul>
<li>Qualitative data is information that cannot be easily counted, measured, or easily expressed using numbers.
<ul>
<li>Nominal variables: a type of categorical variable that represents discrete categories or groups with no inherent order or ranking
<ul>
<li>gender (male, female)</li>
<li>marital status (single, married, divorced)</li>
<li>eye color (blue, brown, green)</li>
</ul></li>
<li>Ordinal variables: categories possess a natural order or ranking
<ul>
<li>a Likert scale measuring agreement with a statement (e.g., strongly disagree, disagree, neutral, agree, strongly agree)</li>
</ul></li>
</ul></li>
<li>A frequency distribution shows the number of observations in each category for a factor or categorical variable.</li>
<li>Guidelines when constructing frequency distribution:
<ul>
<li>Classes or categories are mutually exclusive (they are all unique).</li>
<li>Classes or categories are exhaustive (a full list of categories).</li>
</ul></li>
<li>To calculate frequencies, first, start with a variable that has categorical data.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector with some data that could be categorical</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>Sample_Vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"A"</span>, <span class="st">"C"</span>, <span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"A"</span>, <span class="st">"C"</span>, <span class="st">"A"</span>, <span class="st">"B"</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with the vector</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>data_example <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Sample_Vector)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>To count the number of each category value, we can use the table() command.</li>
<li>The output shows a top row of categories and a bottom row that contains the number of observations in the category.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of frequencies</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>frequencies <span class="ot">&lt;-</span> <span class="fu">table</span>(data_example<span class="sc">$</span>Sample_Vector)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>frequencies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
A B C 
5 3 2 </code></pre>
</div>
</div>
<ul>
<li>Relative frequency is how often something happens divided by all outcomes.</li>
<li>The relative frequency is calculated by <span class="math inline">\(f_i/n\)</span>, where <span class="math inline">\(f_i\)</span> is the frequency of class <span class="math inline">\(i\)</span> and <span class="math inline">\(n\)</span> is the total frequency.</li>
<li>We can use the prop.table() command to calculate relative frequency by dividing each category’s frequency by the sample size.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate proportions</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>proportions <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(frequencies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The cumulative relative frequency is given by <span class="math inline">\(cf_i/n\)</span>, where <span class="math inline">\(cf_i\)</span> is the cumulative frequency of class <span class="math inline">\(i\)</span>.</li>
<li>The cumsum() function calculates the cumulative distribution of the data.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative frequencies</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>cumulfreq <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frequencies)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative proportions</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>cumulproportions <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">prop.table</span>(frequencies))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The rbind() function is used to combine multiple data frames or matrices by row. The name “rbind” stands for “row bind”. Since the data produced by the table is in rows, we can use rbind to link them together.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into table</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>frequency_table <span class="ot">&lt;-</span> <span class="fu">rbind</span>(frequencies, proportions, cumulfreq, cumulproportions)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the table</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>frequency_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   A   B    C
frequencies      5.0 3.0  2.0
proportions      0.5 0.3  0.2
cumulfreq        5.0 8.0 10.0
cumulproportions 0.5 0.8  1.0</code></pre>
</div>
</div>
<ul>
<li>We can transpose a table using the t() command, which flips the dataset.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>TransposedData <span class="ot">&lt;-</span> <span class="fu">t</span>(frequency_table)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>TransposedData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  frequencies proportions cumulfreq cumulproportions
A           5         0.5         5              0.5
B           3         0.3         8              0.8
C           2         0.2        10              1.0</code></pre>
</div>
</div>
<ul>
<li>Finally, sometimes we need to transform our calculations into a dataset.</li>
<li>The as.data.frame function is used to coerce or convert an object into a data frame.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>TransposedData <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(TransposedData)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>TransposedData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  frequencies proportions cumulfreq cumulproportions
A           5         0.5         5              0.5
B           3         0.3         8              0.8
C           2         0.2        10              1.0</code></pre>
</div>
</div>
<hr>
<p>With frequency tables established, the natural next step is to display categorical distributions visually. Bar charts and pie charts serve the same purpose for categorical variables that histograms do for continuous ones — making the shape of the distribution immediately readable.</p>
</section>
<section id="visualizing-qualitative-variables" class="level1">
<h1>Visualizing Qualitative Variables</h1>
<p>With quantitative variables fully described and visualized, we now turn to qualitative (categorical) variables. Rather than histograms and boxplots, categorical variables are best displayed using bar charts and pie charts — each bar or slice represents one category, with height or area proportional to its frequency.</p>
<ul>
<li>A categorical variable has categories that are either ordinal (with a logical order) or nominal (with no logical order).</li>
<li>Categorical variables need to be set as the factor data type in R to be analyzed and visualized correctly.</li>
<li>Some common graphing options for a single categorical variable:
<ol type="1">
<li>Bar graph</li>
<li>Pie chart</li>
</ol></li>
<li>In any graph, it is beneficial to do any data cleaning and investigation into the variable(s) before you begin. With categorical variables, this may require recoding the factor(s) of interest.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The layering concept introduced in <code>## Layering in ggplot</code> above applies to all ggplot2 charts, including the bar charts and pie charts in this section. Each <code>+</code> adds another layer — graph type, labels, colors, and themes all stack the same way.</p>
</div>
</div>
<section id="bar-graph" class="level2">
<h2 class="anchored" data-anchor-id="bar-graph">Bar Graph</h2>
<p>A bar graph depicts the frequency or relative frequency for each category of a qualitative variable as a bar rising vertically from the horizontal axis. It is often used to examine similarities and differences across categories. Before making a bar chart, the variable should be coded as a factor.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="geom_bar" class="level3">
<h3 class="anchored" data-anchor-id="geom_bar">geom_bar()</h3>
<ul>
<li>Create a bar graph using the <code>ggplot()</code> command.</li>
<li><code>ggplot()</code> works in layers, so you will routinely see the <code>+</code> symbol to kick off a new layer.</li>
<li>Using ggplot, we always include the <code>aes()</code> command first inside <code>ggplot()</code>. The <code>aes()</code> command describes the variables being used.
<ul>
<li>First layer: <code>ggplot()</code> and <code>aes()</code> — calls the dataset and variables.</li>
<li>Second layer: Graph type — <code>geom_bar()</code>.</li>
<li>Additional layers: <code>labs()</code> for labels and titles; themes; <code>geom_text()</code>.</li>
</ul></li>
</ul>
</section>
<section id="pertinent-parameters-to-geom_bar" class="level3">
<h3 class="anchored" data-anchor-id="pertinent-parameters-to-geom_bar">Pertinent Parameters to geom_bar()</h3>
<ul>
<li><strong>stat=“identity”</strong>: Specifies that the actual values in the data should be plotted directly, rather than having ggplot count observations. Use this when your y values are already computed.</li>
<li><strong>position=“dodge”</strong>: When plotting two categorical variables, setting <code>position="dodge"</code> places bars side by side instead of stacked.</li>
<li><strong>show.legend = FALSE</strong>: Hides the legend for a layer when the color is already clear from the axis labels.</li>
<li><strong>scale_fill_manual()</strong>: Allows you to manually define the colors used for filled bars.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>GoUp <span class="ot">&lt;-</span> <span class="fl">0.54285</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>GoDown <span class="ot">&lt;-</span> <span class="fl">0.03809</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>RemainStable <span class="ot">&lt;-</span> <span class="fl">0.34285</span></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>NoOpinion <span class="ot">&lt;-</span> <span class="fl">0.07619</span></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>data_frame <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Category =</span> <span class="fu">c</span>(<span class="st">"Go Up"</span>, <span class="st">"Go Down"</span>, <span class="st">"Remain Stable"</span>,</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"No Opinion"</span>), <span class="at">Percentage =</span> <span class="fu">c</span>(GoUp, GoDown, RemainStable, NoOpinion))</span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>MarketShare <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_frame, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Percentage, <span class="at">fill =</span> Category)) <span class="sc">+</span></span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"How do you expect R's market share to change?"</span>,</span>
<span id="cb103-11"><a href="#cb103-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Opinion Category"</span>, <span class="at">y =</span> <span class="st">"Percentage (%)"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Percentage),</span>
<span id="cb103-12"><a href="#cb103-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>,</span>
<span id="cb103-13"><a href="#cb103-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"purple"</span>, <span class="st">"green"</span>))</span>
<span id="cb103-14"><a href="#cb103-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-15"><a href="#cb103-15" aria-hidden="true" tabindex="-1"></a>MarketShare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="pie-chart" class="level2">
<h2 class="anchored" data-anchor-id="pie-chart">Pie Chart</h2>
<ul>
<li>A pie chart is a segmented circle whose segments portray the relative frequencies of a qualitative variable.</li>
<li>Pie charts are available in R but are generally not recommended because comparing slice sizes is harder than comparing bar heights. Bar graphs are preferred for most categorical data.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>fbi.deaths <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/fbi_deaths.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>fbi.deaths.small <span class="ot">&lt;-</span> fbi.deaths[<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>), ]</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>fbi.deaths.small <span class="ot">&lt;-</span> fbi.deaths.small <span class="sc">%&gt;%</span></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">Weapon =</span> X)</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fbi.deaths.small)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Weapon      X2012          X2013          X2014     
 Firearms, type not stated:1   Min.   : 116   Min.   : 123   Min.   :  93  
 Handguns                 :1   1st Qu.: 298   1st Qu.: 285   1st Qu.: 258  
 Other guns               :1   Median : 310   Median : 308   Median : 264  
 Rifles                   :1   Mean   :1779   Mean   :1691   Mean   :1662  
 Shotguns                 :1   3rd Qu.:1769   3rd Qu.:1956   3rd Qu.:2024  
 Asphyxiation             :0   Max.   :6404   Max.   :5782   Max.   :5673  
 (Other)                  :0                                               
     X2015          X2016     
 Min.   : 177   Min.   : 186  
 1st Qu.: 258   1st Qu.: 262  
 Median : 272   Median : 374  
 Mean   :1956   Mean   :2201  
 3rd Qu.:2502   3rd Qu.:3077  
 Max.   :6569   Max.   :7105  
                              </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fbi.deaths.small, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> X2016, <span class="at">fill =</span> Weapon)) <span class="sc">+</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="st">"y"</span>, <span class="at">start =</span> <span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="descriptives_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" alt="Pie Chart Generated by R" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="summary-and-review" class="level1">
<h1>Summary and Review</h1>
<section id="using-ai" class="level2">
<h2 class="anchored" data-anchor-id="using-ai">Using AI</h2>
<p>Use the following prompts with a generative AI tool like ChatGPT to explore descriptive statistics further.</p>
<ul>
<li>What is the difference between mean, median, and mode in describing data distributions, and how can each be used to understand the shape of a distribution?</li>
<li>How do mean and median help identify whether a distribution is skewed, and what does it tell us about the dataset?</li>
<li>Can you explain how the mean, median, and mode behave in normal, positively skewed, and negatively skewed distributions?</li>
<li>What are standard deviation (SD) and variance, and how do they measure the spread of data in a distribution?</li>
<li>Explain the differences between range, interquartile range (IQR), and standard deviation in describing the variability in a dataset.</li>
<li>How does a high standard deviation or variance affect the interpretation of a dataset compared to a low standard deviation?</li>
<li>What is skewness, and how does it affect the shape of a distribution? How can we identify positive and negative skew?</li>
<li>How is kurtosis defined in the semTools package in R, and what does it tell us about the tails of a distribution?</li>
<li>How would you compare and contrast the roles of skewness and kurtosis in identifying the shape and behavior of a distribution?</li>
</ul>
</section>
<section id="quantitative-data-lab" class="level2">
<h2 class="anchored" data-anchor-id="quantitative-data-lab">Quantitative Data Lab</h2>
<p>Use the <code>descriptive_data</code> dataset loaded earlier in this lesson. It contains the following quantitative variables: <code>ServiceScore</code>, <code>DeliveryTime</code>, <code>ReturnRate</code>, and <code>CustomerValue</code>. Make sure <code>tidyverse</code> and <code>semTools</code> are loaded.</p>
<p><strong>1.</strong> Compute the mean and median for both <code>ServiceScore</code> and <code>DeliveryTime</code>. Based on the relationship between those two values for each variable, which one appears skewed and which appears symmetric? Which measure of central tendency is more appropriate for each?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(descriptive_data<span class="sc">$</span>ServiceScore);   <span class="fu">median</span>(descriptive_data<span class="sc">$</span>ServiceScore)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(descriptive_data<span class="sc">$</span>DeliveryTime);   <span class="fu">median</span>(descriptive_data<span class="sc">$</span>DeliveryTime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ServiceScore</code>: mean ≈ 50.0, median = 50 — nearly identical, indicating a symmetric distribution. The mean is a reliable summary here.</p>
<p><code>DeliveryTime</code>: mean is notably higher than the median, indicating right skew — a few very long deliveries are pulling the mean upward. The <strong>median</strong> is the more appropriate measure of center for <code>DeliveryTime</code>.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Run <code>skew()</code> and <code>kurtosis()</code> from <code>semTools</code> on <code>ServiceScore</code> and <code>DeliveryTime</code>. Record the z-values for each and interpret them using the correct threshold for this sample size (n = 200).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(descriptive_data<span class="sc">$</span>ServiceScore);     <span class="fu">kurtosis</span>(descriptive_data<span class="sc">$</span>ServiceScore)</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skew</span>(descriptive_data<span class="sc">$</span>DeliveryTime);     <span class="fu">kurtosis</span>(descriptive_data<span class="sc">$</span>DeliveryTime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>With n = 200, the relevant threshold is <strong>±3.29</strong>.</p>
<p><code>ServiceScore</code>: both z-values fall well within ±3.29 — approximately symmetric and mesokurtic. Ready to use in analyses that assume normality.</p>
<p><code>DeliveryTime</code>: the skewness z-value exceeds 3.29 — significant right skew confirmed. The kurtosis z-value is also elevated, indicating heavy tails (leptokurtic). <code>DeliveryTime</code> should be transformed before use in parametric analyses.</p>
</div>
</div>
</div>
<p><strong>3.</strong> Calculate the standard deviation, variance, IQR, and range for <code>ServiceScore</code> and <code>ReturnRate</code>. Then explain: if both variables had similar means, what would a much larger standard deviation for one of them tell you?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(descriptive_data<span class="sc">$</span>ServiceScore);    <span class="fu">var</span>(descriptive_data<span class="sc">$</span>ServiceScore)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>ServiceScore);   <span class="fu">diff</span>(<span class="fu">range</span>(descriptive_data<span class="sc">$</span>ServiceScore))</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(descriptive_data<span class="sc">$</span>ReturnRate);      <span class="fu">var</span>(descriptive_data<span class="sc">$</span>ReturnRate)</span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>ReturnRate);     <span class="fu">diff</span>(<span class="fu">range</span>(descriptive_data<span class="sc">$</span>ReturnRate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ServiceScore</code>: SD ≈ 4.88, IQR ≈ 8, range 40–59. Scores are tightly clustered around the mean — very consistent.</p>
<p><code>ReturnRate</code>: SD ≈ 1.00, IQR ≈ 1.33, range −3.24 to 2.50. The range is stretched by two low outliers, but the bulk of values sit in a tight band near zero.</p>
<p>If both variables had similar means, a much larger SD for one would indicate that individual values are spread further from the center — more variability and less predictability in that variable.</p>
</div>
</div>
</div>
<p><strong>4.</strong> Compute the IQR-based outlier bounds for <code>DeliveryTime</code> and list any flagged values. Does finding an outlier mean that value is wrong?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>Q1  <span class="ot">&lt;-</span> <span class="fu">quantile</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="fl">0.25</span>)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>Q3  <span class="ot">&lt;-</span> <span class="fu">quantile</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="fl">0.75</span>)</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>IQR_val     <span class="ot">&lt;-</span> <span class="fu">IQR</span>(descriptive_data<span class="sc">$</span>DeliveryTime, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>lower_bound <span class="ot">&lt;-</span> Q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_val</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> Q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> IQR_val</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>descriptive_data[descriptive_data<span class="sc">$</span>DeliveryTime <span class="sc">&lt;</span> lower_bound <span class="sc">|</span></span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a>                 descriptive_data<span class="sc">$</span>DeliveryTime <span class="sc">&gt;</span> upper_bound, <span class="st">"DeliveryTime"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Values above the upper bound are flagged as outliers — these are deliveries that took substantially longer than the typical range. Being flagged does not mean a value is wrong. Each outlier should be investigated: it could be a legitimate extreme case (an unusually complex delivery), a data entry error, or a record from a different population entirely. That judgment requires context, not just a formula.</p>
</div>
</div>
</div>
<p><strong>5.</strong> Create a histogram of <code>ServiceScore</code> (binwidth = 5) and a separate histogram of <code>DeliveryTime</code> (binwidth = 25), each with an informative title and a non-black fill. Compare the shapes — does each histogram match what the skewness statistics showed?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> ServiceScore)) <span class="sc">+</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"mediumseagreen"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Service Score"</span>, <span class="at">x =</span> <span class="st">"Service Score"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> DeliveryTime)) <span class="sc">+</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"tomato"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Delivery Time"</span>, <span class="at">x =</span> <span class="st">"Delivery Time"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ServiceScore</code> should appear roughly symmetric with no tail — consistent with the near-zero skewness z-score. <code>DeliveryTime</code> should show a clear right tail with most values clustered at lower times and a few stretching far to the right — matching the significant positive skewness z-value. This is the intended workflow: compute the statistics first, then confirm visually.</p>
</div>
</div>
</div>
<p><strong>6.</strong> Create boxplots for <code>ServiceScore</code> and <code>DeliveryTime</code>. For each, identify whether outliers appear as individual points. Then explain what the relative lengths of the whiskers tell you about symmetry.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> DeliveryTime)) <span class="sc">+</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"tomato"</span>, <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Delivery Time"</span>, <span class="at">x =</span> <span class="st">"Delivery Time"</span>)</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> ServiceScore)) <span class="sc">+</span></span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"mediumseagreen"</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Service Score"</span>, <span class="at">x =</span> <span class="st">"Service Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>ServiceScore</code>: no outlier points visible, whiskers roughly equal in length — a symmetric distribution. <code>DeliveryTime</code>: individual points plotted beyond the right whisker confirm the outliers identified numerically in Question 4. The right whisker is much longer than the left, visually showing the right skew.</p>
<p>Unequal whisker lengths are a fast visual signal: if the right whisker is longer, the upper values are more spread out — right skew. If the left is longer, the data is left-skewed. Symmetric distributions have roughly equal whiskers.</p>
</div>
</div>
</div>
<p><strong>7.</strong> Create a density plot of <code>CustomerValue</code> with a dashed vertical line at the mean. Based on where the mean line falls relative to the peak, is the distribution symmetric or skewed?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> CustomerValue)) <span class="sc">+</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"navy"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(CustomerValue, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density of Customer Value"</span>, <span class="at">x =</span> <span class="st">"Customer Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The mean line should sit close to the peak of the distribution. If the mean falls slightly to the right of the peak, a mild right skew is present — consistent with the mean (≈96.6) being slightly higher than the median (≈94). A symmetric distribution would show the mean sitting exactly at the peak.</p>
</div>
</div>
</div>
</section>
<section id="qualitative-data-lab" class="level2">
<h2 class="anchored" data-anchor-id="qualitative-data-lab">Qualitative Data Lab</h2>
<p>Use the <code>descriptive_data</code> dataset. The two qualitative variables are <code>EngagementLevel</code> (high, medium, low) and <code>LoyalCustomer</code> (yes, no).</p>
<p><strong>1.</strong> Build a complete frequency summary for <code>EngagementLevel</code>: frequency, relative frequency, cumulative frequency, and cumulative proportion. Combine them into a single transposed data frame, then fill in the table below from your output.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>frequencies      <span class="ot">&lt;-</span> <span class="fu">table</span>(descriptive_data<span class="sc">$</span>EngagementLevel)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>proportions      <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(frequencies)</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>cumulfreq        <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frequencies)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>cumulproportions <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">prop.table</span>(frequencies))</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>frequency_table  <span class="ot">&lt;-</span> <span class="fu">rbind</span>(frequencies, proportions, cumulfreq, cumulproportions)</span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>TransposedData   <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(frequency_table))</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>TransposedData</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th>Frequency</th>
<th>Proportion</th>
<th>Cumul. Freq</th>
<th>Cumul. Prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>high</td>
<td>53</td>
<td>0.265</td>
<td>53</td>
<td>0.265</td>
</tr>
<tr class="even">
<td>low</td>
<td>67</td>
<td>0.335</td>
<td>120</td>
<td>0.600</td>
</tr>
<tr class="odd">
<td>medium</td>
<td>80</td>
<td>0.400</td>
<td>200</td>
<td>1.000</td>
</tr>
</tbody>
</table>
<p>Medium engagement is most common at 40.0% of customers.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Run the same frequency analysis on <code>LoyalCustomer</code>. What percentage of customers are loyal? Which <code>rbind()</code> row tells you this most directly?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>frequencies      <span class="ot">&lt;-</span> <span class="fu">table</span>(descriptive_data<span class="sc">$</span>LoyalCustomer)</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>proportions      <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(frequencies)</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>cumulfreq        <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frequencies)</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>cumulproportions <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(<span class="fu">prop.table</span>(frequencies))</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>frequency_table  <span class="ot">&lt;-</span> <span class="fu">rbind</span>(frequencies, proportions, cumulfreq, cumulproportions)</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">t</span>(frequency_table))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>43.5% of customers are loyal (yes) and 56.5% are not (no). The <code>proportions</code> row gives this most directly — it divides each frequency by the total, producing the relative share of each category without any extra calculation.</p>
</div>
</div>
</div>
<p><strong>3.</strong> Create a bar chart of <code>EngagementLevel</code> showing counts, then a second version showing proportions on the y-axis. What does switching from counts to proportions change about what the chart communicates?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counts</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> EngagementLevel)) <span class="sc">+</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Customer Count by Engagement Level"</span>,</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Engagement Level"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportions</span></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> EngagementLevel, <span class="at">y =</span> <span class="fu">after_stat</span>(prop), <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb116-10"><a href="#cb116-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb116-11"><a href="#cb116-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportion of Customers by Engagement Level"</span>,</span>
<span id="cb116-12"><a href="#cb116-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Engagement Level"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The shape is identical — bars have the same relative heights. The difference is interpretability: counts tell you how many customers are in each group (useful when the total sample size matters), while proportions tell you the share of the whole (easier to compare across datasets of different sizes). Use proportions when you want to communicate relative importance rather than raw volume.</p>
</div>
</div>
</div>
<p><strong>4.</strong> Create a grouped bar chart with <code>EngagementLevel</code> on the x-axis and bars colored by <code>LoyalCustomer</code>. Use <code>position = "dodge"</code> and add a <code>scale_fill_manual()</code> with two colors of your choice. What pattern do you see in the loyalty split across engagement levels?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(descriptive_data, <span class="fu">aes</span>(<span class="at">x =</span> EngagementLevel, <span class="at">fill =</span> LoyalCustomer)) <span class="sc">+</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Engagement Level by Loyalty Status"</span>,</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Engagement Level"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Loyal Customer"</span>) <span class="sc">+</span></span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"no"</span> <span class="ot">=</span> <span class="st">"tomato"</span>, <span class="st">"yes"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Non-loyal customers outnumber loyal customers within every engagement level: high (27 no vs.&nbsp;26 yes), low (39 no vs.&nbsp;28 yes), medium (47 no vs.&nbsp;33 yes). Loyal customers are a consistent minority across all three groups — engagement level alone does not appear to strongly separate loyal from non-loyal customers.</p>
</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This lesson covered descriptive statistics for both quantitative and qualitative data in R:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Key concepts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Central tendency — mean</td>
<td><code>mean()</code>, <code>weighted.mean()</code>; best when distribution is symmetric; sensitive to outliers</td>
</tr>
<tr class="even">
<td>Central tendency — median</td>
<td><code>median()</code>; preferred when data is skewed or outliers are present; not affected by extremes</td>
</tr>
<tr class="odd">
<td>Central tendency — mode</td>
<td><code>sort(table(), decreasing=TRUE)</code>; most useful for categorical data or identifying the most common value</td>
</tr>
<tr class="even">
<td>Skewness</td>
<td><code>skew()</code> from <code>semTools</code>; z-score thresholds: ±2 (n &lt; 50), ±3.29 (n 50–300), ±7 (n &gt; 300)</td>
</tr>
<tr class="odd">
<td>Kurtosis</td>
<td><code>kurtosis()</code> from <code>semTools</code>; same z-score thresholds; leptokurtic (positive) vs.&nbsp;platykurtic (negative)</td>
</tr>
<tr class="even">
<td>Variance and standard deviation</td>
<td><code>var()</code>, <code>sd()</code>; paired with mean; measure average deviation from center</td>
</tr>
<tr class="odd">
<td>Range and IQR</td>
<td><code>diff(range())</code>, <code>IQR()</code>, <code>quantile()</code>; paired with median; IQR is the middle 50% of data</td>
</tr>
<tr class="even">
<td>Outlier detection</td>
<td>Lower bound = Q1 − 1.5 × IQR; upper bound = Q3 + 1.5 × IQR; flagged ≠ wrong</td>
</tr>
<tr class="odd">
<td>Histograms</td>
<td><code>geom_histogram(binwidth=)</code>; reveals shape, center, and spread; connect visually to skewness</td>
</tr>
<tr class="even">
<td>Density plots</td>
<td><code>geom_density()</code>; smoothed histogram; use <code>geom_vline()</code> to overlay the mean</td>
</tr>
<tr class="odd">
<td>Boxplots</td>
<td><code>geom_boxplot()</code>; five-number summary (min, Q1, median, Q3, max); outliers plotted individually</td>
</tr>
<tr class="even">
<td>Frequency tables</td>
<td><code>table()</code>, <code>prop.table()</code>, <code>cumsum()</code>; combined with <code>rbind()</code>, <code>t()</code>, <code>as.data.frame()</code></td>
</tr>
<tr class="odd">
<td>Bar charts</td>
<td><code>geom_bar()</code> for counts; <code>after_stat(prop)</code> for proportions; <code>position="dodge"</code> for grouped bars</td>
</tr>
<tr class="even">
<td>Pie charts</td>
<td><code>coord_polar("y")</code>; available but bar charts are preferred for accurate comparison</td>
</tr>
</tbody>
</table>
<p><strong>What comes next:</strong> The Data Preparation lesson introduces the tools needed to clean and reshape data before analysis — filtering rows, selecting columns, recoding variables, handling missing values, and reshaping between wide and long formats using <code>dplyr</code>. The summary statistics and charts in this lesson are only meaningful on clean data, so data preparation is the essential next step.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./introR.html" class="pagination-link" aria-label="Introduction to R and RStudio">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Introduction to R and RStudio</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./dataprep.html" class="pagination-link" aria-label="Data Preparation">
        <span class="nav-page-text"><span class="chapter-title">Data Preparation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>