<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2024-08-09">

<title>Regression – Probability And Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./anova.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-64b801fe9b6685c0a799f7172ecad621.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
     <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4MST1J29YB"></script>
          <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          
          gtag('config', 'G-4MST1J29YB');
          </script>

<!-- ============================================================
     Statistics Course Assistant — Floating Chat Bubble
     Appears on every page of the book.
     Set WORKER_URL below to your Cloudflare Worker URL.
     ============================================================ -->
<style>
  /* ── Floating button ── */
  #chat-fab {
    position: fixed;
    bottom: 28px;
    right: 28px;
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 4px 20px rgba(79, 142, 247, 0.45);
    z-index: 9999;
    transition: transform 0.2s, box-shadow 0.2s;
  }

  #chat-fab:hover {
    transform: scale(1.08);
    box-shadow: 0 6px 28px rgba(79, 142, 247, 0.6);
  }

  #chat-fab svg { width: 24px; height: 24px; color: #fff; }

  /* unread dot */
  #chat-fab-dot {
    position: absolute;
    top: 4px;
    right: 4px;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: #ff5a5a;
    border: 2px solid #fff;
    display: none;
  }

  /* ── Chat panel ── */
  #chat-panel {
    position: fixed;
    bottom: 96px;
    right: 28px;
    width: 380px;
    max-width: calc(100vw - 40px);
    height: 520px;
    max-height: calc(100vh - 120px);
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 16px;
    display: none;
    flex-direction: column;
    z-index: 9998;
    box-shadow: 0 12px 48px rgba(0,0,0,0.5);
    overflow: hidden;
    animation: panelIn 0.25s ease;
    font-family: 'IBM Plex Sans', -apple-system, sans-serif;
  }

  #chat-panel.open { display: flex; }

  @keyframes panelIn {
    from { opacity: 0; transform: translateY(12px) scale(0.97); }
    to   { opacity: 1; transform: translateY(0) scale(1); }
  }

  /* panel header */
  #chat-panel-header {
    padding: 14px 16px;
    background: #181c27;
    border-bottom: 1px solid #2a2f3e;
    display: flex;
    align-items: center;
    gap: 10px;
    flex-shrink: 0;
  }

  #chat-panel-header .logo {
    width: 30px;
    height: 30px;
    border-radius: 7px;
    background: linear-gradient(135deg, #4f8ef7, #7c5cfc);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 600;
    color: #fff;
    font-family: 'IBM Plex Mono', monospace;
    flex-shrink: 0;
  }

  #chat-panel-header .title { flex: 1; }

  #chat-panel-header .title h3 {
    font-size: 13px;
    font-weight: 600;
    color: #e8eaf0;
    margin: 0;
    line-height: 1.2;
  }

  #chat-panel-header .title p {
    font-size: 11px;
    color: #7a8099;
    margin: 0;
    font-family: 'IBM Plex Mono', monospace;
  }

  #chat-close-btn {
    background: none;
    border: none;
    color: #7a8099;
    cursor: pointer;
    padding: 4px;
    border-radius: 4px;
    display: flex;
    align-items: center;
    transition: color 0.15s;
  }

  #chat-close-btn:hover { color: #e8eaf0; }
  #chat-close-btn svg { width: 16px; height: 16px; }

  /* messages */
  #chat-messages {
    flex: 1;
    overflow-y: auto;
    padding: 14px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    scroll-behavior: smooth;
  }

  #chat-messages::-webkit-scrollbar { width: 3px; }
  #chat-messages::-webkit-scrollbar-thumb { background: #2a2f3e; border-radius: 3px; }

  .cm {
    display: flex;
    gap: 8px;
    animation: msgIn 0.2s ease;
  }

  @keyframes msgIn {
    from { opacity: 0; transform: translateY(4px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  .cm-av {
    width: 22px;
    height: 22px;
    border-radius: 5px;
    flex-shrink: 0;
    margin-top: 1px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 9px;
    font-weight: 700;
    font-family: 'IBM Plex Mono', monospace;
  }

  .cm.user .cm-av  { background: #1e2640; border: 1px solid #2e3a5a; color: #4f8ef7; }
  .cm.bot .cm-av   { background: linear-gradient(135deg, #4f8ef7, #7c5cfc); color: #fff; }
  .cm.error .cm-av { background: #3a1010; color: #ff8a8a; }

  .cm-text {
    flex: 1;
    background: #141720;
    border: 1px solid #2a2f3e;
    border-radius: 10px;
    padding: 8px 11px;
    font-size: 13px;
    line-height: 1.55;
    color: #e8eaf0;
    min-width: 0;
    word-break: break-word;
  }

  .cm.user .cm-text  { background: #1e2640; border-color: #2e3a5a; }
  .cm.error .cm-text { background: #1c1010; border-color: #5a2e2e; color: #ff8a8a; }

  .cm-text p { margin: 0 0 6px; }
  .cm-text p:last-child { margin-bottom: 0; }

  .cm-text code {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 3px;
    padding: 1px 5px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 11.5px;
    color: #a5c3ff;
  }

  .cm-text pre {
    background: #0a0c12;
    border: 1px solid #2a2f3e;
    border-radius: 6px;
    padding: 10px 12px;
    overflow-x: auto;
    margin: 6px 0;
  }

  .cm-text pre code {
    background: none;
    border: none;
    padding: 0;
    font-size: 12px;
    color: #c8d8ff;
  }

  .cm-text ul, .cm-text ol { padding-left: 16px; margin: 4px 0; }
  .cm-text li { margin-bottom: 3px; }
  .cm-text strong { color: #fff; font-weight: 600; }

  /* typing dots */
  .typing-dots { display: flex; gap: 3px; align-items: center; padding: 2px 0; }
  .typing-dots span {
    width: 5px; height: 5px; border-radius: 50%;
    background: #7a8099;
    animation: td 1.2s infinite;
  }
  .typing-dots span:nth-child(2) { animation-delay: 0.2s; }
  .typing-dots span:nth-child(3) { animation-delay: 0.4s; }

  @keyframes td {
    0%,60%,100% { transform: translateY(0); opacity:0.4; }
    30% { transform: translateY(-4px); opacity:1; }
  }

  /* welcome inside panel */
  .panel-welcome {
    text-align: center;
    padding: 20px 10px;
    color: #7a8099;
  }

  .panel-welcome p {
    font-size: 12.5px;
    margin: 0 0 14px;
    line-height: 1.5;
    color: #7a8099;
  }

  .panel-chips {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    justify-content: center;
  }

  .panel-chip {
    background: #181c27;
    border: 1px solid #2a2f3e;
    border-radius: 14px;
    padding: 5px 10px;
    font-size: 11.5px;
    color: #7a8099;
    cursor: pointer;
    transition: all 0.15s;
    font-family: 'IBM Plex Mono', monospace;
    text-align: left;
  }

  .panel-chip:hover {
    border-color: #4f8ef7;
    color: #4f8ef7;
    background: rgba(79,142,247,0.07);
  }

  /* input row */
  #chat-input-row {
    padding: 10px 12px;
    border-top: 1px solid #2a2f3e;
    background: #181c27;
    display: flex;
    gap: 8px;
    align-items: flex-end;
    flex-shrink: 0;
  }

  #chat-input {
    flex: 1;
    background: #0f1117;
    border: 1px solid #2a2f3e;
    border-radius: 8px;
    padding: 8px 11px;
    font-family: -apple-system, sans-serif;
    font-size: 13px;
    color: #e8eaf0;
    resize: none;
    min-height: 36px;
    max-height: 100px;
    outline: none;
    line-height: 1.4;
    transition: border-color 0.2s;
    overflow-y: auto;
  }

  #chat-input:focus { border-color: #4f8ef7; }
  #chat-input::placeholder { color: #7a8099; }

  #chat-send {
    width: 36px;
    height: 36px;
    border-radius: 8px;
    border: none;
    background: #4f8ef7;
    color: #fff;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    transition: opacity 0.15s;
  }

  #chat-send:hover { opacity: 0.85; }
  #chat-send:disabled { opacity: 0.3; cursor: not-allowed; }
  #chat-send svg { width: 15px; height: 15px; }

  /* mobile adjustments */
  @media (max-width: 480px) {
    #chat-panel { right: 12px; bottom: 80px; width: calc(100vw - 24px); }
    #chat-fab   { right: 16px; bottom: 16px; }
  }
</style>

<!-- Floating Action Button -->
</head><body class="nav-sidebar floating nav-fixed"><button id="chat-fab" onclick="toggleChat()" title="Course Assistant" aria-label="Open course assistant">
  <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
  </svg>
  <div id="chat-fab-dot"></div>
</button>

<!-- Chat Panel -->
<div id="chat-panel">
  <div id="chat-panel-header">
    <div class="logo">R∑</div>
    <div class="title">
      <h3>Course Assistant</h3>
      <p>R &amp; Statistics</p>
    </div>
    <button id="chat-close-btn" onclick="toggleChat()" aria-label="Close">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>

  <div id="chat-messages">
    <div class="panel-welcome" id="panel-welcome">
      <p>Ask me anything about R, statistics concepts, or your code.</p>
      <div class="panel-chips">
        <div class="panel-chip" onclick="chipSend(this)">mean vs median?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is skewness?</div>
        <div class="panel-chip" onclick="chipSend(this)">How do I use filter()?</div>
        <div class="panel-chip" onclick="chipSend(this)">Explain na.rm=TRUE</div>
        <div class="panel-chip" onclick="chipSend(this)">How to read a CSV?</div>
        <div class="panel-chip" onclick="chipSend(this)">What is kurtosis?</div>
      </div>
    </div>
  </div>

  <div id="chat-input-row">
    <textarea id="chat-input" rows="1" placeholder="Ask a question…" onkeydown="chatKey(event)" oninput="chatResize(this)"></textarea>
    <button id="chat-send" onclick="chatSend()" aria-label="Send">
      <svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="22" y1="2" x2="11" y2="13"></line>
        <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
      </svg>
    </button>
  </div>
</div>

<script>
  // ============================================================
  // Set this to your Cloudflare Worker URL after deploying

  // ============================================================
  var CHAT_WORKER_URL = 'https://statchat.pamela-schlosser.workers.dev';
  // ============================================================

  var chatHistory = [];
  var chatLoading = false;
  var chatIsOpen  = false;

  function toggleChat() {
    chatIsOpen = !chatIsOpen;
    var panel = document.getElementById('chat-panel');
    var dot   = document.getElementById('chat-fab-dot');
    if (chatIsOpen) {
      panel.classList.add('open');
      dot.style.display = 'none';
      setTimeout(function() {
        var inp = document.getElementById('chat-input');
        if (inp) inp.focus();
      }, 100);
    } else {
      panel.classList.remove('open');
    }
  }

  function chipSend(el) {
    var inp = document.getElementById('chat-input');
    inp.value = el.textContent.trim();
    chatSend();
  }

  function chatKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      chatSend();
    }
  }

  function chatResize(el) {
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 100) + 'px';
  }

  function escHtml(s) {
    return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  function mdToHtml(text) {
    text = text.replace(/```(\w*)\n?([\s\S]*?)```/g, function(_,l,c) {
      return '<pre><code>' + escHtml(c.trim()) + '</code></pre>';
    });
    text = text.replace(/`([^`]+)`/g, '<code>$1</code>');
    text = text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    text = text.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
    text = text.replace(/(<li>.*<\/li>\n?)+/g, function(m) { return '<ul>' + m + '</ul>'; });
    text = text.split(/\n{2,}/).map(function(p) {
      p = p.trim();
      if (!p || p.charAt(0) === '<') return p;
      return '<p>' + p.replace(/\n/g,'<br>') + '</p>';
    }).join('');
    return text;
  }

  function addMsg(role, content, typing) {
    var welcome = document.getElementById('panel-welcome');
    if (welcome) welcome.remove();
    var box = document.getElementById('chat-messages');
    var d   = document.createElement('div');
    d.className = 'cm ' + role;
    var av = role==='user' ? 'you' : role==='bot' ? 'ai' : '!';
    if (typing) {
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text" id="cm-typing">' +
        '<div class="typing-dots"><span></span><span></span><span></span></div>' +
        '</div>';
    } else {
      var html = role==='user'
        ? '<p>' + escHtml(content) + '</p>'
        : mdToHtml(content);
      d.innerHTML = '<div class="cm-av">' + av + '</div>' +
        '<div class="cm-text">' + html + '</div>';
    }
    box.appendChild(d);
    box.scrollTop = box.scrollHeight;
    if (!chatIsOpen && role === 'bot') {
      document.getElementById('chat-fab-dot').style.display = 'block';
    }
  }

  function removeTyping() {
    var t = document.getElementById('cm-typing');
    if (t) t.closest('.cm').remove();
  }

  async function chatSend() {
    if (chatLoading) return;

    var el   = document.getElementById('chat-input');
    var text = el.value.trim();
    if (!text) return;

    addMsg('user', text);
    chatHistory.push({ role: 'user', content: text });
    el.value = '';
    el.style.height = 'auto';

    chatLoading = true;
    document.getElementById('chat-send').disabled = true;
    addMsg('bot', '', true);

    try {
      var res = await fetch(CHAT_WORKER_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 1024,
          messages: chatHistory
        })
      });

      removeTyping();

      if (!res.ok) {
        var err = await res.json().catch(function() { return {}; });
        var msg = err.error || ('HTTP ' + res.status);
        addMsg('error', res.status === 429
          ? 'Rate limit reached. Please wait a moment and try again.'
          : 'Something went wrong: ' + msg);
        chatHistory.pop();
      } else {
        var data  = await res.json();
        var reply = (data.content && data.content[0] && data.content[0].text) || '(no response)';
        chatHistory.push({ role: 'assistant', content: reply });
        addMsg('bot', reply);
      }

    } catch(err) {
      removeTyping();
      addMsg('error', 'Network error: ' + err.message);
      chatHistory.pop();
    }

    chatLoading = false;
    document.getElementById('chat-send').disabled = false;
  }
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Probability And Business Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./chat.html"> 
<span class="menu-text">Course Assistant</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-title">Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Software Know-How</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introR.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to R and RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Descriptive Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataprep.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Preparation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ai.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Using AI</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Calculating Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">ANOVA and Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Recommended Further Reading Materials</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a Glance</a></li>
  <li><a href="#lesson-objectives" id="toc-lesson-objectives" class="nav-link" data-scroll-target="#lesson-objectives">Lesson Objectives</a></li>
  <li><a href="#consider-while-reading" id="toc-consider-while-reading" class="nav-link" data-scroll-target="#consider-while-reading">Consider While Reading</a></li>
  <li><a href="#the-linear-regression-model" id="toc-the-linear-regression-model" class="nav-link" data-scroll-target="#the-linear-regression-model">The Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#overview-of-the-linear-regression" id="toc-overview-of-the-linear-regression" class="nav-link" data-scroll-target="#overview-of-the-linear-regression">Overview of the Linear Regression</a></li>
  <li><a href="#examples-of-independent-and-dependent-variables" id="toc-examples-of-independent-and-dependent-variables" class="nav-link" data-scroll-target="#examples-of-independent-and-dependent-variables">Examples of Independent and Dependent Variables</a></li>
  <li><a href="#estimating-using-a-simple-linear-regression-model" id="toc-estimating-using-a-simple-linear-regression-model" class="nav-link" data-scroll-target="#estimating-using-a-simple-linear-regression-model">Estimating Using a Simple Linear Regression Model</a></li>
  <li><a href="#inexact-relationships" id="toc-inexact-relationships" class="nav-link" data-scroll-target="#inexact-relationships">Inexact Relationships</a></li>
  <li><a href="#regression-as-anova" id="toc-regression-as-anova" class="nav-link" data-scroll-target="#regression-as-anova">Regression as ANOVA</a></li>
  </ul></li>
  <li><a href="#the-simple-linear-regression-model" id="toc-the-simple-linear-regression-model" class="nav-link" data-scroll-target="#the-simple-linear-regression-model">The Simple Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#the-least-squares-estimates" id="toc-the-least-squares-estimates" class="nav-link" data-scroll-target="#the-least-squares-estimates">The Least Squares Estimates</a></li>
  <li><a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit">Goodness of Fit</a></li>
  <li><a href="#the-standard-error-of-the-estimate" id="toc-the-standard-error-of-the-estimate" class="nav-link" data-scroll-target="#the-standard-error-of-the-estimate">The Standard Error of the Estimate</a></li>
  <li><a href="#the-coefficient-of-determination-r2" id="toc-the-coefficient-of-determination-r2" class="nav-link" data-scroll-target="#the-coefficient-of-determination-r2">The Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</a></li>
  <li><a href="#the-adjusted-r2" id="toc-the-adjusted-r2" class="nav-link" data-scroll-target="#the-adjusted-r2">The Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#example-of-simple-linear-regression-in-r" id="toc-example-of-simple-linear-regression-in-r" class="nav-link" data-scroll-target="#example-of-simple-linear-regression-in-r">Example of Simple Linear Regression in R</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions">Predictions</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression">Multiple Regression</a>
  <ul class="collapse">
  <li><a href="#example-of-multiple-linear-regression-in-r" id="toc-example-of-multiple-linear-regression-in-r" class="nav-link" data-scroll-target="#example-of-multiple-linear-regression-in-r">Example of Multiple Linear Regression in R</a></li>
  <li><a href="#examining-the-goodness-of-fit-measures-1" id="toc-examining-the-goodness-of-fit-measures-1" class="nav-link" data-scroll-target="#examining-the-goodness-of-fit-measures-1">Examining the Goodness of Fit Measures</a></li>
  <li><a href="#examining-the-f-test-statistic-1" id="toc-examining-the-f-test-statistic-1" class="nav-link" data-scroll-target="#examining-the-f-test-statistic-1">Examining the F-Test Statistic</a></li>
  <li><a href="#examining-the-hypotheses" id="toc-examining-the-hypotheses" class="nav-link" data-scroll-target="#examining-the-hypotheses">Examining the Hypotheses</a></li>
  <li><a href="#interpreting-the-hypothesis-1" id="toc-interpreting-the-hypothesis-1" class="nav-link" data-scroll-target="#interpreting-the-hypothesis-1">Interpreting the Hypothesis</a></li>
  <li><a href="#the-p-value-method" id="toc-the-p-value-method" class="nav-link" data-scroll-target="#the-p-value-method">The P-value Method</a></li>
  <li><a href="#multicollinerity" id="toc-multicollinerity" class="nav-link" data-scroll-target="#multicollinerity">Multicollinerity</a></li>
  </ul></li>
  <li><a href="#regression-with-categorical-variables" id="toc-regression-with-categorical-variables" class="nav-link" data-scroll-target="#regression-with-categorical-variables">Regression with Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#dummy-variables-with-more-than-2-categories" id="toc-dummy-variables-with-more-than-2-categories" class="nav-link" data-scroll-target="#dummy-variables-with-more-than-2-categories">Dummy Variables with More than 2 Categories</a></li>
  <li><a href="#example-using-dummy-variables" id="toc-example-using-dummy-variables" class="nav-link" data-scroll-target="#example-using-dummy-variables">Example Using Dummy Variables</a></li>
  <li><a href="#example-using-a-continuous-and-categorical-variable" id="toc-example-using-a-continuous-and-categorical-variable" class="nav-link" data-scroll-target="#example-using-a-continuous-and-categorical-variable">Example Using a Continuous and Categorical Variable</a></li>
  <li><a href="#coffee-example" id="toc-coffee-example" class="nav-link" data-scroll-target="#coffee-example">Coffee Example</a>
  <ul class="collapse">
  <li><a href="#visualizing" id="toc-visualizing" class="nav-link" data-scroll-target="#visualizing">Visualizing</a></li>
  <li><a href="#categories" id="toc-categories" class="nav-link" data-scroll-target="#categories">2 Categories</a></li>
  <li><a href="#using-more-than-2-categories" id="toc-using-more-than-2-categories" class="nav-link" data-scroll-target="#using-more-than-2-categories">Using More Than 2 Categories</a></li>
  </ul></li>
  <li><a href="#adding-in-a-numerical-variable" id="toc-adding-in-a-numerical-variable" class="nav-link" data-scroll-target="#adding-in-a-numerical-variable">Adding in a Numerical Variable</a></li>
  </ul></li>
  <li><a href="#review-and-summary" id="toc-review-and-summary" class="nav-link" data-scroll-target="#review-and-summary">Review and Summary</a>
  <ul class="collapse">
  <li><a href="#using-ai" id="toc-using-ai" class="nav-link" data-scroll-target="#using-ai">Using AI</a></li>
  <li><a href="#regression-lab" id="toc-regression-lab" class="nav-link" data-scroll-target="#regression-lab">Regression Lab</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This lesson covers simple and multiple linear regression — the foundational predictive modeling technique in business analytics. Building on the correlation analysis from the previous lesson, we move from describing relationships to modeling and forecasting them.</p>
<p>We begin with the <strong>simple linear regression model</strong>, which estimates a straight-line relationship between one explanatory variable and one continuous response variable. The key outputs are the slope and intercept — parameters that define the regression line — along with three goodness-of-fit measures: the Residual Standard Error (RSE), the coefficient of determination (R²), and the Adjusted R². The F-statistic tests whether the model as a whole explains a meaningful share of the variation in the outcome, and the t-statistics on each coefficient test each predictor individually.</p>
<p>We then extend to <strong>multiple regression</strong>, which adds two or more explanatory variables to the model. Multiple regression allows us to control for competing influences on the outcome, isolating the unique contribution of each predictor while holding the others constant. We cover the p-value method for variable selection — iteratively removing the least significant predictors while watching that the Adjusted R² does not meaningfully decline — and multicollinearity, which arises when predictors are highly correlated with each other and can distort or destabilize coefficient estimates.</p>
<p>The lesson closes with <strong>regression using categorical variables</strong>. When a predictor is categorical rather than continuous, R automatically converts it into dummy variables — a set of binary indicators, one per category, with one category held back as the reference. We work through examples with two-category and multi-category predictors, and combine continuous and categorical predictors in the same model.</p>
<p>By the end of this lesson, you should be able to fit and interpret simple and multiple regression models in R, evaluate goodness of fit, test predictor significance, build a regression equation for prediction, detect and address multicollinearity, and correctly include categorical variables using dummy coding. Work through every code example in your own R script alongside the reading.</p>
<section id="at-a-glance" class="level3">
<h3 class="anchored" data-anchor-id="at-a-glance">At a Glance</h3>
<ul>
<li>In order to succeed at this lesson, you will use a statistical model called linear regression to understand an outcome variable and make predictions. Correlation — covered in the previous lesson — establishes whether a linear relationship exists and how strong it is. Regression uses that relationship to estimate a slope and intercept, allowing us to quantify the effect of each predictor and forecast future values. Linear regression is one of the most commonly used models in business analytics and forms the foundation for more advanced techniques like machine learning.</li>
</ul>
</section>
<section id="lesson-objectives" class="level3">
<h3 class="anchored" data-anchor-id="lesson-objectives">Lesson Objectives</h3>
<ul>
<li>Explore the statistical model for a line.</li>
<li>Compute the slope and intercept in a simple linear regression.</li>
<li>Interpret regression model significance and goodness-of-fit measures (RSE, R², Adjusted R²).</li>
<li>Extend to multiple regression with two or more predictors.</li>
<li>Apply the p-value method for variable selection.</li>
<li>Detect and interpret multicollinearity using VIF scores.</li>
<li>Include categorical predictors using dummy variables.</li>
</ul>
</section>
<section id="consider-while-reading" class="level3">
<h3 class="anchored" data-anchor-id="consider-while-reading">Consider While Reading</h3>
<ul>
<li>In this lesson, we focus on building and interpreting regression models in R. This builds on the scatterplots introduced in the Data Visualization lesson — those visualizations help us assess linearity before running a model — and on the correlation analysis from the previous lesson, which told us whether a relationship was worth modeling in the first place.</li>
<li>As you read, note the connection between regression and ANOVA. The F-test in a regression output works the same way as in an ANOVA: it tests whether the variation in Y that is explained by the model is significantly greater than the unexplained variation. The sum-of-squares logic (SSR, SSE, SST) is identical.</li>
<li>Pay particular attention to the distinction between the overall F-test (is the model significant?) and the individual t-tests on each coefficient (is this specific predictor significant?). In simple regression these give the same p-value, but in multiple regression they can diverge.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the previous lesson, we used correlation to measure the strength and direction of the linear relationship between two continuous variables. Regression takes the next step: it uses that relationship to build a predictive model. Where a correlation coefficient tells you <em>how strongly</em> two variables move together, a regression equation tells you <em>by how much</em> one variable changes for each unit change in the other — and lets you forecast values you have not yet observed.</p>
</section>
<section id="the-linear-regression-model" class="level1">
<h1>The Linear Regression Model</h1>
<section id="overview-of-the-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="overview-of-the-linear-regression">Overview of the Linear Regression</h3>
<ul>
<li>Linear regression analysis is a predictive modelling technique used for building mathematical and statistical models that characterize relationships between a dependent (continuous) variable and one or more independent, or explanatory variables (continuous or categorical), all of which are numerical.</li>
<li>This technique is useful in forecasting, time series modelling, and finding the causal effect between variables.</li>
<li>Simple linear regression involves one <em>explanatory variable</em> and one <em>response variable</em>.
<ul>
<li>Explanatory variable: The variable used to explain the dependent variable, usually denoted by X. Also known as an independent variable or a predictor variable.</li>
<li>Response variable: The variable we wish to explain, usually denoted by Y. Also known as a dependent variable or outcome variable.</li>
</ul></li>
<li>Multiple linear regression involves two or more <em>explanatory</em> variables, while still only one <em>response</em> variable.</li>
</ul>
</section>
<section id="examples-of-independent-and-dependent-variables" class="level3">
<h3 class="anchored" data-anchor-id="examples-of-independent-and-dependent-variables">Examples of Independent and Dependent Variables</h3>
<ul>
<li>Example Question: Does increasing the marketing budget lead to higher sales revenue?
<ul>
<li>Independent Variable: Marketing budget (how much money is spent on advertising and promotions).</li>
<li>Dependent Variable: Sales revenue (how much income the business generates from sales).</li>
</ul></li>
<li>Example Question: Does additional training improve employee productivity?
<ul>
<li>Independent Variable: Hours of employee training.</li>
<li>Dependent Variable: Employee productivity (e.g., units produced per hour or sales closed per month).</li>
</ul></li>
<li>Example Question: Does being a member of a loyalty program increase the frequency of repeat purchases?
<ul>
<li>Independent Variable: Participation in a loyalty program (whether a customer is a member or not).</li>
<li>Dependent Variable: Number of repeat purchases by the customer.</li>
</ul></li>
</ul>
</section>
<section id="estimating-using-a-simple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimating-using-a-simple-linear-regression-model">Estimating Using a Simple Linear Regression Model</h3>
<ul>
<li>While the correlation coefficient may establish a linear relationship, it does not suggest that one variable <em>causes</em> the other.</li>
<li>With regression analysis, we explicitly assume that the response variable is influenced by other explanatory variables.</li>
<li>Using regression analysis, we may <em>predict</em> the response variable given values for our explanatory variables.</li>
</ul>
</section>
<section id="inexact-relationships" class="level3">
<h3 class="anchored" data-anchor-id="inexact-relationships">Inexact Relationships</h3>
<ul>
<li>If the value of the response variable is uniquely determined by the values of the explanatory variables, we say that the relationship is deterministic.
<ul>
<li>But if, as we find in most fields of research, that the relationship is inexact due to omission of relevant factors, we say that the relationship is inexact.</li>
<li>In regression analysis, we include a stochastic error term, that acknowledges that the actual relationship between the response and explanatory variables is not deterministic.</li>
</ul></li>
</ul>
</section>
<section id="regression-as-anova" class="level3">
<h3 class="anchored" data-anchor-id="regression-as-anova">Regression as ANOVA</h3>
<ul>
<li>ANOVA conducts an F - test to determine whether variation in Y is due to varying levels of X.</li>
<li>ANOVA is used to test for significance of regression:
<ul>
<li><span class="math inline">\(H_0\)</span>: population slope coefficient <span class="math inline">\(\beta_1\)</span> <span class="math inline">\(=\)</span> 0</li>
<li><span class="math inline">\(H_A\)</span>: population slope coefficient <span class="math inline">\(\beta_1\)</span> <span class="math inline">\(\neq\)</span> 0</li>
</ul></li>
<li>R reports the p-value (Significant F).</li>
<li>Rejecting <span class="math inline">\(H_0\)</span> indicates that X explains variation in Y.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch9/LinearReg.png" title="Linear Regression Models" class="img-fluid figure-img"></p>
<figcaption>Linear Regression Models</figcaption>
</figure>
</div>
</section>
</section>
<section id="the-simple-linear-regression-model" class="level1">
<h1>The Simple Linear Regression Model</h1>
<ul>
<li>The simple linear regression model is defined as <span class="math inline">\(y= \beta_0+\beta_1 𝑥+\varepsilon_1\)</span>, where <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> are the response and explanatory variables, respectively and <span class="math inline">\(\varepsilon_1\)</span> is the random error term. <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the unknown parameters to be estimated.</li>
<li>By fitting our data to the model, we obtain the equation <span class="math inline">\(\hat{y} = b_0 + b_1*x\)</span>, where <span class="math inline">\(\hat{y}\)</span> is the estimated response variable, <span class="math inline">\(b_0\)</span> is the estimate of <span class="math inline">\(\beta_0\)</span> (Intercept) and <span class="math inline">\(b_1\)</span> is the estimate of <span class="math inline">\(\beta_1\)</span> (Slope).</li>
<li>Sometimes, this equation can be represented using different variable names like <span class="math inline">\(y=mx+b\)</span> This is the same equation as above, but different notation.</li>
<li>Since the predictions cannot be totally accurate, the difference between the predicted and actual value represents the residual <span class="math inline">\(e=y-\hat{y}\)</span>.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch9/RegressEquation.png" title="Regression Equation" class="img-fluid figure-img"></p>
<figcaption>Regression Equation</figcaption>
</figure>
</div>
<section id="the-least-squares-estimates" class="level3">
<h3 class="anchored" data-anchor-id="the-least-squares-estimates">The Least Squares Estimates</h3>
<ul>
<li>The two parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are estimated by minimizing the sum of squared residuals.
<ul>
<li>The slope coefficient <span class="math inline">\(\beta_1\)</span> is estimated as <span class="math inline">\(b_1 = \sum(x_i-\bar{x}*y_i-\bar{y})/\sum(x_i-\bar{x})^2\)</span></li>
<li>The intercept parameter <span class="math inline">\(\beta_0\)</span> is estimated as <span class="math inline">\(b_0 = \hat{y}-b_1*\bar{x}\)</span></li>
<li>And we use this information to make the regression equation given the formula above: <span class="math inline">\(\hat{y} = b_0 + b_1*x\)</span>,</li>
</ul></li>
</ul>
</section>
<section id="goodness-of-fit" class="level3">
<h3 class="anchored" data-anchor-id="goodness-of-fit">Goodness of Fit</h3>
<ul>
<li>Goodness of fit refers to how well the data fit the regression line. I will introduce three measures to judge how well the sample regression fits the data.
<ol type="1">
<li>Standard Error of the Estimate</li>
<li>The Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</li>
<li>The Adjusted <span class="math inline">\(R^2\)</span></li>
</ol></li>
<li>In order to make sense of the goodness of fit measures, we need to go back to the idea of explained and unexplained variance we learned in the ANOVA lesson. Variance can also be known as a difference.<br>
</li>
<li>Unexplained Variance = SSE or Sum of Squares Error: This equals the sum of squared difference between A and B, or between the sum of squares of the difference between observation (<span class="math inline">\(y_i\)</span>) and our predicted value of y (<span class="math inline">\(\hat{y}\)</span>).
<ul>
<li><span class="math inline">\(SSE = \sum^n_{i=1}(y_i - \hat{y})^2\)</span></li>
</ul></li>
<li>Explained Variance = SSR or Sum of Squares Regression: This equals the sum of squared difference between B and C, or between the sum of squares of the difference between our predicted value (<span class="math inline">\(\hat{y}\)</span>) and the mean of y (<span class="math inline">\(\bar{y}\)</span>).
<ul>
<li><span class="math inline">\(SSR = \sum^n_{i=1}(\hat{y} - \bar{y})^2\)</span></li>
</ul></li>
<li>Total Variance = SST or Total Sum of Squares: This equals the sum of squared difference between A and C, or between the sum of squares of the difference between observation (<span class="math inline">\(y_i\)</span>) and the mean of y (<span class="math inline">\(\bar{y}\)</span>).
<ul>
<li>The SST can be broken down into two components: the variation explained by the regression equation (the regression sum of squares or SSR) and the unexplained variation (the error sum of squares or SSE).</li>
<li><span class="math inline">\(SST = \sum^n_{i=1}(y_i - \bar{y})^2\)</span></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Pictures/Ch9/SS.png" title="Visualization of Sum of Squares" class="img-fluid figure-img"></p>
<figcaption>Visualization of Sum of Squares (SS)</figcaption>
</figure>
</div>
</section>
<section id="the-standard-error-of-the-estimate" class="level3">
<h3 class="anchored" data-anchor-id="the-standard-error-of-the-estimate">The Standard Error of the Estimate</h3>
<ul>
<li>The Standard Error of the Estimate, also known as the Residual Standard Error (RSE) (and labelled such in R), is the variability between observed (<span class="math inline">\(y_i\)</span>) and predicted (<span class="math inline">\(\hat{y}\)</span>) values, targeting the unexplained variance in the figure above. This measure is a lack of fit of the model to the data.</li>
<li>To compute the standard error of the estimate, we first compute the SSE and the MSE.
<ul>
<li>Sum of Squares Error: <span class="math inline">\(SSE = \sum^n_{i=1}e^2_i = \sum^n_{i=1}(y_i - \hat{y})^2\)</span></li>
<li>Dividing SSE by the appropriate degrees of freedom, n – k – 1, yields the mean squared error:
<ul>
<li>Mean Squared Error: <span class="math inline">\(MSE = SSE/(n-k-1)\)</span></li>
</ul></li>
<li>The square root of the MSE is the standard error of the estimate, se.
<ul>
<li>Standard Error of Estimate: <span class="math inline">\(se = \sqrt(MSE) = \sqrt(SSE/(n-k-1))\)</span></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="the-coefficient-of-determination-r2" class="level3">
<h3 class="anchored" data-anchor-id="the-coefficient-of-determination-r2">The Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</h3>
<ul>
<li><p>Coefficient of determination refers to the percentage of variance in one variable that is accounted for by another variable or by a group of variables.</p></li>
<li><p>This measure of R-squared is a measure of the “fit” of the line to the data.</p></li>
<li><p>The Coefficient of Determination, denoted as <span class="math inline">\(R^2\)</span>, is a statistical measure that indicates the proportion of variance in the dependent variable (<span class="math inline">\(y\)</span>) that is explained by the independent variable(s) (x) in a regression model. It is calculated as: SSR/SST or 1-SSE/SST. *<span class="math inline">\(R^2\)</span> ranges from 0 to 1:</p>
<ul>
<li><span class="math inline">\(R^2\)</span>=0: None of the variance in <span class="math inline">\(y\)</span> is explained by the model.</li>
<li><span class="math inline">\(R^2\)</span>=1: The model explains all the variance in y. A higher <span class="math inline">\(R^2\)</span> indicates a better fit of the model to the data.</li>
</ul></li>
<li><p><span class="math inline">\(R^2\)</span> = 1-SSE/SST where <span class="math inline">\(SSE = \sum^n_{i=1}(y_i - \hat{y})^2\)</span> and <span class="math inline">\(SST = \sum^n_{i=1}(y_i - \bar{y})^2\)</span></p>
<ul>
<li><span class="math inline">\(R^2\)</span> can also be computed by SSR/SST, which provides the same answer as above.</li>
<li>This measure of fit targets both the unexplained and the explained variance.</li>
<li><span class="math inline">\(R^2\)</span> can also be calculated using the formula for Pearson’s r and squaring it. This gives us the same answer.</li>
</ul></li>
<li><p>Pearson’s <span class="math inline">\(r\)</span> is a statistic that indicates the strength and direction of the relationship between two numeric variables that meet certain assumptions.</p>
<ul>
<li>(Pearson’s <span class="math inline">\(r\)</span>)<span class="math inline">\(^2\)</span> = <span class="math inline">\(r^2_{xy} = (cov_{xy}/(s_x*s_y))^2\)</span>.</li>
</ul></li>
<li><p>You need to see how all these formulas relate to see why all these formulas give you the same answer.</p></li>
</ul>
<section id="interpreting-r2" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-r2">Interpreting (<span class="math inline">\(R^2\)</span>)</h4>
<ul>
<li>This measure is easier to interpret over standard error. In particular, the (<span class="math inline">\(R^2\)</span>) quantifies the fraction of variation in the response variable that is explained by changes in the explanatory variables.</li>
<li>The (<span class="math inline">\(R^2\)</span>) gives you a score between 0 and 1. A score of 1 indicates that your Y variable is perfectly explained by your X variable or variables (where we only have one in simple regression).</li>
<li>The <span class="math inline">\(R^2\)</span> measure has strength of determination like the correlation coefficient, only all measures are from 0 to 1.
<ul>
<li>The closer you get to one, the more <em>explained variance</em> we achieve.</li>
<li>A score of 0 indicates that no variance is explained by the X variable or variables. In this case, the variable would not be a significant predictor variable of Y.</li>
<li>Again, the strength of the relationship varies by field, but generally, a .2 to a .5 is considered weak, a .5 to a .8 is considered moderate, and above a .8 is considered strong.</li>
</ul></li>
</ul>
</section>
<section id="r-output" class="level4">
<h4 class="anchored" data-anchor-id="r-output">R Output</h4>
<ul>
<li>We do see the <span class="math inline">\(R^2\)</span> in our R output labelled Multiple R-squared.</li>
</ul>
</section>
<section id="limitations-of-the-coefficient-of-determination-r2" class="level4">
<h4 class="anchored" data-anchor-id="limitations-of-the-coefficient-of-determination-r2">Limitations of The Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</h4>
<ul>
<li>More explanatory variables always result in a higher <span class="math inline">\(R^2\)</span>.</li>
<li>But some of these variables may be unimportant and should not be in the model.</li>
<li>This is only applicable with multiple regression, discussed below.</li>
</ul>
</section>
</section>
<section id="the-adjusted-r2" class="level3">
<h3 class="anchored" data-anchor-id="the-adjusted-r2">The Adjusted <span class="math inline">\(R^2\)</span></h3>
<ul>
<li><p>The Adjusted Coefficient of Determination, denoted as Adjusted <span class="math inline">\(R^2\)</span> modifies <span class="math inline">\(R^2\)</span> to account for the number of predictors in the model relative to the number of data points. It is calculated as Adjusted <span class="math inline">\(R^2 = 1-(1-R^2)*((n-1)/(n-k-1))\)</span>, where where n is the sample size and p is the number of predictors.</p></li>
<li><p>In simple linear regression, <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span> will be very similar since there is only one predictor variable. The Adjusted <span class="math inline">\(R^2\)</span> becomes more important in multiple regression, where adding more predictors can artificially inflate <span class="math inline">\(R^2\)</span>.</p></li>
<li><p>The Adjusted <span class="math inline">\(R^2\)</span> tries to balance the raw explanatory power against the desire to include only important predictors.</p>
<ul>
<li>Adjusted <span class="math inline">\(R^2 = 1-(1-R^2)*((n-1)/(n-k-1))\)</span>.</li>
<li>The Adjusted <span class="math inline">\(R^2\)</span> penalizes the <span class="math inline">\(R^2\)</span> for adding additional explanatory variables.</li>
</ul></li>
</ul>
<section id="r-output-1" class="level4">
<h4 class="anchored" data-anchor-id="r-output-1">R Output</h4>
<ul>
<li>With our other goodness-of-fit measures, we typically allow the computer to compute the Adjusted <span class="math inline">\(R^2\)</span> using commands in R.<br>
</li>
<li>Therefore, we do see the Adjusted <span class="math inline">\(R^2\)</span> in our R output labelled Adjusted R-squared.</li>
</ul>
</section>
</section>
<section id="example-of-simple-linear-regression-in-r" class="level3">
<h3 class="anchored" data-anchor-id="example-of-simple-linear-regression-in-r">Example of Simple Linear Regression in R</h3>
<ul>
<li><p>The broad steps are the same as we used in the hypothesis testing and ANOVA modules: 1. Set up the hypothesis. 2. Compute the test statistic and calculate probability. 3. Interpret results and write a conclusion.</p></li>
<li><p>Step 1: Set Up the Null and Alternative Hypothesis</p></li>
<li><p><span class="math inline">\(H_0\)</span>: The slope of the line is equal to zero.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: The slope of the line is not equal to zero.</p></li>
<li><p>Step 2: Compute the Test Statistic and Calculate Probability</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Debt_Payments <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/DebtPayments.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(Debt <span class="sc">~</span> Income, <span class="at">data =</span> Debt_Payments)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Debt ~ Income, data = Debt_Payments)

Residuals:
     Min       1Q   Median       3Q      Max 
-107.087  -38.767   -5.828   50.137  101.619 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  210.298     91.339   2.302   0.0303 *  
Income        10.441      1.222   8.544 9.66e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 63.26 on 24 degrees of freedom
Multiple R-squared:  0.7526,    Adjusted R-squared:  0.7423 
F-statistic:    73 on 1 and 24 DF,  p-value: 9.66e-09</code></pre>
</div>
</div>
<ul>
<li>Step 3: Interpret the Probability and Write a Conclusion</li>
<li>We interpret the probability and write a conclusion after looking at the following:</li>
</ul>
<ol type="1">
<li>Goodness of Fit Measures</li>
<li>The F-test statistic</li>
<li>The p-value from the hypothesis</li>
</ol>
<ul>
<li>We then can interpret the hypothesis and make the regression equation if needed to make predictions.</li>
</ul>
<section id="examining-the-goodness-of-fit-measures" class="level4">
<h4 class="anchored" data-anchor-id="examining-the-goodness-of-fit-measures">Examining the Goodness of Fit Measures</h4>
<ul>
<li><p>Like the ANOVA, we need the summary() command to see the regression output.</p></li>
<li><p>This output includes the following:</p>
<ul>
<li>Standard Error of Estimate at 63.26</li>
<li>a <span class="math inline">\(R^2\)</span> of 0.7526.</li>
<li>an Adjusted <span class="math inline">\(R^2\)</span> of 0.7423</li>
</ul></li>
<li><p>We do not really see a difference in <span class="math inline">\(R^2\)</span> and the Adjusted <span class="math inline">\(R^2\)</span> because we only have a simple linear regression, which includes one X. The other thing that could create a difference between these measures is having a small sample size. A small sample size could adjust the <span class="math inline">\(R^2\)</span> down (like it did a little here <span class="math inline">\(n=28\)</span>). In both cases, a score around .75 indicates that we are explaining about 75% of the variance in Debt Payments, which is specifically stated as 75.26% in the <span class="math inline">\(R^2\)</span> value.</p></li>
<li><p>The Standard Error of Estimate - known in R as the RSE or Residual Standard Error at 63.26.</p></li>
<li><p>The RSE represents the average amount by which the observed values deviate from the predicted values</p></li>
<li><p>The RSE has the same units as the dependent variable y, making it directly interpretable in the context of the problem.</p>
<ul>
<li>The scale of income is in 1000s.</li>
<li>Therefore, for every 1000 dollars difference in Income we could be off on our debt payments by 63.26 dollars.</li>
</ul></li>
<li><p>Again, most statisticians interpret the <span class="math inline">\(R^2\)</span> and the adjusted <span class="math inline">\(R^2\)</span> over the RSE.</p></li>
</ul>
</section>
<section id="examining-the-f-test-statistic" class="level4">
<h4 class="anchored" data-anchor-id="examining-the-f-test-statistic">Examining the F-Test Statistic</h4>
<ul>
<li>The F-statistic is a ratio of explained information (in the numerator) to unexplained information (in the denominator). If a model explains more than it leaves unexplained, the numerator is larger and the F-statistic is greater than 1. F-statistics that are much greater than 1 are explaining much more of the variation in the outcome than they leave unexplained. Large F-statistics are more likely to be statistically significant.</li>
<li>We see a F-statistic in our output with a p-value of 9.66e-09, which is less than .05. This indicates that our overall model is significant, which in simple regression means that our one X predictor variable is also significant. If this F-statistic is significant, we can interpret the hypothesis.</li>
</ul>
</section>
<section id="examining-the-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="examining-the-hypothesis">Examining the Hypothesis</h4>
<ul>
<li>We see a p-value on the Income row of 9.66e-09 from a t-value. This is also significant at .05 level. This p-value is the same as the F-test statistic because we only have one X variable.</li>
<li>This significance means our predictor variable does influence the Y variable and that we can reject the null hypothesis and show support for our alternative hypothesis.</li>
<li>This means Income does influence Debt Payments.</li>
</ul>
</section>
<section id="interpreting-the-hypothesis" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-hypothesis">Interpreting the Hypothesis</h4>
<ul>
<li>A <span class="math inline">\(b_1\)</span> estimate of 10.441 indicates that for 1000 dollars of Income (again our data is in 1000s), the payment of dept will increase by 10.441.</li>
<li>A <span class="math inline">\(b_0\)</span> estimate of 210.298 indicates where the regression line will start given a Y at 0.
<ul>
<li>This gives us a regression equation at <span class="math inline">\(\hat{y} = 210.298 + 10.441*Income\)</span></li>
<li>We can graph this regression line using the abline() command on our plot we did earlier.</li>
<li>As you can see from the chart, there was no data at the Y intercept, but if I extend the chart out, it does hit the y axis at 210 like stated.</li>
<li>Also from the chart, we note that for each unit of income we go to the right, we go up by 10.441 units in dept payments.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Debt <span class="sc">~</span> Income, <span class="at">data =</span> Debt_Payments, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">120</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1350</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(Simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" alt="Scatterplot of Debt_Payments" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="predictions" class="level3">
<h3 class="anchored" data-anchor-id="predictions">Predictions</h3>
<ul>
<li>We can calculate this using the regression equation or use the predict() command in order to calculate different values of y given values of x based on our regression equation we got in the step above.</li>
<li>The coef() function returns the model’s coefficients which are needed to make the regression equation.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What would be your debt payments if Income was 100 ( for 100,000)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(Simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      Income 
  210.29768    10.44111 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fl">210.298</span> <span class="sc">+</span> <span class="fl">10.441</span> <span class="sc">*</span> (<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1254.398</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(Simple, <span class="fu">data.frame</span>(<span class="at">Income =</span> <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
1254.408 </code></pre>
</div>
</div>
</section>
</section>
<section id="multiple-regression" class="level1">
<h1>Multiple Regression</h1>
<ul>
<li><p>A key advantage of multiple regression over simple regression is that it allows us to <em>control</em> for other variables. When we include multiple predictors, each coefficient reflects the unique contribution of that variable <em>while holding all others constant</em>. This makes our model more realistic and our estimates more accurate — but it also means we need to be careful about which variables we include, since adding unnecessary predictors can introduce noise and obscure the relationships we care about.</p></li>
<li><p>Multiple regression allows us to explore how several <em>explanatory</em> variables influence the <em>response</em> variable.</p></li>
<li><p>Suppose there are <span class="math inline">\(k\)</span> explanatory variables. The multiple linear regression model is defined as: <span class="math inline">\(y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \ ⋯ + \beta_kx_k +\varepsilon\)</span></p></li>
<li><p>Where:</p>
<ul>
<li><span class="math inline">\(y\)</span> is the dependent variable,</li>
<li><span class="math inline">\(x_1, ⋯, x_k\)</span> are independent explanatory variables,</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept term,</li>
<li><span class="math inline">\(\beta_1 ⋯, \beta_k\)</span> are the regression coefficients for the independent variables,</li>
<li><span class="math inline">\(\varepsilon\)</span> is the random error term</li>
</ul></li>
<li><p>We estimate the regression coefficients—called partial regression coefficients — <span class="math inline">\(b_0, b_1, b_2,… b_k\)</span>, then use the model: <span class="math inline">\(\hat{y} = b_0 + b_1x_1 + b_2x_2 + \ ... + b_kx_k\)</span> .</p></li>
<li><p>The partial regression coefficients represent the expected change in the dependent variable when the associated independent variable is increased by one unit while the values of all other independent variables are held constant.</p></li>
<li><p>For example, if there are <span class="math inline">\(k = 3\)</span> explanatory variables, the value <span class="math inline">\(b_1\)</span> estimates how a change in <span class="math inline">\(x_1\)</span> will influence <span class="math inline">\(y\)</span> assuming <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span> are held constant.</p></li>
</ul>
<section id="example-of-multiple-linear-regression-in-r" class="level3">
<h3 class="anchored" data-anchor-id="example-of-multiple-linear-regression-in-r">Example of Multiple Linear Regression in R</h3>
<ul>
<li>The steps to multiple linear regression are the same as simple linear regression except we should have more than one hypothesis.</li>
</ul>
<ol type="1">
<li>Step 1: Set up the null and alternative hypotheses</li>
</ol>
<ul>
<li>Hypothesis 1: Income affects Debt Payments.
<ul>
<li><span class="math inline">\(H_0\)</span>: The slope of the line in regards to Income is equal to zero.</li>
<li><span class="math inline">\(H_A\)</span>: The slope of the line in regards to Income is not equal to zero.</li>
</ul></li>
<li>Hypothesis 2: Unemployment affects Debt Payments.
<ul>
<li><span class="math inline">\(H_0\)</span>: The slope of the line in regards to Unemployment is equal to zero.</li>
<li><span class="math inline">\(H_A\)</span>: The slope of the line in regards to Unemployment is not equal to zero.</li>
</ul></li>
</ul>
<ol start="2" type="1">
<li>Step 2: Compute the test statistic and calculate probability</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Debt_Payments <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/DebtPayments.csv"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(Debt <span class="sc">~</span> Income <span class="sc">+</span> Unemployment, <span class="at">data =</span> Debt_Payments)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Multiple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Debt ~ Income + Unemployment, data = Debt_Payments)

Residuals:
     Min       1Q   Median       3Q      Max 
-110.456  -38.454   -5.836   51.156  102.121 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  198.9956   156.3619   1.273    0.216    
Income        10.5122     1.4765   7.120 2.98e-07 ***
Unemployment   0.6186     6.8679   0.090    0.929    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 64.61 on 23 degrees of freedom
Multiple R-squared:  0.7527,    Adjusted R-squared:  0.7312 
F-statistic:    35 on 2 and 23 DF,  p-value: 1.054e-07</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Step 3: Interpret the probability and write a conclusion</li>
</ol>
<ul>
<li>We interpret the probability and write a conclusion after looking at the following:
<ul>
<li>Goodness of Fit Measures</li>
<li>The F-test statistic</li>
<li>The p-values from the hypotheses</li>
</ul></li>
<li>We then can interpret the hypotheses and make the regression equation if needed to make predictions.</li>
</ul>
</section>
<section id="examining-the-goodness-of-fit-measures-1" class="level3">
<h3 class="anchored" data-anchor-id="examining-the-goodness-of-fit-measures-1">Examining the Goodness of Fit Measures</h3>
<ul>
<li>Like the ANOVA, we need the summary() command to see the regression output.</li>
<li>This output includes the following:
<ul>
<li>Standard error of estimate at 64.61 - was previously 63.26 with simple regression.</li>
<li>a <span class="math inline">\(R^2\)</span> of 0.7527 - was previously 0.7526 with simple regression.</li>
<li>an Adjusted <span class="math inline">\(R^2\)</span> of 0.7312 - was previously 0.7423 with simple regression.</li>
</ul></li>
<li>Looking at the goodness of fit indices, they suggest that we are not explaining anything more by adding the unemployment variable over what we had with the Income variable. Our RSE and <span class="math inline">\(R^2\)</span> are about the same, and our adjusted <span class="math inline">\(R^2\)</span> has gone down - again paying the price for including an unnecessary variable.</li>
</ul>
</section>
<section id="examining-the-f-test-statistic-1" class="level3">
<h3 class="anchored" data-anchor-id="examining-the-f-test-statistic-1">Examining the F-Test Statistic</h3>
<ul>
<li>We see a overall F-statistic in our output with a p-value of 1.054e-07, which is less than .05. This indicates that our overall model is significant - which in multiple regression means that <em>at least one</em> X predictor variable is significant. If this F-statistic is significant, we can interpret the hypotheses.</li>
</ul>
</section>
<section id="examining-the-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="examining-the-hypotheses">Examining the Hypotheses</h3>
<ul>
<li>Hypothesis 1: The output shows a p-value on the Income row of 2.98e-07 from a t-value. This was significant in our simple regression model, and is still significant at .05 level here. This significance means our predictor variable does influence the Y variable and that we can reject the null hypothesis and show support for our alternative hypothesis.</li>
<li>Hypothesis 2: The output shows a p-value on the Unemployment row of 0.929 from a t-value. This is <em>NOT</em> significant at any appropriate level of alpha. This lack of significance means our predictor variable does <em>NOT</em> influence the Y variable and that we fail to reject the null hypothesis that there is a slope.</li>
</ul>
</section>
<section id="interpreting-the-hypothesis-1" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-hypothesis-1">Interpreting the Hypothesis</h3>
<ul>
<li>Because Unemployment is not significant, we should drop it from the model before creating the regression equation. The extra variable is only adding <em>noise</em> to our model and not adding anything useful in understanding debt payments.</li>
</ul>
</section>
<section id="the-p-value-method" class="level2">
<h2 class="anchored" data-anchor-id="the-p-value-method">The P-value Method</h2>
<ul>
<li><p>When you have a lot of predictors, it can be difficult to come up with a good model.</p></li>
<li><p>A common criteria is to remove based on the highest p-value.</p></li>
<li><p>Remove indicators until all variables are significant, and none are insignificant.</p></li>
<li><p>As we drop variables, we also want to keep an eye on the adjusted R-Squared to make sure it does not significantly decrease. It should stay about the same if we drop variables that are not helpful in understanding the model, and could improve because we are decreasing the number of variables being evaluated.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Credit"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Credit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   400 obs. of  12 variables:
 $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Income   : num  14.9 106 104.6 148.9 55.9 ...
 $ Limit    : int  3606 6645 7075 9504 4897 8047 3388 7114 3300 6819 ...
 $ Rating   : int  283 483 514 681 357 569 259 512 266 491 ...
 $ Cards    : int  2 3 4 3 2 4 2 2 5 3 ...
 $ Age      : int  34 82 71 36 68 77 37 87 66 41 ...
 $ Education: int  11 15 11 11 16 10 12 9 13 19 ...
 $ Gender   : Factor w/ 2 levels " Male","Female": 1 2 1 2 1 1 2 1 2 2 ...
 $ Student  : Factor w/ 2 levels "No","Yes": 1 2 1 1 1 1 1 1 1 2 ...
 $ Married  : Factor w/ 2 levels "No","Yes": 2 2 1 1 2 1 1 1 1 2 ...
 $ Ethnicity: Factor w/ 3 levels "African American",..: 3 2 2 2 3 3 1 2 3 1 ...
 $ Balance  : int  333 903 580 964 331 1151 203 872 279 1350 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Removing variables that are of no interest to the model based on</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="do">## what we have learned so far.  The following lines removes the</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="do">## categorical variables, Gender, Student, Married, and Ethnicity. It</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="do">## also removed the ID because that is not a helpful variable.</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>Credit <span class="ot">&lt;-</span> <span class="fu">select</span>(Credit, <span class="sc">-</span>Gender, <span class="sc">-</span>Student, <span class="sc">-</span>Married, <span class="sc">-</span>Ethnicity, <span class="sc">-</span>ID)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>creditlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> ., <span class="at">data =</span> Credit)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Balance ~ ., data = Credit)

Residuals:
    Min      1Q  Median      3Q     Max 
-227.25 -113.15  -42.06   45.82  542.97 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -477.95809   55.06529  -8.680  &lt; 2e-16 ***
Income        -7.55804    0.38237 -19.766  &lt; 2e-16 ***
Limit          0.12585    0.05304   2.373  0.01813 *  
Rating         2.06310    0.79426   2.598  0.00974 ** 
Cards         11.59156    7.06670   1.640  0.10174    
Age           -0.89240    0.47808  -1.867  0.06270 .  
Education      1.99828    2.59979   0.769  0.44257    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 161.6 on 393 degrees of freedom
Multiple R-squared:  0.8782,    Adjusted R-squared:  0.8764 
F-statistic: 472.5 on 6 and 393 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple R-squared: 0.8782, Adjusted R-squared: 0.8764</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Education has the highest p-value, so it is removed from analysis. We use the minus sign to remove the variable in the lm function.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>creditlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> . <span class="sc">-</span> Education, <span class="at">data =</span> Credit)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Balance ~ . - Education, data = Credit)

Residuals:
    Min      1Q  Median      3Q     Max 
-231.37 -113.46  -39.55   41.66  544.35 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -449.36101   40.57409 -11.075   &lt;2e-16 ***
Income        -7.56211    0.38214 -19.789   &lt;2e-16 ***
Limit          0.12855    0.05289   2.430   0.0155 *  
Rating         2.02240    0.79208   2.553   0.0110 *  
Cards         11.55272    7.06285   1.636   0.1027    
Age           -0.88832    0.47781  -1.859   0.0638 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 161.6 on 394 degrees of freedom
Multiple R-squared:  0.8781,    Adjusted R-squared:  0.8765 
F-statistic: 567.4 on 5 and 394 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple R-squared: 0.8781, Adjusted R-squared: 0.8765</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Cards has the next highest p-value, so it is removed from analysis using the - minus sign format.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>creditlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> . <span class="sc">-</span> Education <span class="sc">-</span> Cards, <span class="at">data =</span> Credit)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Balance ~ . - Education - Cards, data = Credit)

Residuals:
    Min      1Q  Median      3Q     Max 
-249.62 -110.89  -39.98   51.87  546.52 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -445.10477   40.57635 -10.970  &lt; 2e-16 ***
Income        -7.61268    0.38169 -19.945  &lt; 2e-16 ***
Limit          0.08183    0.04461   1.834   0.0674 .  
Rating         2.73142    0.66435   4.111 4.79e-05 ***
Age           -0.85612    0.47841  -1.789   0.0743 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 161.9 on 395 degrees of freedom
Multiple R-squared:  0.8772,    Adjusted R-squared:  0.876 
F-statistic: 705.6 on 4 and 395 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple R-squared: 0.8772, Adjusted R-squared: 0.876</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Age is next to be removed because it has the next highest p-value at .06270.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>creditlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> . <span class="sc">-</span> Education <span class="sc">-</span> Cards <span class="sc">-</span> Age, <span class="at">data =</span> Credit)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Balance ~ . - Education - Cards - Age, data = Credit)

Residuals:
    Min      1Q  Median      3Q     Max 
-260.93 -113.14  -36.27   49.35  554.23 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -489.72748   32.09892 -15.257  &lt; 2e-16 ***
Income        -7.71931    0.37806 -20.418  &lt; 2e-16 ***
Limit          0.08467    0.04471   1.894    0.059 .  
Rating         2.69858    0.66594   4.052 6.11e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 162.4 on 396 degrees of freedom
Multiple R-squared:  0.8762,    Adjusted R-squared:  0.8753 
F-statistic: 934.6 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple R-squared: 0.8762, Adjusted R-squared: 0.8753</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Finally Limit is the next to be removed because it has the next highest (and still insignificant) p-value at .059.</p></li>
<li><p>Age is next to be removed because it has the next highest p-value at .06270.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>creditlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Balance <span class="sc">~</span> . <span class="sc">-</span> Education <span class="sc">-</span> Cards <span class="sc">-</span> Age <span class="sc">-</span> Limit, <span class="at">data =</span> Credit)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Balance ~ . - Education - Cards - Age - Limit, data = Credit)

Residuals:
    Min      1Q  Median      3Q     Max 
-278.57 -112.69  -36.21   57.92  575.24 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -534.81215   21.60270  -24.76   &lt;2e-16 ***
Income        -7.67212    0.37846  -20.27   &lt;2e-16 ***
Rating         3.94926    0.08621   45.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 162.9 on 397 degrees of freedom
Multiple R-squared:  0.8751,    Adjusted R-squared:  0.8745 
F-statistic:  1391 on 2 and 397 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple R-squared: 0.8751,Adjusted R-squared: 0.8745</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>In our original model with non-helpful insignificant predictors, we had an adjusted R-Squared at 0.8764. After removing insignificant predictors, we are only down to .8745. This means we can explain someones Balance best by understanding Income and Rating.</li>
<li>The interpretation is as follows:</li>
<li>A one unit change in Income causes a negative 7.67 change in Balance.</li>
<li>A one unit change in Rating causes a 3.949 change in Balance.</li>
</ul>
</section>
<section id="multicollinerity" class="level2">
<h2 class="anchored" data-anchor-id="multicollinerity">Multicollinerity</h2>
<ul>
<li>Multicollinearity refers to the situation in which two or more predictor variables are closely related to another.</li>
<li>Collinearity can cause significant factors to be insignificant, or insignificant factors to seem significant. Both are problematic.</li>
<li>If sample correlation coefficient between 2 explanatory variables is more than .80 or less than -.80, we could have severe multicollinearity. Seemingly wrong signs of estimated regression coefficients may also indicate multicollinearity. A good remedy may be to simply drop one of the collinear variables if we can justify it as redundant.</li>
<li>Alternatively, we could try to increase our sample size.</li>
<li>Another option would be to try to transform our variables so that they are no longer collinear.</li>
<li>Last, especially if we are interested only in maintaining a high predictive power, it may make sense to do nothing.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Credit<span class="sc">$</span>Income, Credit<span class="sc">$</span>Rating)  <span class="do">##close to .8, but still under</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7913776</code></pre>
</div>
</div>
<ul>
<li>The second way to tell if there is multicollinearity is to use the vif() command from the car package.</li>
<li>The vif() function in R is used to calculate the Variance Inflation Factor (VIF) for each predictor variable in a multiple regression model. The VIF quantifies how much the variance of a regression coefficient is inflated due to multicollinearity among the predictors. High VIF values indicate high multicollinearity, which can affect the stability and interpretability of the regression coefficients.</li>
<li>We want all scores to be under 10 to indicate the absence of problematic multicollinerity in our model.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)  <span class="do">##need to have car package installed first. </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Place regression model object in the function to see vif scores.</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(creditlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Income  Rating 
2.67579 2.67579 </code></pre>
</div>
</div>
<ul>
<li>While statisticians differ on what constitutes, the general consensus is that scores need to be under 5 or 10.</li>
<li>Both scores are under 10, so we do have an absence of multicollinerity in our final model.
<ul>
<li>VIF = 1: No correlation between the predictor and the other predictors.</li>
<li>1 &lt; VIF &lt; 5: Moderate correlation but not severe enough to require correction. Scores less than 5 pass assumption.</li>
<li>5 &lt; VIF &lt; 10: High correlation, indicating potential multicollinearity problems. We keep an eye on this issue, but pass the assumption.</li>
<li>VIF &gt;= 10: High correlation, indicating multicollinearity problems. Fail assumption.</li>
</ul></li>
</ul>
<section id="section" class="level41">
<p class="heading"></p>
</section>
</section>
</section>
<section id="regression-with-categorical-variables" class="level1">
<h1>Regression with Categorical Variables</h1>
<ul>
<li><p>Simple and multiple regression both require a continuous dependent variable (y). However, the predictor variables (x) can be categorical or continuous. If you were to have a y/x pairing with a continuous y and a categorical x, you might as well choose to run an ANOVA from the last module or a t-test if there are only 2 categories. However, if you have a more complex model, or need to try a variety of models, multiple regression allows for you to seamlessly add and delete predictor variables (both categorical and continuous).</p></li>
<li><p>We often have categorical predictors in modeling settings. And it might not make sense to think about a “one unit increase” in a categorical variable. In regression settings, we can account for categorical variables by creating dummy variables, which are indicator variables for certain conditions happening. When considering categorical variables, one variable is taken to be the baseline or reference value. All other categories will be compared to it.</p></li>
<li><p>Regression analysis requires numerical data.</p></li>
<li><p>Ordinal variables can be represented by a number in one column when there is even distance between the categories.</p>
<ul>
<li>From strongly disagree to disagree to N/A to agree to strongly agree. Each 1 unit change considers the same distance between points.</li>
<li>A weighted scale would go from strongly disagree to neither to agree to strongly agree to agree all the time.</li>
<li>Need to manually code these and coerce into a number.</li>
<li>Some ordinal variables need to use dummy coding in R (i.e., Seasonality). Need to always check rationale before blindly recoding to numbers, or using numbers that were provided.</li>
</ul></li>
<li><p>Nominal categorical data can be included as independent variables, but must be coded numeric using dummy variables.</p>
<ul>
<li>R will create the dummy variables automatically in a regression using the lm() command.</li>
<li>For variables with 2 categories, code as 0 and 1.</li>
</ul></li>
</ul>
<section id="dummy-variables-with-more-than-2-categories" class="level2">
<h2 class="anchored" data-anchor-id="dummy-variables-with-more-than-2-categories">Dummy Variables with More than 2 Categories</h2>
<ul>
<li>Like in an ANOVA test, a categorical variable may be defined by more than two categories.</li>
<li>Use multiple dummy variables to capture all categories, one for each category.</li>
<li>When a categorical variable has k &gt; 2 levels, we need to add k − 1 additional variables to the model.</li>
<li>Given the intercept term, we exclude one of the dummy variables from the regression.
<ul>
<li>The excluded variable represents the reference category.</li>
<li>Including all dummy variables creates perfect multicollinearity (which is an assumption discussed in your textbook).</li>
</ul></li>
<li>Example: mode of transportation with three categories
<ul>
<li>Public transportation, driving alone, or car pooling
<ul>
<li><span class="math inline">\(d_1=1\)</span> for public transportation and 0 otherwise</li>
<li><span class="math inline">\(d_2=1\)</span> for driving alone and 0 otherwise</li>
<li><span class="math inline">\(d_1=d_2=0\)</span> indicates car pooling</li>
</ul></li>
</ul></li>
<li>Slope estimates of categorical data cannot be evaluated the same way. In the example below, since Gender is nominal, and because we are using regression, we should use dummy variables to process this factor in the regression instead of the method above. We can use this technique for ordinal variables to recode them into numeric. Again, R does this coding on our behalf using the lm() command.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take a vector representing gender</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"MALE"</span>, <span class="st">"FEMALE"</span>, <span class="st">"FEMALE"</span>, <span class="st">"UNKNOWN"</span>, <span class="st">"MALE"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># One way is to convert the data into numerical in the column using</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ifelse statements.</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(gender <span class="sc">==</span> <span class="st">"MALE"</span>, <span class="dv">1</span>, <span class="fu">ifelse</span>(gender <span class="sc">==</span> <span class="st">"FEMALE"</span>, <span class="dv">2</span>, <span class="dv">99</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  2  2 99  1</code></pre>
</div>
</div>
</section>
<section id="example-using-dummy-variables" class="level2">
<h2 class="anchored" data-anchor-id="example-using-dummy-variables">Example Using Dummy Variables</h2>
<ul>
<li>Suppose that we are forecasting and we want to account for the month as a predictor.</li>
<li>Then the following dummy variables can be created the following way:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/months.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   132 obs. of  3 variables:
 $ Month: Factor w/ 12 levels "Apr","Aug","Dec",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Year : int  2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 ...
 $ Units: int  45420 44558 63844 39338 35000 45747 50923 46786 48696 55000 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Units)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" alt="Boxplot of Sales Data Generated by R" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>I produced a boxplot of the monthly data across units above. April (Apr) is the first month listed (not Jan for January). It alphabetizes it from there from left to right.</li>
<li>Looking at the lm() command summary below, the hypotheses take on the format VariableCategory. So MonthAug corresponds to the Month variable with the Aug category, representing August. You will notice that there is no MonthApr listed. It is considered the referent category and held in the intercept.</li>
<li>The interpretation of each of the coefficients associated with the dummy variables is that it is a measure of the effect of that category relative to the omitted or referent category.</li>
<li>In the example to the left, the intercept coefficient is associated with April, so MonthAug measures the effect of August on the forecast variable (Units) compared to the effect of April.
<ul>
<li>Since the data represents the difference in Units sold in months, we can interpret the predicted units sold for April as 49,580.8.</li>
<li>August was significantly different than April because there is a p-value less than .05. Specifically, we can expect about 7701.6 more units to be sold in August over April. December, January, June, and November also had significantly different Units sold.</li>
<li>February, July, March, May, October, and September are not different than April because the p-value is &gt; .05.</li>
</ul></li>
<li>Never try to remove a categorical variable that is not significant because it means something else - that the category is not different than the referent category. More on this later.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppose that we are forecasting daily data and we want to account</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># for the month as a predictor.  Then the following dummy variables</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># can be created.</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>lmSales <span class="ot">&lt;-</span> <span class="fu">lm</span>(Units <span class="sc">~</span> Month, <span class="at">data =</span> sales)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmSales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Units ~ Month, data = sales)

Residuals:
     Min       1Q   Median       3Q      Max 
-12724.5  -4056.6    -36.3   3620.9  22066.5 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  49580.8     1749.6  28.339  &lt; 2e-16 ***
MonthAug      7701.6     2474.2   3.113  0.00232 ** 
MonthDec     25245.7     2474.2  10.203  &lt; 2e-16 ***
MonthFeb     -3744.7     2474.2  -1.513  0.13279    
MonthJan     -6939.5     2474.2  -2.805  0.00588 ** 
MonthJul      1809.8     2474.2   0.731  0.46592    
MonthJun      4971.5     2474.2   2.009  0.04675 *  
MonthMar      3671.9     2474.2   1.484  0.14042    
MonthMay      3652.1     2474.2   1.476  0.14255    
MonthNov     14205.6     2474.2   5.741 7.21e-08 ***
MonthOct      -125.4     2474.2  -0.051  0.95967    
MonthSep       261.8     2474.2   0.106  0.91590    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5803 on 120 degrees of freedom
Multiple R-squared:  0.6857,    Adjusted R-squared:  0.6569 
F-statistic:  23.8 on 11 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The Intercept absorbs the referent category and so in this case,</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># April is alphabetically first and the referent category.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We can reset the levels by using the factor() command. Shown below, I reset the levels of the month in order from month 1 (Jan) to month 12 (Dec). This puts “Jan” in the referent category when we rerun the regression. This allows us to compare Jan to other months and to specifically, test what months are different from Jan (+ increase in sales from Jan, - a decrease in sales from Jan).</li>
<li>For example, March has 10612 more unit sales than Jan.&nbsp;If not significant, like MonthFeb, then you can interpret as not significantly different than the 42K in Jan.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>sales<span class="sc">$</span>Month <span class="ot">&lt;-</span> <span class="fu">factor</span>(sales<span class="sc">$</span>Month, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Jan"</span>, <span class="st">"Feb"</span>, <span class="st">"Mar"</span>, <span class="st">"Apr"</span>,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"May"</span>, <span class="st">"Jun"</span>, <span class="st">"Jul"</span>, <span class="st">"Aug"</span>, <span class="st">"Sep"</span>, <span class="st">"Oct"</span>, <span class="st">"Nov"</span>, <span class="st">"Dec"</span>))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sales, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Units)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lmSales <span class="ot">&lt;-</span> <span class="fu">lm</span>(Units <span class="sc">~</span> Month, <span class="at">data =</span> sales)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmSales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Units ~ Month, data = sales)

Residuals:
     Min       1Q   Median       3Q      Max 
-12724.5  -4056.6    -36.3   3620.9  22066.5 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    42641       1750  24.373  &lt; 2e-16 ***
MonthFeb        3195       2474   1.291 0.199106    
MonthMar       10612       2474   4.289 3.65e-05 ***
MonthApr        6940       2474   2.805 0.005877 ** 
MonthMay       10592       2474   4.281 3.77e-05 ***
MonthJun       11911       2474   4.814 4.36e-06 ***
MonthJul        8749       2474   3.536 0.000578 ***
MonthAug       14641       2474   5.917 3.17e-08 ***
MonthSep        7201       2474   2.911 0.004302 ** 
MonthOct        6814       2474   2.754 0.006803 ** 
MonthNov       21145       2474   8.546 4.78e-14 ***
MonthDec       32185       2474  13.008  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5803 on 120 degrees of freedom
Multiple R-squared:  0.6857,    Adjusted R-squared:  0.6569 
F-statistic:  23.8 on 11 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The interpretation of each of the coefficients associated with the</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy variables is that it is a measure of the effect of that</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># category relative to the omitted category. In the example to the</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># left, the intercept coefficient is associated with January, so</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># MonthFeb measures the effect of Feb on the forecast variable</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (Units) compared to the effect of Jan.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="example-using-a-continuous-and-categorical-variable" class="level2">
<h2 class="anchored" data-anchor-id="example-using-a-continuous-and-categorical-variable">Example Using a Continuous and Categorical Variable</h2>
<ul>
<li>Let’s do an example with the GNP.csv data set to use GNP and quarterly data to predict Sales (in millions)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>GNP <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/GNP.csv"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(GNP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   40 obs. of  4 variables:
 $ Year   : int  2007 2007 2007 2007 2008 2008 2008 2008 2009 2009 ...
 $ Quarter: int  1 2 3 4 1 2 3 4 1 2 ...
 $ Sales  : int  921266 1013371 1000151 1060394 950268 1028016 999824 957207 828677 905562 ...
 $ GNP    : num  14302 14513 14718 14880 14849 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># #1, 2, 3, 4 represent the quarter and we want that data as</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># categorical</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>GNP<span class="sc">$</span>Quarter <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(GNP<span class="sc">$</span>Quarter)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co"># #Evaluate Quarterly data of GNP in a boxplot.</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>GNP <span class="sc">%&gt;%</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Quarter, <span class="at">y =</span> Sales)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" alt="Boxplot of GNP variable Generated by R" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the linear regression considering GNP and Quarterly data</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>lmGNP <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> GNP <span class="sc">+</span> Quarter, <span class="at">data =</span> GNP)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmGNP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ GNP + Quarter, data = GNP)

Residuals:
   Min     1Q Median     3Q    Max 
-53748 -20083   -700  16341  52626 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -61669.572  52583.805  -1.173    0.249    
GNP             65.055      3.215  20.234  &lt; 2e-16 ***
Quarter2     78278.963  13576.443   5.766 1.57e-06 ***
Quarter3     59960.212  13607.096   4.407 9.49e-05 ***
Quarter4    108765.258  13638.197   7.975 2.21e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30330 on 35 degrees of freedom
Multiple R-squared:  0.9364,    Adjusted R-squared:  0.9291 
F-statistic: 128.7 on 4 and 35 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate y, where y and x are Sales and GNP, and 2 is a quarter 2</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy, 3 is a Quarter 3 dummy, and 4 is a Quarter 4 dummy.</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># All else equal, retail sales in quarter 1 are expected to be</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># approximately $108,765 million less than sales in quarter 4.</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># What are the predicted sales in quarter 2 if GNP is $18,000 (in</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co"># billions)?</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>Quarter2 <span class="ot">&lt;-</span> <span class="dv">18000</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmGNP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          GNP     Quarter2     Quarter3     Quarter4 
-61669.57208     65.05476  78278.96330  59960.21187 108765.25801 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the equation</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">61669.57208</span> <span class="sc">+</span> <span class="fl">65.05476</span> <span class="sc">*</span> Quarter2 <span class="sc">+</span> <span class="fl">78278.963</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1187595</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># When you use the predict() command with a categorical variable, you</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># need to include the predictors with what they equal as shown below.</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># I pulled out the data.frame() command into a new variable named nd</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># to simplify our predict() command later on.</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">GNP =</span> <span class="dv">18000</span>, <span class="at">Quarter =</span> <span class="st">"2"</span>)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmGNP, nd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1 
1187595 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can write the above 2 lines like shown below for the same</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># answer.</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmGNP, <span class="fu">data.frame</span>(<span class="at">GNP =</span> <span class="dv">18000</span>, <span class="at">Quarter =</span> <span class="st">"2"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      1 
1187595 </code></pre>
</div>
</div>
<ul>
<li>While you technically can keep adding categorical variables, you must be careful not to add too many because the intercept becomes increasingly difficult to interpret!</li>
</ul>
</section>
<section id="coffee-example" class="level2">
<h2 class="anchored" data-anchor-id="coffee-example">Coffee Example</h2>
<section id="visualizing" class="level3">
<h3 class="anchored" data-anchor-id="visualizing">Visualizing</h3>
<ul>
<li>Let’s try a bigger example with the coffee dataset.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>coffee <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/coffee.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coffee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1311 obs. of  31 variables:
 $ X                   : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Species             : Factor w/ 1 level "Arabica": 1 1 1 1 1 1 1 1 1 1 ...
 $ Owner               : Factor w/ 306 levels "","acacia hills ltd",..: 206 206 125 302 206 154 137 95 95 75 ...
 $ Country.of.Origin   : Factor w/ 37 levels "","Brazil","Burundi",..: 10 10 11 10 10 2 26 10 10 10 ...
 $ Farm.Name           : Factor w/ 558 levels "","-","1","200 farms",..: 374 374 441 526 374 1 1 19 19 510 ...
 $ ICO.Number          : Factor w/ 843 levels "","-","??","0",..: 455 455 1 1 455 1 1 98 98 454 ...
 $ Company             : Factor w/ 271 levels "","ac la laja sa de cv",..: 169 169 1 264 169 1 208 1 1 88 ...
 $ Number.of.Bags      : int  300 300 5 320 300 100 100 300 300 50 ...
 $ Bag.Weight          : Factor w/ 56 levels "0 kg","0 lbs",..: 47 47 3 47 47 32 51 47 47 47 ...
 $ Harvest.Year        : Factor w/ 47 levels "","08/09 crop",..: 16 16 1 16 16 14 13 41 41 16 ...
 $ Processing.Method   : Factor w/ 6 levels "","Natural / Dry",..: 6 6 1 2 6 2 6 1 1 2 ...
 $ Color               : Factor w/ 5 levels "","Blue-Green",..: 4 4 1 4 4 3 3 1 1 4 ...
 $ Aroma               : num  8.67 8.75 8.42 8.17 8.25 8.58 8.42 8.25 8.67 8.08 ...
 $ Flavor              : num  8.83 8.67 8.5 8.58 8.5 8.42 8.5 8.33 8.67 8.58 ...
 $ Aftertaste          : num  8.67 8.5 8.42 8.42 8.25 8.42 8.33 8.5 8.58 8.5 ...
 $ Acidity             : num  8.75 8.58 8.42 8.42 8.5 8.5 8.5 8.42 8.42 8.5 ...
 $ Body                : num  8.5 8.42 8.33 8.5 8.42 8.25 8.25 8.33 8.33 7.67 ...
 $ Balance             : num  8.42 8.42 8.42 8.25 8.33 8.33 8.25 8.5 8.42 8.42 ...
 $ Uniformity          : num  10 10 10 10 10 10 10 10 9.33 10 ...
 $ Clean.Cup           : num  10 10 10 10 10 10 10 10 10 10 ...
 $ Sweetness           : num  10 10 10 10 10 10 10 9.33 9.33 10 ...
 $ Cupper.Points       : num  8.75 8.58 9.25 8.67 8.58 8.33 8.5 9 8.67 8.5 ...
 $ Moisture            : num  0.12 0.12 0 0.11 0.12 0.11 0.11 0.03 0.03 0.1 ...
 $ Category.One.Defects: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Quakers             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Category.Two.Defects: int  0 1 0 2 2 1 0 0 0 4 ...
 $ unit_of_measurement : Factor w/ 2 levels "ft","m": 2 2 2 2 2 2 2 2 2 2 ...
 $ altitude_low_meters : num  1950 1950 1600 1800 1950 ...
 $ altitude_high_meters: num  2200 2200 1800 2200 2200 NA NA 1700 1700 1850 ...
 $ altitude_mean_meters: num  2075 2075 1700 2000 2075 ...
 $ TotalScore          : num  90.6 89.9 89.8 89 88.8 ...</code></pre>
</div>
</div>
<ul>
<li>Sometimes, we are only interested in 2 or 3 category values. In the following example, I am filtering by Processing Method and creating a ggplot only holding the methods of interest to me.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>coffee <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Processing.Method <span class="sc">==</span> <span class="st">"Natural / Dry"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Washed / Wet"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Processing.Method, <span class="at">y =</span> TotalScore)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Does not look like large group differences, good indication into what we will find.</li>
<li>In the next visualization, lets add in a scatterplot to show the difference between 2 continuous variables (Flavor and TotalScore) using Processing Method method as the color.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>coffee <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Processing.Method <span class="sc">==</span> <span class="st">"Natural / Dry"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Washed / Wet"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Flavor, <span class="at">y =</span> TotalScore, <span class="at">color =</span> Processing.Method)) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Processing.Method))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>In the chart above, flavor almost looks like a perfect predictor, strong and positive.</li>
</ul>
</section>
<section id="categories" class="level3">
<h3 class="anchored" data-anchor-id="categories">2 Categories</h3>
<ul>
<li>Suppose there are only 2 processing methods for coffee beans: Wet/Washed and Natural/Dry.<br>
R takes Natural/Dry as the referent category value. Then we can create one dummy variable. A Dummy Variable is then assigned as either a 0 or 1. Let’s save the filtering of 2 methods into a new smaller dataset first and then running the lm model.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>coffee2cat <span class="ot">&lt;-</span> <span class="fu">filter</span>(coffee, Processing.Method <span class="sc">==</span> <span class="st">"Natural / Dry"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Washed / Wet"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coffee2cat<span class="sc">$</span>Processing.Method)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Washed / Wet  Washed / Wet  Natural / Dry Washed / Wet  Natural / Dry
[6] Washed / Wet 
6 Levels:  Natural / Dry Other ... Washed / Wet</code></pre>
</div>
</div>
<ul>
<li>Next, lets run a lm model using the newly filtered data.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>lmModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(TotalScore <span class="sc">~</span> Processing.Method, <span class="at">data =</span> coffee2cat)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalScore ~ Processing.Method, data = coffee2cat)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.1346  -0.9944   0.4554   1.5354   8.6154 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    82.3541     0.1704 483.193   &lt;2e-16 ***
Processing.MethodWashed / Wet  -0.3895     0.1950  -1.997    0.046 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.7 on 1061 degrees of freedom
Multiple R-squared:  0.003746,  Adjusted R-squared:  0.002807 
F-statistic:  3.99 on 1 and 1061 DF,  p-value: 0.04603</code></pre>
</div>
</div>
<ul>
<li>We can make a prediction of Washed/Wet.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmModel, <span class="fu">data.frame</span>(<span class="at">Processing.Method =</span> <span class="st">"Washed / Wet"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
81.96462 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept) Processing.MethodWashed / Wet 
                   82.3541434                    -0.3895252 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fl">82.3541</span> <span class="sc">-</span> <span class="fl">0.3895</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81.9646</code></pre>
</div>
</div>
</section>
<section id="using-more-than-2-categories" class="level3">
<h3 class="anchored" data-anchor-id="using-more-than-2-categories">Using More Than 2 Categories</h3>
<ul>
<li><p>A categorical variable may be defined by more than two categories.</p></li>
<li><p>Like mentioned above, we use multiple dummy variables to capture all categories, one for each category.</p></li>
<li><p>When a categorical variable has k &gt; 2 levels, we need to add k − 1 additional variables to the model.</p></li>
<li><p>Given the intercept term, we exclude one of the dummy variables from the regression.</p></li>
<li><p>The excluded variable represents the reference category. Example: Processing.Time Filtering by 3 categories: “Natural / Dry” “Washed / Wet“ or Other”) <span class="math inline">\(d_1=1\)</span> for Other and 0 otherwise <span class="math inline">\(d_2=1\)</span> for Washed/Wet and 0 otherwise <span class="math inline">\(d_1=d_2=0\)</span> indicates Natural/Dry referent category</p></li>
<li><p><span class="math inline">\(Score_i=β_0+β_1(I(Other)_i)+β_2(I(Wet)_i)+ϵ_I\)</span> <span class="math inline">\(β_0\)</span> represents the expected score for a coffee with 0 for the two dummy variables. That is, if it was a dry process coffee <span class="math inline">\(β_1\)</span> represents the expected difference in score for coffee with an Other roasting process, compared to the baseline level (dry process) <span class="math inline">\(β_2\)</span> represents the expected difference in score for Washed/Wet process coffee compared to dry process coffee. We have to estimate multiple “slopes” for this one variable - one corresponding to each non-reference level.</p></li>
<li><p>We can refilter the data to include the third category value.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>coffee3cat <span class="ot">&lt;-</span> <span class="fu">filter</span>(coffee, Processing.Method <span class="sc">==</span> <span class="st">"Natural / Dry"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Washed / Wet"</span> <span class="sc">|</span> Processing.Method <span class="sc">==</span> <span class="st">"Other"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coffee3cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X Species               Owner Country.of.Origin
1 1 Arabica           metad plc          Ethiopia
2 2 Arabica           metad plc          Ethiopia
3 4 Arabica yidnekachew dabessa          Ethiopia
4 5 Arabica           metad plc          Ethiopia
5 6 Arabica           ji-ae ahn            Brazil
6 7 Arabica       hugo valdivia              Peru
                              Farm.Name ICO.Number
1                             metad plc  2014/2015
2                             metad plc  2014/2015
3 yidnekachew dabessa coffee plantation           
4                             metad plc  2014/2015
5                                                 
6                                                 
                                Company Number.of.Bags Bag.Weight Harvest.Year
1     metad agricultural developmet plc            300      60 kg         2014
2     metad agricultural developmet plc            300      60 kg         2014
3 yidnekachew debessa coffee plantation            320      60 kg         2014
4     metad agricultural developmet plc            300      60 kg         2014
5                                                  100      30 kg         2013
6 richmond investment-coffee department            100      69 kg         2012
  Processing.Method        Color Aroma Flavor Aftertaste Acidity Body Balance
1      Washed / Wet        Green  8.67   8.83       8.67    8.75 8.50    8.42
2      Washed / Wet        Green  8.75   8.67       8.50    8.58 8.42    8.42
3     Natural / Dry        Green  8.17   8.58       8.42    8.42 8.50    8.25
4      Washed / Wet        Green  8.25   8.50       8.25    8.50 8.42    8.33
5     Natural / Dry Bluish-Green  8.58   8.42       8.42    8.50 8.25    8.33
6      Washed / Wet Bluish-Green  8.42   8.50       8.33    8.50 8.25    8.25
  Uniformity Clean.Cup Sweetness Cupper.Points Moisture Category.One.Defects
1         10        10        10          8.75     0.12                    0
2         10        10        10          8.58     0.12                    0
3         10        10        10          8.67     0.11                    0
4         10        10        10          8.58     0.12                    0
5         10        10        10          8.33     0.11                    0
6         10        10        10          8.50     0.11                    0
  Quakers Category.Two.Defects unit_of_measurement altitude_low_meters
1       0                    0                   m                1950
2       0                    1                   m                1950
3       0                    2                   m                1800
4       0                    2                   m                1950
5       0                    1                   m                  NA
6       0                    0                   m                  NA
  altitude_high_meters altitude_mean_meters TotalScore
1                 2200                 2075      90.58
2                 2200                 2075      89.92
3                 2200                 2000      89.00
4                 2200                 2075      88.83
5                   NA                   NA      88.83
6                   NA                   NA      88.75</code></pre>
</div>
</div>
<ul>
<li>We can make our new model object with the lm function.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>lmModel2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TotalScore <span class="sc">~</span> Processing.Method, <span class="at">data =</span> coffee3cat)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalScore ~ Processing.Method, data = coffee3cat)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.1346  -0.9646   0.4554   1.5354   8.6154 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    82.3541     0.1728 476.694   &lt;2e-16 ***
Processing.MethodOther         -1.0757     0.5639  -1.908   0.0567 .  
Processing.MethodWashed / Wet  -0.3895     0.1977  -1.971   0.0490 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.737 on 1086 degrees of freedom
Multiple R-squared:  0.005435,  Adjusted R-squared:  0.003603 
F-statistic: 2.967 on 2 and 1086 DF,  p-value: 0.05186</code></pre>
</div>
</div>
<ul>
<li>The overall model is not significant here, but one group still shows differences. Means poor predictor, but that there are still group differences (even if small) between Washed/Wet and Natural/Dry</li>
<li>Finally, we can make our new prediction of what the score would be in the Processing.Method was Other.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmModel2, <span class="fu">data.frame</span>(<span class="at">Processing.Method =</span> <span class="st">"Other"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
81.27846 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmModel2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)        Processing.MethodOther 
                   82.3541434                    -1.0756819 
Processing.MethodWashed / Wet 
                   -0.3895252 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fl">82.3541434</span> <span class="sc">-</span> <span class="fl">1.0756819</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81.27846</code></pre>
</div>
</div>
</section>
</section>
<section id="adding-in-a-numerical-variable" class="level2">
<h2 class="anchored" data-anchor-id="adding-in-a-numerical-variable">Adding in a Numerical Variable</h2>
<ul>
<li>We can add in another variable like Flavor. Flavor is a much stronger predictor.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>lmModel3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TotalScore <span class="sc">~</span> Flavor <span class="sc">+</span> Processing.Method, <span class="at">data =</span> coffee3cat)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmModel3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalScore ~ Flavor + Processing.Method, data = coffee3cat)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.6648  -0.3555   0.2157   0.7248   5.7972 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    31.4116     1.0691  29.380  &lt; 2e-16 ***
Flavor                          6.7151     0.1403  47.849  &lt; 2e-16 ***
Processing.MethodOther         -0.1274     0.3205  -0.398  0.69108    
Processing.MethodWashed / Wet   0.2931     0.1130   2.593  0.00964 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.553 on 1085 degrees of freedom
Multiple R-squared:  0.6802,    Adjusted R-squared:  0.6793 
F-statistic: 769.3 on 3 and 1085 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lmModel3, <span class="fu">data.frame</span>(<span class="at">Flavor =</span> <span class="dv">10</span>, <span class="at">Processing.Method =</span> <span class="st">"Other"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
98.43565 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmModel3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)                        Flavor 
                   31.4116160                     6.7151441 
       Processing.MethodOther Processing.MethodWashed / Wet 
                   -0.1274019                     0.2931262 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fl">31.411616</span> <span class="sc">+</span> <span class="fl">6.7151441</span> <span class="sc">*</span> <span class="dv">10</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.1274019</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 98.43566</code></pre>
</div>
</div>
<ul>
<li>After adjusting for aroma, and flavor, is there sufficient evidence to suggest a difference in mean score between dry vs.&nbsp;wet process beans? Explain, using a formal hypothesis test. $H_0: Processing.Method_{Washed / Wet} = Processing.Method_{Dry} $ $H_A: Processing.Method_{Washed / Wet}Processing.Method_{Dry} $</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>lmModel4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TotalScore <span class="sc">~</span> Aroma <span class="sc">+</span> Flavor <span class="sc">+</span> Processing.Method, <span class="at">data =</span> coffee2cat)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmModel4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TotalScore ~ Aroma + Flavor + Processing.Method, 
    data = coffee2cat)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.5344  -0.2720   0.2208   0.7122   4.7629 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    28.1650     1.1482  24.530  &lt; 2e-16 ***
Aroma                           1.6013     0.2134   7.502 1.32e-13 ***
Flavor                          5.5406     0.1987  27.884  &lt; 2e-16 ***
Processing.MethodWashed / Wet   0.2337     0.1079   2.166   0.0306 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.479 on 1059 degrees of freedom
Multiple R-squared:  0.7017,    Adjusted R-squared:  0.7009 
F-statistic: 830.6 on 3 and 1059 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>We find evidence that there is a difference between Washed/Wet processed coffee beans and dry processed beans as evident by the significant p-value &lt; .05.</p></li>
<li><p>Adjusting for aroma, flavor, and process, which country has the highest expected score? The lowest?</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate the predicted scores in the dataset</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>predicted_scores <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmModel4, <span class="at">newdata =</span> coffee2cat)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new dataframe with Country and predicted scores</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>predicted_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Country =</span> coffee2cat<span class="sc">$</span>Country, <span class="at">Predicted_Score =</span> predicted_scores)</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the country with the highest expected score</span></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>highest_expected_score <span class="ot">&lt;-</span> <span class="fu">filter</span>(predicted_data, Predicted_Score <span class="sc">==</span> <span class="fu">max</span>(Predicted_Score))</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>highest_expected_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Country Predicted_Score
1 Ethiopia        91.20569</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the country with the lowest expected score</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>lowest_expected_score <span class="ot">&lt;-</span> <span class="fu">filter</span>(predicted_data, Predicted_Score <span class="sc">==</span> <span class="fu">min</span>(Predicted_Score))</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>lowest_expected_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Country Predicted_Score
990 Guatemala        73.56705</code></pre>
</div>
</div>
<ul>
<li><p>We find that Ethiopia has the highest predicted score and Guatemala has the lowest predicted score based on Aroma, Flavor, and Processing Method.</p></li>
<li><p>What percentage of the variability in the total score is explained by a linear relationship with the predictors in your model?</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(lmModel4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.702         0.701  1.48      831. 1.35e-277     3 -1922. 3854. 3879.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<ul>
<li>We can look at the R-squared value of .693 and adjusted R-squared value of .692 and state that about 69% of the variable in total score is explained by a linear relationship with the predictors in our model.</li>
</ul>
</section>
</section>
<section id="review-and-summary" class="level1">
<h1>Review and Summary</h1>
<section id="using-ai" class="level2">
<h2 class="anchored" data-anchor-id="using-ai">Using AI</h2>
<ul>
<li><p>Use the following prompts on a generative AI, like chatGPT, to learn more about regression analysis in R.</p></li>
<li><p>Explain how to perform simple linear regression in R. Use the lm() function and discuss how to interpret the slope, intercept, and R-squared values from the regression output.</p></li>
<li><p>What is the coefficient of determination (R-squared) in regression analysis, and how does it relate to the goodness of fit? How can the residual standard error (RSE) and adjusted R-squared help in interpreting a model?</p></li>
<li><p>Describe how to perform multiple linear regression in R using the lm() function. How do you interpret the coefficients for multiple predictors, and what do the p-values tell you about their significance?</p></li>
<li><p>What does the F-statistic in a regression output indicate? How does it help in determining the significance of a regression model, and what role does it play when comparing multiple models?</p></li>
<li><p>Explain how ANOVA is related to regression analysis. How can the F-test be used to assess the significance of regression models? What are residuals in a regression model, and how can analyzing them help assess model fit? How is the sum of squared errors (SSE) related to residual analysis?</p></li>
<li><p>What is multicollinearity, and why is it problematic in multiple regression? How can you detect multicollinearity in R using the vif() function, and what steps can be taken to address it?</p></li>
<li><p>How can you use a fitted regression model to make predictions for new data in R? Explain how the predict() function works and provide an example using both simple and multiple regression.</p></li>
<li><p>Given the output from the summary() function for a regression model in R, explain how to interpret the coefficients, R-squared, adjusted R-squared, residual standard error, and p-values.</p></li>
<li><p>Describe how to use the p-value method for variable selection in multiple regression. How do you iteratively remove insignificant predictors while monitoring the R-squared and adjusted R-squared values?</p></li>
</ul>
</section>
<section id="regression-lab" class="level2">
<h2 class="anchored" data-anchor-id="regression-lab">Regression Lab</h2>
<p><strong>A dataset</strong> has one continuous predictor variable (<code>Income</code>, in thousands) and one continuous outcome (<code>Debt</code>, in dollars). A student runs <code>lm(Debt ~ Income, data = df)</code> and gets the following summary output:</p>
<pre><code>Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  210.30      41.82    5.03  0.00004 ***
Income        10.44       1.19    8.77  9.66e-09 ***

Residual standard error: 63.26 on 26 degrees of freedom
Multiple R-squared:  0.7526,    Adjusted R-squared:  0.7423 
F-statistic: 76.86 on 1 and 26 DF,  p-value: 9.66e-09</code></pre>
<p>Write out the regression equation, interpret the slope and intercept in plain English, and state what the <span class="math inline">\(R^2\)</span> tells you about model fit.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Regression equation:</strong> <span class="math display">\[\hat{y} = 210.30 + 10.44 \times \text{Income}\]</span></p>
<p><strong>Intercept (</strong><span class="math inline">\(b_0 = 210.30\)</span>): When Income is zero (i.e., $0 in thousands), the predicted debt payment is $210.30. In this context, the intercept is a mathematical anchor for the line — there is likely no data at Income = 0, so it should not be interpreted as a meaningful real-world value on its own.</p>
<p><strong>Slope (</strong><span class="math inline">\(b_1 = 10.44\)</span>): For every additional $1,000 in income (one unit increase in Income), debt payments are predicted to increase by $10.44. Income and debt move in the same direction — higher earners tend to carry higher debt payments.</p>
<p><span class="math inline">\(R^2 = 0.7526\)</span>: Income explains approximately <strong>75.3%</strong> of the variability in debt payments. The remaining 24.7% is explained by other factors not in the model. An <span class="math inline">\(R^2\)</span> above 0.5 is generally considered moderate-to-strong in business applications — this model fits the data reasonably well.</p>
</div>
</div>
</div>
<p><strong>Using the regression output above</strong>, make a prediction for a person with an income of $85,000 (Income = 85) using both the regression equation and the <code>predict()</code> function in R. Show both approaches.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Using the equation:</strong> <span class="math display">\[\hat{y} = 210.30 + 10.44 \times 85 = 210.30 + 887.40 = 1097.70\]</span></p>
<p>Predicted debt payment: approximately <strong>$1,097.70</strong></p>
<p><strong>Using <code>predict()</code> in R:</strong></p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(Simple, <span class="fu">data.frame</span>(<span class="at">Income =</span> <span class="dv">85</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Both approaches give the same answer. The <code>predict()</code> function is more convenient when making many predictions at once or when the model includes multiple predictors, since it handles all the coefficient multiplication automatically.</p>
</div>
</div>
</div>
<p><strong>A multiple regression model</strong> is built to predict <code>Balance</code> from <code>Income</code>, <code>Rating</code>, <code>Limit</code>, <code>Cards</code>, <code>Age</code>, and <code>Education</code>. The initial model returns the following Adjusted <span class="math inline">\(R^2\)</span> values as variables are removed one at a time using the p-value method:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Variables removed</th>
<th>Adjusted R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 (full model)</td>
<td>—</td>
<td>0.8764</td>
</tr>
<tr class="even">
<td>1</td>
<td>Education (p = 0.71)</td>
<td>0.8765</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Cards (p = 0.53)</td>
<td>0.8760</td>
</tr>
<tr class="even">
<td>3</td>
<td>Age (p = 0.06)</td>
<td>0.8753</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Limit (p = 0.059)</td>
<td>0.8745</td>
</tr>
</tbody>
</table>
<p>Explain why Adjusted <span class="math inline">\(R^2\)</span> barely changes — and in step 1 actually <em>increases</em> — as variables are removed, and why this supports the variable-removal decisions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Why Adjusted</strong> <span class="math inline">\(R^2\)</span> barely changes: The variables being removed (Education, Cards, Age, Limit) were contributing almost nothing to the model’s explanatory power. When a predictor is truly uninformative, removing it does not reduce how well the model fits the data — it just eliminates noise.</p>
<p><strong>Why it increased in step 1:</strong> The Adjusted <span class="math inline">\(R^2\)</span> formula penalizes models for having extra predictors. The raw <span class="math inline">\(R^2\)</span> always increases or stays flat when you add a variable, but the Adjusted <span class="math inline">\(R^2\)</span> can actually <em>decrease</em> if a variable’s marginal contribution is less than the penalty for including it. When Education (p = 0.71) was removed, the penalty relief from dropping one useless predictor outweighed the tiny loss in explained variance, nudging Adjusted <span class="math inline">\(R^2\)</span> slightly upward.</p>
<p><strong>Why this supports the decisions:</strong> A good variable-selection strategy keeps Adjusted <span class="math inline">\(R^2\)</span> stable or improves it while reducing model complexity. Starting at 0.8764 and finishing at 0.8745 after removing four predictors means the simpler final model explains almost exactly as much variation as the full model — with fewer parameters, easier interpretation, and less risk of overfitting. The two remaining predictors (Income and Rating) are doing essentially all the work.</p>
</div>
</div>
</div>
<p><strong>A researcher</strong> includes <code>Ethnicity</code> as a predictor in a regression model. It has three categories: Asian.American, Black, and White. R automatically creates dummy variables and produces this output (condensed):</p>
<pre><code>Coefficients:
                    Estimate
(Intercept)           720.5     ← Asian.American baseline
EthnicityBlack        -18.3    (p = 0.12)
EthnicityWhite        -13.1    (p = 0.08)</code></pre>
<p>Identify the reference category, interpret the intercept and each dummy coefficient, and explain why there is no <code>EthnicityAsian.American</code> row in the output.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Reference category:</strong> Asian.American — it is the category that R excluded from the output and absorbed into the intercept.</p>
<p><strong>Intercept (720.5):</strong> The predicted outcome for an Asian.American individual (when all other predictors are held at zero, or if this is the only predictor). It represents the baseline group mean.</p>
<p><strong>EthnicityBlack (−18.3):</strong> Black respondents are predicted to have an outcome 18.3 units <em>lower</em> than Asian.American respondents, on average, all else equal. The p-value of 0.12 means this difference is <strong>not statistically significant</strong> at <span class="math inline">\(\alpha = 0.05\)</span> — we cannot conclude that the group means differ from the Asian.American baseline.</p>
<p><strong>EthnicityWhite (−13.1):</strong> White respondents are predicted to score 13.1 units lower than the Asian.American baseline. Again, p = 0.08 is not significant at <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><strong>Why no Asian.American row:</strong> Including all three dummy variables (Asian.American, Black, White) would create <strong>perfect multicollinearity</strong> — the three dummies would always sum to 1, making the model mathematically unsolvable. R automatically drops one category (alphabetically first by default, which is Asian.American here) to serve as the reference. Every other category is interpreted <em>relative to</em> that reference.</p>
<p><strong>Note:</strong> A non-significant dummy coefficient does not mean you remove that category from the model — it means that category is not significantly <em>different from the reference</em>. You remove or keep the entire categorical variable together.</p>
</div>
</div>
</div>
<p><strong>Explain</strong> why multicollinearity is a problem in multiple regression, and interpret the following VIF output. Which predictors pass the assumption, and what would you do about the one(s) that do not?</p>
<pre><code>   Income    Rating     Limit 
    1.011     2.234    14.822</code></pre>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Why multicollinearity is a problem:</strong> When two or more predictors are highly correlated with each other, the model cannot reliably separate their individual effects. This inflates the standard errors of the affected coefficients, making them appear non-significant even when they genuinely predict the outcome. It can also produce coefficient estimates with wrong signs — a predictor that should have a positive relationship might appear negative in the output. Predictions from the model may still be accurate, but individual coefficient interpretation becomes unreliable.</p>
<p><strong>Interpreting the VIF output:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>VIF</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Income</td>
<td>1.011</td>
<td>✅ Passes — no correlation with other predictors</td>
</tr>
<tr class="even">
<td>Rating</td>
<td>2.234</td>
<td>✅ Passes — moderate but acceptable (well under 5)</td>
</tr>
<tr class="odd">
<td>Limit</td>
<td>14.822</td>
<td>❌ Fails — severe multicollinearity (VIF ≥ 10)</td>
</tr>
</tbody>
</table>
<p><strong>What to do about Limit:</strong> A VIF of 14.8 suggests <code>Limit</code> is highly correlated with one or more other predictors in the model (likely <code>Rating</code>, since credit limit and credit rating are often set together). Options:</p>
<ol type="1">
<li><strong>Drop one of the correlated variables.</strong> If <code>Limit</code> and <code>Rating</code> are largely redundant, remove whichever is less theoretically important.</li>
<li><strong>Check the correlation matrix</strong> — <code>cor(Credit$Limit, Credit$Rating)</code> — to confirm which variable is driving the problem.</li>
<li><strong>Keep it if prediction is the goal.</strong> If you only care about the model’s overall predictions (not the individual coefficients), multicollinearity is less harmful. The Adjusted <span class="math inline">\(R^2\)</span> and predictions remain valid even when VIF is high.</li>
</ol>
</div>
</div>
</div>
<p><strong>A model predicting employee salary</strong> (in $000s) from <code>YearsExperience</code> and <code>Department</code> (Finance, Marketing, Operations — three categories) returns these coefficients:</p>
<pre><code>(Intercept)             52.1
YearsExperience          2.8
DepartmentMarketing     -4.5
DepartmentOperations    -9.2</code></pre>
<p>Write the four prediction equations (one per department), then calculate the predicted salary for a Marketing employee with 7 years of experience and an Operations employee with 12 years of experience.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Reference category:</strong> Finance (alphabetically first, omitted from output).</p>
<p><strong>Four prediction equations:</strong></p>
<ul>
<li><strong>Finance:</strong> <span class="math inline">\(\hat{y} = 52.1 + 2.8 \times \text{Years}\)</span></li>
<li><strong>Marketing:</strong> <span class="math inline">\(\hat{y} = 52.1 + 2.8 \times \text{Years} + (-4.5) = 47.6 + 2.8 \times \text{Years}\)</span></li>
<li><strong>Operations:</strong> <span class="math inline">\(\hat{y} = 52.1 + 2.8 \times \text{Years} + (-9.2) = 42.9 + 2.8 \times \text{Years}\)</span></li>
</ul>
<p>All three lines have the <strong>same slope</strong> (2.8 — each additional year of experience adds $2,800 regardless of department) but <strong>different intercepts</strong> (Finance starts highest, then Marketing, then Operations).</p>
<p><strong>Predictions:</strong></p>
<p>Marketing, 7 years: <span class="math inline">\(47.6 + 2.8 \times 7 = 47.6 + 19.6 = \$67,200\)</span></p>
<p>Operations, 12 years: <span class="math inline">\(42.9 + 2.8 \times 12 = 42.9 + 33.6 = \$76,500\)</span></p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(salary_model, <span class="fu">data.frame</span>(<span class="at">YearsExperience =</span> <span class="dv">7</span>,  <span class="at">Department =</span> <span class="st">"Marketing"</span>))</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(salary_model, <span class="fu">data.frame</span>(<span class="at">YearsExperience =</span> <span class="dv">12</span>, <span class="at">Department =</span> <span class="st">"Operations"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note that even though Operations has the lowest intercept, the Operations employee earns more here because they have significantly more experience — the slope effect eventually overtakes the department penalty.</p>
</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This lesson covered simple linear regression, multiple regression, and regression with categorical variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Topic</th>
<th>Key concepts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple linear regression</td>
<td><code>lm()</code>, slope (<span class="math inline">\(b_1\)</span>), intercept (<span class="math inline">\(b_0\)</span>), regression equation <span class="math inline">\(\hat{y} = b_0 + b_1 x\)</span></td>
</tr>
<tr class="even">
<td>Goodness of fit</td>
<td>RSE (Residual Standard Error), R², Adjusted R²</td>
</tr>
<tr class="odd">
<td>Sum of squares</td>
<td>SSE (unexplained), SSR (explained), SST (total)</td>
</tr>
<tr class="even">
<td>F-test</td>
<td>Overall model significance; ratio of explained to unexplained variance</td>
</tr>
<tr class="odd">
<td>Coefficient t-tests</td>
<td>Individual predictor significance; slope = 0 vs.&nbsp;slope ≠ 0</td>
</tr>
<tr class="even">
<td>Predictions</td>
<td><code>predict()</code>, <code>coef()</code></td>
</tr>
<tr class="odd">
<td>Multiple regression</td>
<td>Two or more predictors, partial regression coefficients, holding others constant</td>
</tr>
<tr class="even">
<td>Variable selection</td>
<td>P-value method: remove highest p-value iteratively; monitor Adjusted R²</td>
</tr>
<tr class="odd">
<td>Multicollinearity</td>
<td><code>vif()</code> from <code>car</code> package; VIF &lt; 5 passes, VIF ≥ 10 fails</td>
</tr>
<tr class="even">
<td>Dummy variables</td>
<td>Categorical predictors as binary indicators; reference category held in intercept</td>
</tr>
<tr class="odd">
<td>Multi-category dummies</td>
<td>k − 1 dummy variables for k categories; R handles automatically in <code>lm()</code></td>
</tr>
<tr class="even">
<td>Predictions with categorical variables</td>
<td><code>predict()</code> with <code>data.frame()</code> specifying category as character string</td>
</tr>
</tbody>
</table>
<p><strong>What comes next:</strong> The regression model you built here — predicting a continuous outcome from a mix of continuous and categorical predictors — is the foundation for machine learning methods covered in our business anlaytics major or our MSBA program here in the Mason School of Business. Techniques like k-nearest neighbors, decision trees, and ensemble models all share the same goal of minimizing prediction error, and many of the diagnostics and model-evaluation concepts introduced here (residuals, overfitting, the bias-variance tradeoff) carry forward directly.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./anova.html" class="pagination-link" aria-label="ANOVA and Correlation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">ANOVA and Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>